### ISSUE TITLE
Can NerdTreedisplay only the files that exist in QuickFix list?

### ISSUE THREAD

**Issue by oguzbilgic** [preservim/nerdtree#1053]
There are different ways QuickFix list is populated (make, lsp errors, search, git diff, etc). I find the QuickList extremely useful as it standardizes many outputs and gives me a way to cycle through them. But I find the QuickFix buffer very hard to use for seeing the big picture the way it displays/lists the files. I would like to have a NerdTree display those files using a tree format. Basically a tree way of viewing files in Quickfix. (I know that QuickFix can include same file multiple times, so there would be a simple de-duping for the tree view)

**Comment by PhilRunninger** [comment]
This is outside the stated purpose of the plugin, and would overly complicate an already bloated codebase. Besides, you'd be losing functionality you only get inside the Quickfix buffer, like jumping directly to the offending line of code.
