### ISSUE TITLE
After moving a file, don't open it in current buffer

### ISSUE THREAD

**Issue by geoyws** [preservim/nerdtree#1055]
#### Description

Currently each time I rename a file, it opens up in the current NERDTree buffer.

**Comment by PhilRunninger** [comment]
Files are **not** opened after renaming a file. If you're reporting a bug, please close this issue and create a bug issue with as much information as you can provide.

**Comment by PhilRunninger** [comment]
@geoyws I'm going to close this issue, because it reads more like a bug report than a feature request. If you are experiencing problems with NERDTree, open a new bug issue.

**Comment by geoyws** [comment]
Apologies, haven't been checking my issues. This was quite a while ago and things seem to be working now with my setup.
