### ISSUE TITLE
NERDTreeFind fails with vim-startify or empty buffer

### ISSUE THREAD

**Issue by andys8** [preservim/nerdtree#1059]
#### Description

`:NERDTreeFind` prints this error when used with `vim-startify`. My guess is this is related.

![image](https://user-images.githubusercontent.com/13085980/69344793-47e0b280-0c70-11ea-9d58-2c33a702ad92.png)

Possible related, because it's working fine with not exisiting/written files:
https://github.com/scrooloose/nerdtree/pull/1043

**Comment by willfindlay** [comment]
I'm actually also getting this issue but without vim-startify.

**Comment by andys8** [comment]
@willfindlay What's in your buffer when this issue occurs?

**Comment by andys8** [comment]
This happens with an empty buffer, too. You can reproduce the error like this:

```shell
$ echo "new buffer" | vim -
:NERDTreeFind

E716: Key not present in Dictionary: putCursorHere
```

I basically want the behavior of `:NERDTreeFind` - but to fail **silently** in case the file isn't saved or is not a file. Is there currently a way to achieve this or could it be done with an extra command or argument? @PhilRunninger  :)

**Comment by andys8** [comment]
The absolut best thing would be if `:NERDTreeToggle` could be highlighting the current file, if it exists, otherwise just toggles. Not sure if it's currently possible.

**Comment by andys8** [comment]
Also `:NERDTreeFind` in nerdtree itself on a file jumps to the containing directory. It looks like random, side-effecty behavior and not intended.

**Comment by andys8** [comment]
The last few comments of myself are probably different feature requests or maybe can be achieved with vimscript. I created a PR to fix the root issue and fail with the wanted error message to close this issue.

**Comment by tbergeron** [comment]
I have the same issue when using :NERDTreeFind in an empty buffer. I understand why it happens but it would be great to have a way of achieving this:

> The absolut best thing would be if `:NERDTreeToggle` could be highlighting the current file, if it exists, otherwise just toggles. Not sure if it's currently possible.

**Comment by andys8** [comment]
@tbergeron if you want to, you can try out the PR #1081 I submitted. I'm confident it should fix the issue, and also might be merged soon. Positive feedback would be nice, though.

**Comment by tbergeron** [comment]
@andys8 I tried your PR and it shows: `NERDTree: no file for the current buffer` instead of opening the current directory. Is that the desired behavior? Before, it would show the error but then it would open the tree view. Now it just shows the error message. Thanks

**Comment by andys8** [comment]
That's the intended behavior. I guess it was like this before it was broken, too.

**Comment by tbergeron** [comment]
@andys8 oh I see! :rofl: I thought it would open the current directory if no file is opened in the buffer. I wish there would be some way to toggle to the current opened file. Good job fixing that bug though :P

**Comment by andys8** [comment]
Thanks @PhilRunninger
