### ISSUE TITLE
I can not open file that contains LF in the name

### ISSUE THREAD

**Issue by rkuchumov** [preservim/nerdtree#1063]
#### Self-Diagnosis

- [ ] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [ ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [ ] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [ ] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System: Linux 5.3
- [ ] Vim/Neovim version `:echo v:version`:  801
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`:  6.2.0
- [ ] vimrc settings
    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. echo aaa > "$(printf 'aa\nbb')"
2. vim
3. :NERDTree

**Comment by PhilRunninger** [comment]
Who really puts linefeeds in their filenames? Given this is a very unlikely scenario, I'm going to close this issue and suggest you open the file another way.
