### ISSUE TITLE
Moving a file with NERDTreeAutoDeleteBuffer=1 results in the file type being removed and breaks syntax highlighting

### ISSUE THREAD

**Issue by nickjj** [preservim/nerdtree#1069]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: Ubuntu 18.04 (LTS)
- [x] Vim/Neovim version: VIM - Vi IMproved 8.0
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.3.0
- [x] vimrc settings
    - [x] NERDTree variables
    ```vim
    let g:NERDTreeShowHidden=1
    let g:NERDTreeAutoDeleteBuffer=1
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1.  `echo "## Hello" > /tmp/a.md`
2. `vim /tmp/a.md`
3. Toggle NERDTree open and select the file
4. `mm` to move the file
5. Change the file name from `a.md` to `b.md`

#### Current Result (Include screenshots where appropriate.)

The buffer correctly switches to `b.md` but the file type has been removed which in turn removes the syntax highlighting.

Now we need to run either `set ft=markdown` or `:e` manually and things work again.

#### Expected Result

The buffer would have `b.md` open with the file type set to Markdown which in turn has correct syntax highlighting without having to manually do anything extra.

**Comment by normenmueller** [comment]
> #### Environment (for bug reports)
> * [x]  Operating System: macOS 10.15.2
> * [x]  Vim/Neovim version: VIM - Vi IMproved 8.1
> * [x]  NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.4.1
> * [x]  vimrc settings
>   
>   * [x]  NERDTree variables
>   
>   ```viml
>   let g:NERDTreeChDirMode = 2
>   let g:NERDTreeIgnore = ['\~$']
>   let g:NERDSpaceDelims = 1
>   ```
>   * Other NERDTree-dependent Plugins
>     
>     * [ ]  jistr/vim-nerdtree-tabs
>     * [ ]  ryanoasis/vim-devicons
>     * [ ]  tiagofumo/vim-nerdtree-syntax-highlight
>     * [ ]  Xuyuanp/nerdtree-git-plugin
>     * [] Others (specify):
>   * [x]  I've verified the issue occurs with only NERDTree installed.
> 
> #### Steps to Reproduce the Issue
> 1. `echo "## Hello" > /tmp/a.md`
> 2. `vim /tmp/a.md`
> 3. Toggle NERDTree open and select the file
> 4. `mm` to move the file
> 5. Change the file name from `a.md` to `b.md`
> 
> #### Current Result (Include screenshots where appropriate.)
> The buffer correctly switches to `b.md` but the file type has been removed which in turn removes the syntax highlighting.
> 
In my case "Now we need to run either `set ft=markdown` or `:e` manually and things work again." does not work. I've to restart Vim. No other chance to re-enable syntax highlighting. 
> 
> #### Expected Result
> The buffer would have `b.md` open with the file type set to Markdown which in turn has correct syntax highlighting without having to manually do anything extra.

**Comment by nickjj** [comment]
@normenmueller you need to likely set `let g:NERDTreeAutoDeleteBuffer=1`, otherwise the old buffer stays open.

**Comment by normenmueller** [comment]
@nickjj Will try, but I also have the problem that the highlighting is disabled in case of creating a new file by `ma`.

**Comment by normenmueller** [comment]
@nickjj Even with `let g:NERDTreeAutoDeleteBuffer=1` it does not work. And still, even creating a new file disables highlighting completely.

**Comment by nickjj** [comment]
I'm not sure, you may want to open a different issue. This one is dedicated to the exact bug listed in my original post.

**Comment by normenmueller** [comment]
> I'm not sure, you may want to open a different issue. This one is dedicated to the exact bug listed in my original post.

Done: #1070
