### ISSUE TITLE
NERDTree jumpy on opening a floating window

### ISSUE THREAD

**Issue by codingedward** [preservim/nerdtree#1074]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question
Hello, I have an issue with NERDTree <> Coc.nvim integration where on Vim's floating window showing NERDTree suddenly moves the directory/file under CursorLine to the top of the tree.

Here's a screenshot of what's happening:
![Screen-Recording-2020-01-06-at-16 22 44](https://user-images.githubusercontent.com/15171489/71820816-658f9d00-30a1-11ea-8a0c-e7da62aff12b.gif)

After debugging to find which setting was responsible, I found that setting `set updatetime=<value>` would change how soon this would happen as it affects `CursorHold` but I could not figure how NERDTree uses this setting.

I also raised an issue with `Coc.nvim`'s maintainer who advised that I should avoid `jump to float window` but unfortunately I couldn't get any pointers on how to do that.

Kindly help.

**Comment by PhilRunninger** [comment]
Possible duplicate of #983.

**Comment by codingedward** [comment]
Hi @PhilRunninger, closing in favor of #983. I will be sure to share what I can to help debug this issue 💪 .
