### ISSUE TITLE
Menu / move command lost source file

### ISSUE THREAD

**Issue by JESii** [preservim/nerdtree#1078]
#### Self-Diagnosis

- [x ] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [ x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ x] Operating System: MacOS Mojave 10.14.6
- [x ] Vim/Neovim version `:echo v:version`: Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 16:51:54)
- [ x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.4.3
- [ ] vimrc settings
    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ x] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. editing a file `src/components/Summary/Confirmation/confirmation.js`
2. In NREDTree, type `mm` on that entry
3. move the file to `src/components/Summary/LegalCopy/LegalCopy.js` (that file already exists)

#### Current Result (Include screenshots where appropriate.)
Removes the existing file, and deletes the source file -- the text from the source file was not moved to the existing/target file and is nowhere to be found.

#### Expected Result
Should actually move the file.

I've done lots of moves in the years I've been using NERDTree, and never seen this issue. Fortunately, it was a (relatively) small file but I shudder to think that one of my larger files could be lost like this.
I've searched my tree for possibly misnamed files and can't find anything that might be the lost file.
If I can reproduce, I will...

**Comment by PhilRunninger** [comment]
`git checkout .` No, seriously... it looks like there needs to be a check that we don't overwrite existing files. Or at least prompt first.

**Comment by JESii** [comment]
Thanks, @PhilRunninger -- Your quick response is much appreciated. 
If possible, a prompt for allowing/denying the action would be very nice?
