### ISSUE TITLE
Cannot enter child dirs

### ISSUE THREAD

**Issue by calvinfroedge** [preservim/nerdtree#108]
All my folders have ?~V? before them and I cannot enter into directories with the enter key.  Any ideas?  I installed via pathogen.  Here is a screenshot of what I'm experiencing:  http://screencast.com/t/X9jarQ9W

**Comment by gbell12** [comment]
This happens with Putty on Windows ssh'ed into an Ubuntu box.

The `export LANG=en_US.UTF-8` suggestion didn't help, and in fact makes the cursor "consume" characters as you move around.  `let g:NERDTreeDirArrows=0` does fix it, but then I'm looking like a grandpa stuck in ASCII days.

**Comment by zwhitchcox** [comment]
This is broken again.

**Comment by zwhitchcox** [comment]
Don't know what happened, but it fixed itself, nvmd

**Comment by lacostenycoder** [comment]
try just adding this to your .vimrc
`set encoding=utf-8`

**Comment by Dvbnhbq** [comment]
@lacostenycoder  Thank you, that worked for me on Windows 10 WLS, which is xenial with old VIM 7.4.

**Comment by amaxcz** [comment]
let g:NERDTreeDirArrowExpandable = '>'
let g:NERDTreeDirArrowCollapsible = 'v'

works well without utf-8
