### ISSUE TITLE
Childnode in same alignment as parent

### ISSUE THREAD

**Issue by maharjanaman** [preservim/nerdtree#1084]
After updating to latest version, I got this issue,
<img width="294" alt="Screen Shot 2020-01-28 at 15 39 45" src="https://user-images.githubusercontent.com/14164484/73253503-c4e65600-41e4-11ea-87be-5e3b411de843.png">

`hooks`, `info` are all childnode of `.git`.

**Comment by PhilRunninger** [comment]
This looks like a problem in either [indentLine](https://github.com/Yggdroot/indentLine) or [devicons](https://github.com/ryanoasis/vim-devicons), depending on who you believe. The error probably surfaced after your [last commit](https://github.com/maharjanaman/dotfiles/commit/ba8d5fa7ab5b9f11c085039940b36dc4a9afabe4). 

See https://github.com/Yggdroot/indentLine/issues/152 for a more in-depth discussion, as well as a solution.
