### ISSUE TITLE
Expanding all in the current directory recursively

### ISSUE THREAD

**Issue by aGIToz** [preservim/nerdtree#1086]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question
Hello, I don't if this is the right place to ask this question, _kindly suggest me if not so._

Is there any any way to expand all (close all) the directory inside my pwd recursively in nerdtree. This is to improve my workflow.

Thanks

**Comment by PhilRunninger** [comment]
Use these default keystrokes: `PO` to recursively expand the root folder, and `PX` to recursively close the root folder. Please review `:h NERDTree-P`, `:h NERDTree-O` and `:h NERDTree-X` again.
