### ISSUE TITLE
Theme on picture on README.md

### ISSUE THREAD

**Issue by ca4e** [preservim/nerdtree#1088]
Just wondering what theme/color-scheme is used on the screenshot in the "README.md".

Thanks in advance!

**Comment by PhilRunninger** [comment]
That screenshot was added by @lifecrisis in commit 6efef86. This would be a question for him to answer.

**Comment by lifecrisis** [comment]
@ca4e:

The color scheme is [gruvbox](https://github.com/morhetz/gruvbox).  It looks great when using graphical Vim, but I don't recommend it in the terminal (depending on your terminal emulator, it may break in mysterious ways).
