### ISSUE TITLE
Is there any way to delete, copy multiple files in NERDTree?

### ISSUE THREAD

**Issue by aGIToz** [preservim/nerdtree#1089]
#### Self-Diagnosis

- [x ] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x ] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [ x] I have searched the web for an answer to my question.

#### State Your Question

Is there any way to delete, copy multiple files in NERDTree, like in the vims inbuilt `netrw-mf`? It allows to mark files and do multiple operations (edit, copy, delete, rename, compress, hide). Check `:help netrw-mf` for more.

**Comment by PhilRunninger** [comment]
There is a separate plugin for that: https://github.com/PhilRunninger/nerdtree-visual-selection. It doesn't use marks like netrw does, but instead, it uses a visual selection.

**Comment by elig0n** [comment]
why doesn't this get merged ?

**Comment by PhilRunninger** [comment]
Keeping it separate gives people who want the functionality the abililty to install it, while keeping NERDTree codebase as small as possible. (One could, however, argue that it's too late for that, given there are 6200+ lines of code already.)

Sometimes the extra plugins introduce performance issues that some people would not tolerate.

The NERDTree API is there also to encourage other developers to contribute their own NERDTree extensions, as has been done with [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin), [vim-devicons](https://github.com/ryanoasis/vim-devicons), [vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight), and [nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops).
