### ISSUE TITLE
Cursor position is wrong on startup

### ISSUE THREAD

**Issue by koallen** [preservim/nerdtree#1091]
#### Self-Diagnosis
- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: RHEL 7.7
- [x] Vim/Neovim version `:echo v:version`: 800
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.7.0
- [x] vimrc settings
    - [x] NERDTree variables

    ```vim
    " open on start up in console for directory
    augroup OpenNerdTreeOnDirectory
        autocmd!
        autocmd StdinReadPre * let s:std_in=1
        autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && 
            \ !exists("s:std_in") | ene | exe 'NERDTree' argv()[0] | endif
    augroup END

    " close when only nerdtree left
    augroup CloseNerdTree
        autocmd!
        autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && 
            \ b:NERDTree.isTabTree()) | q | endif
    augroup END

    " ignore certain files and directories
    let g:NERDTreeIgnore = ['^.git$', '^node_modules$']

    " show hidden files by default in certain directories
    augroup NerdTreeShowHiddenFiles
        autocmd!
        autocmd BufEnter ~/.dotfiles** let g:NERDTreeShowHidden = 1
    augroup END

    " automatically delete buffer for files deleted in NERDTree
    let g:NERDTreeAutoDeleteBuffer = 1

    nnoremap <Leader>f :NERDTreeFocus<CR>
    ```

    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [x] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Open neovim on a directory (e.g. `nvim .`)

#### Current Result (Include screenshots where appropriate.)
vim-airline shows that the nerdtree window is active (has the color in the airline). However, the cursor is actually in the empty buffer window.

#### Expected Result
cursor stays in nerdtree window.

#### Additional notes

I think this only started to happen after I upgraded my plugins yesterday. Previously it has been working fine (last time I update should be around mid-January). I'm not sure if some code change

**Comment by koallen** [comment]
If I manually run `ene`  followed by `exe 'NERDTree' '/some/path'` it will correctly open and focus on NERDTree. Only when on startup it's not working as expected.

**Comment by PhilRunninger** [comment]
With only **NERDTree**, **nerdtree-git-plugin** and **vim-arline** installed, and using the vimrc given in the issue, I do not see this behavior. My cursor is located in the NEDTree window, as expected, and Airline indicates it is the active window. Perhaps you have another autocommand interfering with the ones you show above.

**Comment by koallen** [comment]
Turns out this is due to a recent change in the `indentLine` plugin (https://github.com/Yggdroot/indentLine/issues/289).

Closing the issue.
