### ISSUE TITLE
cd into a path without manually traversing

### ISSUE THREAD

**Issue by Aster89** [preservim/nerdtree#1096]
I haven't found anything in the doc about this.

Sometimes a directory structure can be like this:
```
dir
├── dir1
├── dir2
├── dir3
└── bigDir
    ├── smallDir
    │   ├── file1
    │   └── file2
    ├── more
    ├── than
    ├── a
    ├── thousand
    ├── files
    ├── in
    ├── this
    ├── very
    ├── big
    ├── or
    ├── better
    ├── huge
    ├── directory
    └── WOW
```
Now let's say the cwd is `dir`, therefore when I open NERDTree, I see this:
```
dir1
dir2
dir3
bigDir
```
I want to cd into `bigDir/smallDir` directly, to avoid having to render the content of `bidDir`.

**Comment by PhilRunninger** [comment]
You can use the command: `:NERDTree bigDir/smallDir`. This will replace the current NERDTree with one that has `smallDir` as its root.

**Comment by Aster89** [comment]
@PhilRunninger , one think I didn't think about when opening this issue, is that sometimes the `dir` in the example above is the "focused" directory in the NERDTree window, but it is **not** the folder from which I opened Vim, therefore it is not the output of `:pwd`. In this case, the command you suggested cannot work.

Do you have a suggestion for this?

**Comment by PhilRunninger** [comment]
You can use any relative or absolute path that will get you where you want to go. For example, if you're in the `dir1` directory, you can use: `:NERDTree ../bigDir/smallDir`.

An absolute path could look like this: `:NERDTree /home/Aster89/dir/bigDir/smallDir`

Remember that tab completion works on directories when you're typing out the `:NERDTree` command. That saves a lot of typing.

**Comment by Aster89** [comment]
Yes, and that is what I'm doing at the moment, but it writing the absolute or relative path can be difficult; as in, I don't necessarily remember all the way up to the current `:pwd`.

<s>On the other hand, it would be very useful if one could use `:NERDTree path` from the tree root</s> Good, it seems that I needed to know of `cd`, `CD`. Very useful :)
