### ISSUE TITLE
Empty buffer is created when using vsplit(s) on a previously opened and closed file.

### ISSUE THREAD

**Issue by AwkwardKore** [preservim/nerdtree#1097]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: MacOS 10.15.4
- [x] Vim/Neovim version `:echo v:version`: vim 801
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`:  6.7.0
- [x] vimrc settings
    - [x] NERDTree variables
    ```vim
   let NERDTreeShowHidden=1
   let NERDTreeIgnore=['\.DS_Store$', '\.swp$', '\.git$']
   let NERDTreeShowLineNumbers=1
   let NERDTreeMinimalUI=1
   let NERDTreeWinSize=35
   let g:NERDTreeStatusline='NERDTree'
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Create two files in an empty directory: ```file1.txt``` and ```file2.txt```.
2. Open vim in that directory.
3. Open file1.txt with nerdtree ```o```.
4. Open file2.txt with nerdtree ```o```.
5. Delete buffer where file1.txt is open ```:bd {buffer number}```
6. Open file1.txt as vsplit with nerdtree ```s```

#### Current Result (Include screenshots where appropriate.)
You get a new empty buffer on the buffer list, in this case it was the buffer ```4 [No Name]```:

![Screen Shot 2020-03-31 at 19 54 00](https://user-images.githubusercontent.com/7896727/78091415-f7016900-7389-11ea-9a01-dc497bbf60da.png)

If you do the 6 steps and keep quitting ```:q``` the file1.txt and opening again with vsplit```s```, it keeps creating new empty buffers. ***Note that this time I didn't delete the buffer***, I just quit the file with ```:q```. This means that you only have to delete the buffer once and keep using vsplit```s``` for it to trigger the issue multiple times. This is after quitting and opening the same file 3 times:

![Screen Shot 2020-03-31 at 20 11 46](https://user-images.githubusercontent.com/7896727/78092157-35982300-738c-11ea-9072-58e06548c436.png)

#### Expected Result
The expected result should be the two files open on vsplit without having to create a new empty buffer. Since it has another open file on vim, it shouldn't have to open a new empty buffer. This expected behavior is what happens when you use split command on nerdtree```i``` instead of vsplit```s```. They should behave the same when it comes to handling the buffers:

![Screen Shot 2020-03-31 at 20 00 38](https://user-images.githubusercontent.com/7896727/78091547-637c6800-738a-11ea-9cd7-691e3d4f6e5d.png)

#### Comments
I already have the solution to this problem on my forked repository. I created this issue because this seems like a bug but I don't know if this is actually the correct behavior.

**Comment by PhilRunninger** [comment]
I confirmed this behavior, and it definitely is not correct. Go ahead and create a pull request to merge your fix in.

Thanks!
