### ISSUE TITLE
6.7.6 issue 

### ISSUE THREAD

**Issue by 90geek** [preservim/nerdtree#1104]
#### Self-Diagnosis

- [ ] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
open file issue ,`处理 function nerdtree#ui_glue#invokeKeyMap..293..292..<SNR>128_customOpenFile..322..338..394..395..229 时发生错误:`
- [ ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [ ] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System: centos7
- [ ] Vim/Neovim version `:echo v:version`: vim 704
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 
- [ ] vimrc settings
    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. 
6.7.5
#### Current Result (Include screenshots where appropriate.)
```
处理 function nerdtree#ui_glue#invokeKeyMap..293..292..<SNR>128_customOpenFile..322..338..394..395..229 时发生错误:
```

**Comment by iesvme** [comment]
I have the same problem.

**Comment by 90geek** [comment]
> I have the same problem.

It's no problem to go back to the previous version
