### ISSUE TITLE
When you try to open a file after moving it, A directory does open

### ISSUE THREAD

**Issue by scrawld** [preservim/nerdtree#1106]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: Ubuntu 18.04.2 LTS
- [x] Vim/Neovim version `:echo v:version`: 802
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: NERDTree (6.7.7) quickhelp
- [x] vimrc settings
    My Vimrc: https://github.com/scrawld/vimrc/blob/master/.vimrc
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Use the NERDTree menu to move a directory of files
2. Then use NERDTree to try to open the file and actually open the NERDTree directory

#### Current Result (Include screenshots where appropriate.)

![image](https://camo.githubusercontent.com/460e006d5a019dbc082467fa67648b92b35295fb/68747470733a2f2f7331372e61636f6e766572742e636f6d2f636f6e766572742f70337236382d63647836372f326e3463652d71786466392e676966)

#### Expected Result
    Opens the specified file

**Comment by PhilRunninger** [comment]
I cannot reproduce this error with the instructions given. Can you provide more information? Screenshots, maybe. Can you verify the move actually happened in a file explorer or another terminal before trying to open the file?

**Comment by scrawld** [comment]
@PhilRunninger I'm sorry that I don't quite understand what you mean. Could you please give me a specific debugging method? Thank you

**Comment by scrawld** [comment]
I tried to use my vim profile on CentOS 7, but the problem didn't appear.I'm not sure if it has anything to do with the vim compilation process
I did this when I compiled vim [Linux 下源码编译安装vim 8.2 并添加 python 支持](https://www.jianshu.com/p/aa5ea81bbc72)

**Comment by scrawld** [comment]
This is my vim compile command
```
./configure --with-features=huge \
--enable-multibyte \
--enable-pythoninterp=dynamic \
--with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
--enable-python3interp=dynamic \
--with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu \
--enable-cscope \
--enable-gui=auto \
--enable-gtk2-check \
--enable-fontset \
--enable-largefile \
--disable-netbeans \
--enable-fail-if-missing \
--prefix=/usr/local
```

**Comment by scrawld** [comment]
I had the same problem with another ubuntu that.
Contos doesn't have this problem.
The steps that cause the problem are roughly opening the directory and closing all Windows, and then the problem occurs when you try to open the file.
![avatar](https://s17.aconvert.com/convert/p3r68-cdx67/577fi-8jfje.gif)

**Comment by scrawld** [comment]
Sorry, the root cause of the problem was found because I added one more line of configuration to the configuration file. Now I'll just delete this line of configuration
```
" If more than one window and previous buffer was NERDTree, go back to it.
autocmd BufEnter * if bufname('#') =~# "^NERD_tree_" && winnr('$') > 1 | b# | endif
```
