### ISSUE TITLE
Auto close NERDTree to exit nvim does not trigger the VimLeave event

### ISSUE THREAD

**Issue by sihoang** [preservim/nerdtree#1108]
#### Self-Diagnosis

- [x ] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x ] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x ] I have searched the web for an answer to my question.

#### State Your Question
I follow the README to close NERDTree on close of last file:
```vim
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
```
When I do `:q` on last file, it does exit nvim, however, the event VimLeave is not triggered.  To verify, I add:
```vim
autocmd vimleave * :!touch ~/vimleave
```
I guess this might be a bug in nvim?

**Comment by PhilRunninger** [comment]
No bug. This behavior is purposeful, and is not related to NERDTree. See `:h autocmd-nested` for more details. To get your **VimLeave** event to fire, just add the `nested` flag to the **BufEnter** autocmd, like so:

```vim
autocmd bufenter * nested if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
````
