### ISSUE TITLE
space line column couldn't be removed

### ISSUE THREAD

**Issue by falcucci** [preservim/nerdtree#1109]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

I would like to have an option to remove this space line column from the tree. 

<img width="385" alt="Screen Shot 2020-04-18 at 18 41 09" src="https://user-images.githubusercontent.com/33763843/79672005-8b4e3700-81a4-11ea-8c0e-3266a4aedbb4.png">

Is it a bug or a really dumb question?

**Comment by PhilRunninger** [comment]
`let NERDTreeMinimalUI = 1` will turn of all 3 of those lines at the top. There is no option for removing only the blank line.

**Comment by falcucci** [comment]
sorry I was refering to the sign column.

really isn't a nerdtree issue, then I fixed that with `set signcolumn=no`.

ty @PhilRunninger good tip aswell.
