### ISSUE TITLE
Calling NERDTreeFind after 3 times messes with the rendering

### ISSUE THREAD

**Issue by sobrinho** [preservim/nerdtree#1110]
I have no idea why it happens after the 3rd call.

#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: MacOS
- [x] Vim/Neovim version `:echo v:version`: 800
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.7.7
- [x] vimrc settings
    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. `mkdir -p a/b/c/d`
1. `touch a/b/c/d/{a,b,c,d,e}`
1. `touch a/b/c/{a,b,c,d,e}`
1. `vi a/b/c/d/a`
1. call `:NERDTreeToggle`
1. go to `a` and type `O` to expand all dirs
1. call `:NERDTreeToggle` it opens correcltly
1. call `:NERDTreeToggle` it closes correcltly
1. call `:NERDTreeToggle` it opens correcltly
1. call `:NERDTreeToggle` it closes correcltly
1. call `:NERDTreeToggle` it opens bugged

#### Current Result (Include screenshots where appropriate.)

![Screen Shot 2020-04-18 at 18 56 55](https://user-images.githubusercontent.com/26460/79672222-69ee4a80-81a6-11ea-9ae4-2f1ca1bbd638.png)

#### Expected Result

![Screen Shot 2020-04-18 at 18 57 00](https://user-images.githubusercontent.com/26460/79672231-75da0c80-81a6-11ea-8b4a-044a2454f1f1.png)

**Comment by PhilRunninger** [comment]
I'm not seeing this behavior. Please provide more information, as requested in the issue template. Both of your screenshots show an indentation that is not possible with NERDTree by itself. Do you have some vimscript that is changing the indentation from its usual 2 spaces?

**Comment by PhilRunninger** [comment]
@sobrinho, Do you have any more information for me to use in diagnosing this issue?

**Comment by sobrinho** [comment]
@PhilRunninger I'm not sure which plugin is messing this up but here are my vimfiles: https://github.com/sobrinho/vimfiles

This issue does not always happen, I just tried to replicate it again and it didn't work in the structure I replicated but any complex dir structure causes the issue.

I can pair up with you if you want to check anything remotely, just let me know what time it does work for you.

**Comment by sobrinho** [comment]
I updated all my packages to the latest version and it seems like something fixed it, even the highlight changed in nerdtree.

Closing for now.
