### ISSUE TITLE
Add NERDTreeCloseAll command

### ISSUE THREAD

**Issue by przepompownia** [preservim/nerdtree#1117]
A command that closes all NERDTree buffers can be useful before save generic vim session. 

`sessionoptions` does not allow to exclude `nofile` buffers.

**Comment by PhilRunninger** [comment]
You can do this in your `.vimrc` with the `tabdo` command.
```vim
:tabdo NERDTreeClose
```
You can then create your own mapping (shown below) or command to combine it with the `:mksession` command.
```vim
nnoremap <leader>S :tabdo NERDTreeClose<CR>:mksession<CR>
```
