### ISSUE TITLE
A robust solution to deal with previous NERDTree instances when switching tabs?

### ISSUE THREAD

**Issue by niccolomineo** [preservim/nerdtree#1121]
I am wondering if there is a robust way to avoid the previously opened tab keeping focus on NERDTree and also solve the problem that, when I go back to a previously opened tab, the tree is collapsed to the root.

<img width="340" alt="Schermata 2020-05-10 alle 18 12 54" src="https://user-images.githubusercontent.com/5409469/81504918-5426fd80-92ec-11ea-936b-ba9c303b86b1.png">

I am using these snippets at the moment:
```
autocmd BufWinEnter * silent NERDTreeMirror
autocmd VimEnter * wincmd w

function! OpenInTab(node)
    call a:node.activate({'reuse': 'all', 'where': 't'})
endfunction
autocmd VimEnter * call NERDTreeAddKeyMap({ 'key': '<LeftRelease>', 'scope': "FileNode", 'callback': "OpenInTab", 'override':1 })
```

**Comment by PhilRunninger** [comment]
Sorry it took me a while to respond. Try this augroup, which remembers the state of the buffer when you leave it, and restores it when entering:
```vim
augroup bufferEvents
    autocmd!
    autocmd BufLeave * let b:winview = winsaveview()
    autocmd BufEnter * if(exists('b:winview')) | call winrestview(b:winview) | endif
augroup END
```
and change your first two autocommands to this:
```vim
autocmd TabNew * NERDTreeMirror|wincmd w
autocmd VimEnter * NERDTree|wincmd w
```
`BufWinEnter` happens more often than necessary for what you're doing, and `|wincmd w` will keep the buffers in the right window.

**Comment by PhilRunninger** [comment]
@niccolomineo, is it OK if I close this one?

**Comment by niccolomineo** [comment]
Yep, thanks!
