### ISSUE TITLE
Suggested config partially interacts with vim-plug call

### ISSUE THREAD

**Issue by andresbrocco** [preservim/nerdtree#1125]
#### Self-Diagnosis

- [X] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [X] I have reviewed the NERDTree documentation. `:h NERDTree`
- [X] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [X] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [X] Operating System: Linux Ubuntu 20
- [X] Vim/Neovim version `:echo v:version`: 801 
- [X] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.7.9
- [X] vimrc settings
    - [X] NERDTree variables
    As suggested in [the wiki](https://github.com/preservim/nerdtree/wiki#how-can-i-make-sure-vim-does-not-open-files-and-other-buffers-on-nerdtree-window) to make sure vim does not open files and other buffers on NerdTree window:
    ```vim
        " If more than one window and previous buffer was NERDTree, go back to it.
        autocmd BufEnter * if bufname('#') =~# "^NERD_tree_" && winnr('$') > 1 | b# | endif
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [X] Others (specify): vim-plug 
    - [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Position the cursor on an opened NERDTree 
2. Try to call a vim-plug function, like ':PlugInstall' or ':PlugClean'

#### Current Result (Include screenshots where appropriate.)
![nerdtree_conflict_with_vim-plug](https://user-images.githubusercontent.com/33270103/82005538-fe2fbe00-963b-11ea-9911-321ca5cb8f0c.png)

#### Expected Result
![correct_behaviour](https://user-images.githubusercontent.com/33270103/82005570-0d167080-963c-11ea-823b-1a39bf93e9f1.png)

**Comment by andresbrocco** [comment]
Sorry, I added the bug label by mistake and don't know howto remove it. In fact, this issue is not THAT important...

**Comment by PhilRunninger** [comment]
**vim-plug** uses the command `vertical topleft new` to create its window. According to the Vim documentation `:help :new`,

> This behaves like a ":split" first, and then an ":enew" command.

The `split` command creates the new window with NERDTree in it, and `enew` puts a new empty buffer in the window. After this command runs, your auto command runs and switches back to the NERDTree buffer. I'm not certain, but then `:PlugInstall` may then be trying to modify the NERDTree buffer in the window it created, assuming its own buffer is there.

You might be able to do this, but it could break **vim-plug** if it relies on auto commands to do its thing: `:noautocmd PlugInstall`

### No, wait!
Check out `:help g:plug_window`. You can override the command in my 1st paragraph. Try 
```vim
let g:plug_window = 'noautocmd vertical topleft new'
```

**Comment by andresbrocco** [comment]
It worked for me! I'll add your suggestion to that wiki topic!
