### ISSUE TITLE
NERDTreeQuitOnOpen doesn't work

### ISSUE THREAD

**Issue by catoblepa** [preservim/nerdtree#113]
On file open nerdtree remain open.

In my .vimrc NERDTreeQuitOnOpen is set to 1:
let NERDTreeQuitOnOpen=1

:version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct  6 2011 10:19:44)

**Comment by yueyingjuesha** [comment]
@catoblepa Sorry it's still not working for me
