### ISSUE TITLE
vim show strange string when nerdtree turns on

### ISSUE THREAD

**Issue by laoshaw** [preservim/nerdtree#1131]
#### Self-Diagnosis

- [X ] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [ X] I have reviewed the NERDTree documentation. `:h NERDTree`
- [ X] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [ X] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System: ubuntu 18.04
- [ ] Vim/Neovim version `:echo v:version`: 802
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.7.13
- [ ] vimrc settings
    - [ ] NERDTree variables
    ```vim
let NERDTreeMinimalUI = 1
let g:NERDTreeWinSize = 30
let g:NERDTreeDirArrowExpandable = ''
let g:NERDTreeDirArrowCollapsible = ''
let g:NERDTreeChDirMode=2
let g:NERDTreeMouseMode=3
let g:NERDTreeIgnore = ['\.pyc$','\~$','\.db$', '\.sqlite$', '__pycache__']
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [x ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): nerdtree-execute nerdcommenter
    - [ x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. open any file then open nerdtree, the use down arrow key, or leave insert mode with Esc, or mouse-click somewhere, 

#### Current Result (Include screenshots where appropriate.)
I see a strange string shown at random places, the string starts with  square-style-character(with 0018 inside tiny block, some utf-8 graph char?) then followed by: >4,2m.
#### Expected Result
no strange string shown

**Comment by laoshaw** [comment]
One more comment: this only occurs using gnome-terminal/lxterminal where TERM=xterm256-color or xterm-color, it does not happen using xterm when TERM=xterm-color or xterm256-color. It used to work well until today's upgrade of ubuntu vim and nerdtree plugin(not sure which one triggered this problem)

**Comment by PhilRunninger** [comment]
Can you share a screenshot?

**Comment by laoshaw** [comment]
![image](https://user-images.githubusercontent.com/18351761/82711099-190cbe80-9c4a-11ea-95dc-4460e89ae50d.png)

the last block(behind letter m) is cursor while taking the screenshot, ignore it

**Comment by laoshaw** [comment]
After I disabled https://github.com/Xuyuanp/nerdtree-git-plugin the issues changed, keyboard move the cursor did not trigger the strange string, however a :w will trigger it.

**Comment by laoshaw** [comment]
it might not be nerdtree issue afterall, I disabled nerdtree, then run "PlugClean", I saw the same strange string on the Plug pane, though it will disappear after a few seconds.

All these never occurred before today's upgrade. It might be vim's problem.

**Comment by PhilRunninger** [comment]
Is it actually changing the text of the file, or is it a display artifact? Try running `:redraw!` to see if it clears up. Check out your prior version of NERDTree to either rule it out or assign blame to it.

The characters you see are probably `<Esc>[4;2m` (001B is in the box). This is an [ANSI escape sequence](http://ascii-table.com/ansi-escape-sequences.php), and the ones ending in `m` set the graphics mode. `4` turns on underscore, and `2` is undefined. My guess is that whatever is writing that out is doing it incorrectly, and it's not NERDTree.

**Comment by laoshaw** [comment]
it's just a display artifact.
after more debugging I agree it's not about nerdtree, sorry, I downgraded vim and it works fine, the newest 8.2vim release on ubuntu 18.04 broke it, I'm building vim8.2 from source instead now. 

Thanks!
