### ISSUE TITLE
Shift + i show warning: Can not make changes, modifiable is off.

### ISSUE THREAD

**Issue by ngocthienvnn** [preservim/nerdtree#1133]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System: Kubuntu 20.04 
- [ ] Vim/Neovim version `:echo v:version`: gvim 802 
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.7.13
- [ ] vimrc settings
    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1.  Open a folder which is having some hidden files
2. Shift + i to show hidden file

#### Current Result (Include screenshots where appropriate.)
Can not make changes, 'modifiable' is off
#### Expected Result
Hidden file is shown

**Comment by PhilRunninger** [comment]
Doublecheck the key assigned to that function `: echo NERDTreeMapToggleHidden`. `I` is the default, but you might have changed it.

Make sure you or another plugin hasn't redefined the `Shift+i` mapping. Type the command `:verbose map I` while in the NERDTree window to see what it is asked to do. You should see the following:
```
n  I           *@:call nerdtree#ui_glue#invokeKeyMap("I")<CR>
        Last set from ~/.vim/pack/bundle/opt/nerdtree/lib/nerdtree/key_map.vim line 58
```

**Comment by ngocthienvnn** [comment]
![image](https://user-images.githubusercontent.com/14000527/82827179-aebd7d80-9ed8-11ea-968a-f563a5011380.png)
You are right, gvim or vim gui assigned I for middle mouse event. that cause ToggleHidden now working.

**Comment by PhilRunninger** [comment]
Your screenshot doesn't show the capital `I` mapping. Your arrow is pointing to `<Shift-Insert>`. Were you able to resolve this issue?

**Comment by ngocthienvnn** [comment]
@PhilRunninger sorry, it's my mistake. This issue occurs on vim-gtk3, i reverted back to vim-gtk. Now, it works well.
