### ISSUE TITLE
Can the distance between directory and its parent node be set to 1 space

### ISSUE THREAD

**Issue by gVimer** [preservim/nerdtree#1135]
#### Description
Now I think indenting two spaces is a bit of a waste of space
      
![QQ截图20200529210050](https://user-images.githubusercontent.com/6241431/83262488-a8d4de80-a1ef-11ea-862a-a021f652c0f1.png)

**Comment by gVimer** [comment]
I like chang two sapce to one space
 let treeParts .= (self.path.isDirectory || g:NERDTreeDirArrowExpandable ==# '' ? '' : '  ')
==》let treeParts .= (self.path.isDirectory || g:NERDTreeDirArrowExpandable ==# '' ? '' : ' ')
after this change  i can‘ot open a file or dir

**Comment by PhilRunninger** [comment]
Revert your changes to NERDTree. There is a lot more to it than that one line of code, as you discovered. Add this file to your setup, in the location given in the comment. It has worked out well for me.

```vim
" This block changes the indentation of NERDTree to appear as 1 space per
" level instead of the normal 2 spaces. It works only if your vim has the
" +conceal feature turned on, and it must be saved as
" ~/.vim/after/syntax/nerdtree.vim to work properly.

if has("conceal")
    syntax clear NERDTreeOpenable
    syntax clear NERDTreeClosable
    let s:dirArrows = escape(g:NERDTreeDirArrowCollapsible, '~]\-').escape(g:NERDTreeDirArrowExpandable, '~]\-')
    exec 'syntax match CompressSpaces #['.s:dirArrows.' ]\zs \ze.*' . g:NERDTreeNodeDelimiter . '# containedin=ALL conceal'
endif
```

I'll put this in the Wiki also.

**Comment by gVimer** [comment]
This is the effect  I want!
3Q very much for your reply！
