### ISSUE TITLE
how use a command

### ISSUE THREAD

**Issue by lyb-Q** [preservim/nerdtree#1137]
Ask me how to insert a conflict with vim when you use the window opened with the A command. How to set up, thank you.

**Comment by PhilRunninger** [comment]
I'm not sure I understand your question. Could you provide some more information?

**Comment by lyb-Q** [comment]
> I'm not sure I understand your question. Could you provide some more information?

I'm sorry I didn't make myself clear.I use A to change into insertion mode in vim, I want to use nerdtree-A to enlarge the open window in nerdtree

**Comment by PhilRunninger** [comment]
`A` enters Insert mode at the end of the current line. Are you changing its behavior? I interpreted your comment to mean you changed `A` to behave like `i`. That being the case, I conducted the following tests.
```
:map A i
ibar<Esc>0Afoo<Esc>
:NERDTree
A
A
```
or
```
:nnoremap A i
ibar<Esc>0Afoo<Esc>
:NERDTree
A
A
```
In both cases `A` Vim entered Insert mode at the current location in a non-NERDTree buffer. The result is a single line (`foobar`) in the buffer. In NERDTree, `A` expands and contracts the window.

If I misunderstood what you are trying to do, please share the code you are using. A minimal `.vimrc` file would be helpful in figuring this out.

**Comment by lyb-Q** [comment]
I want to use nerdtree ```A```  to enlarge the open window operation in vim normal mode. But it doesn't work out, it change insert mode.How to configure it

 I look at which of the help documentation says 

``` A: Zoom(maximize-minimize) the NERDT ree window ```

> conflict with vim insertion mode, how to avoid this

**Comment by PhilRunninger** [comment]
Let me clarify: While in the NERDTree window, you want to press `A` to maximize the NERDTree window, but instead it enters insert mode. Is that correct?

1. There is no configuration needed to make this work. NERDTree sets up the `A` key mapping when it initializes.
1. NERDTree is a readonly, unmodifiable buffer. It should never go into Insert mode.

I suspect something is overriding your `A` key mapping. While you're in the NERDTree window, enter this command, and tell me what it says.
```vim
:verbose map A
```
It should echo this back to you:
```
n  A           *@:call nerdtree#ui_glue#invokeKeyMap("A")<CR>
        Last set from ~/.vim/pack/bundle/opt/nerdtree/lib/nerdtree/key_map.vim line 58
```
Again, if you can also show your `vimrc` file, that would be very helpful.

**Comment by PhilRunninger** [comment]
On the other hand, if you expect NERDTree to expand its window when the cursor is **not** in the NERDTree window, you could set it up this way:
```vim
:nmap A :NERDTreeFocus<CR>A
```

**Comment by PhilRunninger** [comment]
Or do you want `A` to expand the current window, even if it isn't NERDTree? You would have to write your own function to do that. The keystrokes you could use are `<C-w>|` to make the window as wide as possible, and `<C-w>=` to make all windows as equal in size as possible.

**Comment by PhilRunninger** [comment]
@lyb-Q, has your question been answered? If so, please close the issue; otherwise, please further clarify your question.

Thank you.

**Comment by lyb-Q** [comment]
> Sorry, I should have made my statement incorrect. There's no problem with using the feature, just this I don't know how to do it.

> I want to enlarge these two windows.This is the window that opens after my code jumps

![addd](https://s1.ax1x.com/2020/06/16/NFUM0P.png)

**Comment by lyb-Q** [comment]
> @lyb-Q, has your question been answered? If so, please close the issue; otherwise, please further clarify your question.
> 
> Thank you.
