### ISSUE TITLE
alternate behavior for `o`

### ISSUE THREAD

**Issue by approaching236** [preservim/nerdtree#1140]
#### Description

I find myself leaving vim to touch a file to edit from the current directory, but having to remember the path that I was just exploring with NERD tree. If I had my druthers I would change the behavior of `o` in NERD tree (enter toggles just fine), to 'open' the line below a directory, just to touch a file with the given name in that dir.

another explanation:
```
nested/
  directories/
    I/
      don't/
        want_to_remember/ // <- cursor on this line
          files...
```
then hit `o` to enter into the file name entry 'dialog'
```
nested/
  directories/
    I/
      don't/
        want_to_remember/ // 
          new_file_name.hot_jam <- now cursor on this line
          files...
```
on exit, touch a file at that dir with the newly entered name

This feels like it would be a minor arcane nightmare to implement, but damn would it save me some fiddly grief

**Comment by PhilRunninger** [comment]
Yeah, that would be a nightmare. Fortunately, this feature already exists in the built-in file system menu. Just follow these keystrokes.

1. Press `m` to open the menu.
1. Press `a` to select the `(a)dd a childnode` option.
1. The prompt is prefilled with the path of the directory you're on. Just continue typing the filename at the end of the prompt: `new_file_name.hot_jam`

That's it. You're new empty file has been created. The NERDTree is refreshed, and you can then press `o` to open your new file.

**Comment by approaching236** [comment]
Right on, thank you so much!
