### ISSUE TITLE
Howto remove top filepath line?

### ISSUE THREAD

**Issue by tmpm697** [preservim/nerdtree#1142]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

When open nertree in vim, it's always display filepath and it doesn't change when you open file in subdirs.

e.g:
```
/home/user/path/to/somewhere/
> dir1
> dir2
  file1
  file2
```

`/home/user/path/to/somewhere/` is where I open vim. I don't like it to appear when I open nerdtree. how to remove it?

**Comment by PhilRunninger** [comment]
You can put this line in a file called `~/.vim/after/syntax/nerdtre.vim`:
```vim
highlight link NERDTreeCWD Ignore
```
This will not gain you an extra line of text in your window, but will cause the text's foreground to be the same as the background.

I would advise against this, however. That line of text shows the root of the tree, which can be changed with the `C`, `CD`, `U`, or `u` keys. (See `:h NERDTree-C`, `:h NERDTree-CD`, `:h NERDTree-U` and `:h NERDTree-u` to see what they do.) After using these to change your root several times, you might prefer always knowing what the current root of the tree is.

**Comment by tmpm697** [comment]
Nothing change in my nerdtree, still showing filepath after having nerdtre.vim with content as you mention.

Is there an option to disable it, why ppl hardcode this?

**Comment by tmpm697** [comment]
Seem if I open nerdtree and manually enter this line in command mode: `highlight link NERDTreeCWD Ignore`, it does hide to filepath but in put under `~/.vim/after/syntax/nerdtre.vim` won't work, even in `~/.vimrc`.

**Comment by PhilRunninger** [comment]
I misspelled the file name. It needs to be `nerdtree.vim`. There is no option to change it, and what I gave you is just a workaround to a change perfectly reasonable design.

**Comment by tmpm697** [comment]
Yes I need to find a away to find it `perfectly`, I ended up using tpope's plugin instead.
