### ISSUE TITLE
Bookmarked files won't open in split window, despite the answers to #111

### ISSUE THREAD

**Issue by hugo-manet** [preservim/nerdtree#1143]
Hi !
The opening shortcuts i, s, gs, gi won't work on bookmarked files.
I have installed version 6.8.0 with Vundle three days ago. The quickhelp doesn't reference these shortcuts, there only is a "bookmark table mappings" section which seems to apply to both directory bookmarks and file bookmarks.
Maybe I'm doing something wrong, or maybe there is an option to toggle ?
Sincerely,

**Comment by PhilRunninger** [comment]
You are not doing anything wrong. Those shortcuts were never applicable to bookmarks. I'll add them.
