### ISSUE TITLE
Detecting When NerdTree is Opening 

### ISSUE THREAD

**Issue by cxgslegend** [preservim/nerdtree#1146]
Hello, sorry if this is an obvious question. But I cannot seem to find the answer to this (maybe I am just bad at looking for it). 

I am trying to detect when NerdTree is opening a buffer. I need this because my winwidth, and winminwidth settings are effecting Nerdtree when set globally. Also, I resize splits to maximize the current split (and I don't want to maximize NerdTree ever). 

My first attempt at this was to detect if I was entering a non-NerdTree buffer, and set local settings. But I guess these variables are not defined at the time the auto comands are running. 
```
autocmd BufEnter * if (!exists("b:NERDTree") | setlocal winheight=5 | setlocal winminheight=5 | setlocal winwidth=85 | setlocal winminwidth=70 | :res | :vertical res | endif
```
My logic was that this should run in all buffers except the NerdTree buffer. But unfortunately, it runs all buffers. 

Any advice would be greatly appreciated. Thanks!

**Comment by PhilRunninger** [comment]
I think the way `resize` works requires something a little more complicated. This `.vimrc` snippet works with vertical splits, but you can take it from here to handle the horizontal splits.
```vim
set winminwidth=5
autocmd WinEnter * resize |
                 \ vertical resize |
                 \ let current_win = winnr() |
                 \ let NT_win = bufwinnr('NERD_tree_*') |
                 \ if NT_win ==# current_win |
                 \   execute 'noautocmd setlocal winwidth='.g:NERDTreeWinSize |
                 \ elseif NT_win !=# -1 |
                 \   execute 'noautocmd '.NT_win.'wincmd w' |
                 \   execute 'noautocmd setlocal winwidth='.g:NERDTreeWinSize |
                 \   noautocmd wincmd p |
                 \ endif
```

**Comment by cxgslegend** [comment]
Thanks @PhilRunninger! I tweaked this a little but I got it to work. Also, my understanding of winminwidth was wrong. Setting it sets it for all windows. So that was messing me up too. This solves my issue. You can close the issue if you want. And thanks for making such an amazing plugin!

**Comment by PhilRunninger** [comment]
You're welcome, but I can't take credit for NERDTree. It's @scrooloose 's brainchild; I'm just helping it along. If you don't mind, can you share your final autocmd for others who might be interested?

**Comment by cxgslegend** [comment]
Oh sorry, I saw you on a bunch of the issues, so I assumed you must be the maintainer. But still, I thank you for the help!

I changed what you wrote to the following 
```
set winheight=5 
set winminheight=5 
set winwidth=60 
set winminwidth=40

autocmd WinEnter * let current_win = winnr() |
                 \ let NT_win = bufwinnr('NERD_tree_*') |
                 \ if NT_win ==# current_win |
                 \   execute 'noautocmd setlocal winwidth='.g:NERDTreeWinSize |
                 \ elseif NT_win !=# -1 |
                 \   execute 'noautocmd '.NT_win.'wincmd w' |
                 \   noautocmd wincmd p |
                 \   resize |
                 \   vertical resize |
                 \ endif
```
I moved the resize and vertical resize inside the elseif because I didn't want it doing it inside of nerdtree windows. I also removed the winwidth inside the elseif because the resize and vertical resize would just make the non-nerdtree window as big as it could be based on the global winminwidth, and winminheight. 

But I learned a lot from this. I honestly didn't even know about noautocmd or that you could move to a window with <num>wincmd w.

**Comment by PhilRunninger** [comment]
No worries. I'm just happy to keep it going.

It looks like you have a couple of lines that don't do anything. `wincmd w` followed by `wincmd p` just switches to NERDTree and back to the previous window. You can maybe take them out.

Yes, there is a lot to learn about Vim script buried deep in the help pages. I'm learning all the time myself.
