### ISSUE TITLE
NERDTreeIgnore

### ISSUE THREAD

**Issue by trueFireblade** [preservim/nerdtree#1148]
I am running NERDTree in Neovim via VimPlug on a archlinux setup and I added the line `let g:NERDTreeIgnore=['.+\.class']` to my init.vim but for some reason NERDTree still displays all the class files, even though I as far as I saw from the stuff I read in the issues and the doc that the line should be exaclty like that!

**Comment by PhilRunninger** [comment]
This looks like a duplicate of #1107. I wasn't able to reproduce that issue. You mentioned Neovim and Arch Linux, which may be a clue. Are you able to use your vim setup on another platform or in Vim? Does this happen there as well?

**Comment by trueFireblade** [comment]
Thanks for linking that post, using the regex "\.class$" worked! So for some reason your regex parser had some troubles with understanding the ".+"!

**Comment by trueFireblade** [comment]
@

**Comment by PhilRunninger** [comment]
That's probably because the `+` needs to be escaped. You could have used `['.\+\.class$']`.
