### ISSUE TITLE
NERDTree will lose its width when the buffer next to it is closed

### ISSUE THREAD

**Issue by leighmcculloch** [preservim/nerdtree#1152]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: `Debian Buster`
- [x] Vim/~Neovim~ version `:echo v:version`: `802`
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: `6.8.0`
- [x] vimrc settings
    - [x] NERDTree variables
    ```vim
    let g:NERDTreeWinSize = 31
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [x] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] ~I've verified the issue occurs with only NERDTree installed.~ [This issue occurs frequently when using tabs in the way that is supported by vim-airline. This might not be the traditional way to use tabs, but I think it is worth reporting.]

#### Steps to Reproduce the Issue
1. Open multiples files in VIM.
   <img width="794" alt="Screen Shot 2020-07-12 at 11 05 01 PM" src="https://user-images.githubusercontent.com/351529/87276280-da9abf80-c494-11ea-9739-a7e2d6c91367.png">

2. Toggle open NERDTree which opens on the left.
   <img width="794" alt="Screen Shot 2020-07-12 at 11 05 14 PM" src="https://user-images.githubusercontent.com/351529/87276320-ee462600-c494-11ea-8ad9-9f89d5604f88.png">

3. Switch back to buffer on the right.
   <img width="794" alt="Screen Shot 2020-07-12 at 11 05 24 PM" src="https://user-images.githubusercontent.com/351529/87276337-f4d49d80-c494-11ea-865f-32b001cc7de5.png">

4. Close buffer on the left with `:bdelete`.
   <img width="794" alt="Screen Shot 2020-07-12 at 11 05 33 PM" src="https://user-images.githubusercontent.com/351529/87276350-f900bb00-c494-11ea-8960-00fff859237d.png">

5. Switch to another open file.
<img width="794" alt="Screen Shot 2020-07-12 at 11 05 43 PM" src="https://user-images.githubusercontent.com/351529/87276361-fdc56f00-c494-11ea-8436-a6ace4fdc983.png">

6. Toggle open NERDTree which open on the left, using maximum width, leaving buffer that was open only a single column of text on right.
<img width="794" alt="Screen Shot 2020-07-12 at 11 06 24 PM" src="https://user-images.githubusercontent.com/351529/87276368-01f18c80-c495-11ea-9b3f-aa4040c7c7b0.png">

#### Current Result (Include screenshots where appropriate.)
See the last screenshot above. The NERDTree buffer is open on the left but is using maximum width leaving only one column of text space on the right for the buffer that was open. I believe this logically makes sense because the NERDTree window changed size to the full width in step 4 when the buffer next to NERDTree was closed.

#### Expected Result
I expected NERDTree to retain its configured size when it is reopened, but I can also see a very valid expectation that the window retains its width whenever it is changed, so I'm not sure there's a clear direction.

I have managed to work around this for my workflow using: https://github.com/leighmcculloch/vim_dotfiles/blob/master/vimrc#L135

When I open NERDTree with `NERDTreeFind`, I call `vertical resize 31` immediately afterwards. It fixes the issue for me resulting in step 6 from above looking like this:
<img width="794" alt="Screen Shot 2020-07-12 at 11 05 52 PM" src="https://user-images.githubusercontent.com/351529/87276639-9d82fd00-c495-11ea-8ac9-4a2691e89f0d.png">

This issue may be related to #142 which was closed without much information or resolution. As my issue is more specific I've opened a new issue.

**Comment by PhilRunninger** [comment]
@leighmcculloch, I had to jump through quite a few hoops to recreate this. Could it be that another of your plugins is doing some of what I'm describing below? For example, [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs) keeps the same NERDTree buffer on all tabs.

Here are the steps I took, along with explanations where needed.

1. `vim` - Open vim with no files open.
1. `:NERDTree`
1. `t` - Open file1 in a new tab, and go there.
1. `:NERDTreeMirror` - Open the same NERDTree buffer in the second tab.
1. `q` - Close NERDTree, leaving file1 in a window by itself.
1. `gt` - Go back to the first tab.
1. `o` - Open file2 in the current tab.
1. `:bdelete` - Close the file2 buffer, and the window that's displaying it. NERDTree is now a full-width window.
1. `gt` - Go to the tab where file1 is displayed. As you leave the NERDTree buffer, it remembers its width for when it's displayed again.
1. `:NERDTreeToggle` - Show the NERDTree again, in the second tab now, restoring its width from the previous step.

`:NERDTreeMirror` and `:NERDTreeToggle` seem to be key in my reproduction of the issue. Anything else creates a new NERDTree in the tab, which will be created at the desired width.

I have a solution, which will be out shortly in a pull request that I'd like to you try out for me.

Stay tuned...

**Comment by PhilRunninger** [comment]
Here's another, simpler sequence of commands to reproduce the issue. It isn't related to tabs.

1. `vim` - Open vim with no files open.
1. `:NERDTree`
1. `o` - Open **file1** and put the cursor in it.
1. `:q` - Close **file1**'s window. This leaves NERDTree open by itself.
1. `:b file1` - Switch to the **file1** buffer in the current NERDTree window. As you leave the NERDTree buffer, it remembers its width for the next time it's displayed.
1. `:NERDTreeToggle` - Show the NERDTree again, restoring its width from the previous step.

**Comment by PhilRunninger** [comment]
@leighmcculloch, checkout branch `i1152` or pull request #1153, and see if that fixes your issue.

Thanks!

**Comment by leighmcculloch** [comment]
@PhilRunninger I had planned to return after your earlier comment and share a reproducible without NERDTreeMirror because I'm not using the plugin you mentioned, I'm using vim-airline's tabline feature which definitely doesn't call the mirror function, but you were so fast! I can confirm the fix you have in the PR fixes my issue without me needing to do the resize hack. 

Thank you!!! 🎉
