### ISSUE TITLE
Crashing update: Error: Key not present in Dictionary: Slash(), etc.

### ISSUE THREAD

**Issue by iFork** [preservim/nerdtree#1154]
After last update of this plugin - it is not working.
Errors Vim reports:
```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..77[26]..76[3]..<SNR>48_customOpenDir[1]..<SNR>
48_activateDirNode[7]..134[3]..168[8]..157[6]..156[25]..154[15]..266[5]..NERDTreeGitStatusRefreshListener[5]..NERDTreeGet
GitStatusPrefix:
line    6:
E716: Key not present in Dictionary: Slash()
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..77[26]..76[3]..<SNR>48_customOpenDir[1]..<SNR>
48_activateDirNode[7]..134[3]..168[8]..157[6]..156:
line   25:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..77[26]..76[3]..<SNR>48_customOpenDir[1]..<SNR>
48_activateDirNode[7]..134[3]..168[8]..157:
line    6:
E170: Missing :endwhile
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..77[26]..76[3]..<SNR>48_customOpenDir[1]..<SNR>
48_activateDirNode[7]..134[3]..168:
line    8:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..77[26]..76:
line    3:
E171: Missing :endif
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..77:
line   26:
E171: Missing :endif
```

#### Self-Diagnosis

- [ ] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [ ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [ ] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System: 
- [x] Vim/Neovim version `:echo v:version`:  vim 802
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`:  6.9.3
- [ ] vimrc settings
    - [ ] NERDTree variables
```vim
" nerdtree-git-plugin 
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }
```
- Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [x] Xuyuanp/nerdtree-git-plugin
        - [x] Others (specify): low-ghost/nerdtree-fugitive
- [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Open vim
[2. Open nerdtree, try to open dir - for more errors - as listed above]

**Comment by Xuyuanp** [comment]
Fixed, please see [here](https://github.com/Xuyuanp/nerdtree-git-plugin/issues/141)

**Comment by PhilRunninger** [comment]
Thanks, @Xuyuanp!
