### ISSUE TITLE
highlinghting for symbol links covers leading flags

### ISSUE THREAD

**Issue by Xuyuanp** [preservim/nerdtree#1155]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: mac 
- [x] Vim/Neovim version `:echo v:version`:
   -  NVIM v0.4.3
   - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul  8 2020 04:15:03)
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`:  6.9.3
- [x] vimrc settings
    - [x] NERDTree variables
    ```vim
    let NERDTreeShowBookmarks               = 1
    let NERDTreeIgnore                      =
           \ ['\.idea', '\.iml', '\.pyc', '\~$', '\.swo$', '\.git', '\.hg', '\.svn', '\.bzr', '\.DS_Store', 'tmp', 'gin-bin']
    let NERDTreeShowHidden                  = 1
    let NERDTreeChDirMode                   = 2
    let NERDTreeMouseMode                   = 2
    let g:NERDTreeNodeDelimiter = "\u00a0"

    ```
    - Other NERDTree-dependent Plugins
        - [x] jistr/vim-nerdtree-tabs
        - [x] ryanoasis/vim-devicons
        - [x] tiagofumo/vim-nerdtree-syntax-highlight
        - [x] Xuyuanp/nerdtree-git-plugin
        - [x] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. create a symbol link file

#### Current Result (Include screenshots where appropriate.)

![WechatIMG3](https://user-images.githubusercontent.com/2245664/87754378-54d19800-c837-11ea-814c-ab90888844ab.jpeg)

#### Expected Result

no brackets

#### My Solution

I try to update [syntax/nerdtree.vim#L19](https://github.com/preservim/nerdtree/blob/96e247ba7488af1e71d0facfc68aba37e750298c/syntax/nerdtree.vim#L19)

```vim
syn match NERDTreeLinkFile #[\]].* ->#me=e-3 containedin=NERDTreeFile
```

it looks like ok. (but i don't know why)

![WechatIMG4](https://user-images.githubusercontent.com/2245664/87754515-ab3ed680-c837-11ea-9453-ec6c6e3c4eca.jpeg)

Also, `NERDTreeRO` syntax match is similar with this issue.  you can see the readonly file `c.go`, the gopher icon should be light bule.

**Comment by PhilRunninger** [comment]
I fixed the problem with the brackets. The **NERDTreeFlags** syntax group was not contained in the **NERDTreeLinkFile** group. I'll put out a PR soon for it.

The color of your `c.go` file's icon is controlled by [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight). If it's still not right after this PR, I suggest creating an issue in that project.

The syntax highlighting in NERDTree is a hot mess, in my opinion. Specifically, the `NERDTreeRO` syntax group is supposed to display read-only files in the WarningMsg color, and that isn't happening. I'm going to call that a separate issue, and deal with it another time. As it stands, read-only files are marked with `[RO]`, which is sufficient.
