### ISSUE TITLE
nerdtree not installing

### ISSUE THREAD

**Issue by psomdeb25** [preservim/nerdtree#1158]
My vimrc file is located in ~/vimrc and have entered the following commands in the file but it does not install the plugin on to my system. Is there a bug?

Commands:
```vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin(~/.vim/bundle)
Plugin 'VundleVim/Vundle.vim'

Plugin 'L9'
Plugin 'preservim/nerdtree'
call vundle#end()
```

Edit:
Operating System Version: macOS Mojave 10.14.6
Vim version: 8.0 (2016 Sep 12, compiled Jun 19 2019 19:08:44)
Included patches: 1-503, 505-680, 682-1283, 1365
Compiled by root@apple.com

**Comment by PhilRunninger** [comment]
It looks like you forgot to put quotes around the directory name. It should read:
```vim
call vundle#begin('~/.vim/bundle')
```
I don't remember if it's the case with Vundle or not, but you may have trouble with the tilde. You can do this to get around that issue:

```vim
let $VIMHOME=expand('~')
set rtp+=$VIMHOME/.vim/bundle/Vundle.vim
call vundle#begin($VIMHOME.'/.vim/bundle')
```

While we're on the subject of setting things up, I like to keep all my vim configuration together in one folder. If you move your `~/vimrc` to `~/.vim/vimrc`, then it's all in one place and easier to clone to other machines.

**Comment by psomdeb25** [comment]
Even with the above mentioned changes to the command list and having moved from ~/.vimrc to ~/.vim/vimrc I still do not seem to have the nerdtree installed. The directory tree ~/.vim/bundle does only has the L9 Plugin which I had installed an year back. Am I doing something wrong. Do I have to remove the line 
Line: Plugin 'L9' 

Since it has already been installed on my system.

**Comment by PhilRunninger** [comment]
Reread the Vundle documentation. You need to issue the `:PluginInstall` command to install the plugins. You must have done that with L9, but not yet with NERDTree.

**Comment by PhilRunninger** [comment]
While stepping through your GIF, I saw some things in your `vimrc` that are set up poorly.

1. You are using multiple plugin managers. I see **pathogen**, **Vundle.vim**, and **vim-plug**. You should definitely stick to one. Of those, my favorite is **vim-plug**, and the rest of this comment, I will assume that is the one being used.
1. You have multiple blocks of code like this:
    ```vim
    call plug#begin('~/.vim/plugged') 
    Plug <plugin-name>
    call plug#end()
    ```
    All `Plug` statements should be between a single pair of `plug#begin()` and `plug#end()` statements. Multiple `plug#begin()` calls will cause **vim-plug** to reinitialize, forgetting about plugins that were configured earlier.
1. You specified multiple locations for plugins: `~/.vim/plugged` and `~/.vim/bundle`. You should keep all plugins in one directory.
1. You have something to fix on line 81.

The `Plug` statements in your `vimrc` determine which already-installed plugins are loaded for the current vim session. If you need to install one or more of those listed plugins, use the `:PlugInstall` command inside of vim and then restart vim. **vim-plug** also has commands for updating plugins, cleaning up unused plugins (ones you once installed, but whose `Plug` statement has been removed), etc. Take a second look at the **vim-plug** documentation to learn more about what it can do.

**Comment by psomdeb25** [comment]
Thank you for the valuable insight @PhilRunninger
