### ISSUE TITLE
Errors on NERDTreeFind command: "Key not present in Dictionary: Slash()"

### ISSUE THREAD

**Issue by gvolpe** [preservim/nerdtree#1159]
#### Summary

The bug only appears in both versions `6.9.4` and `6.9.5`. I've tested previous versions `6.8.0`, `6.9.0`, `6.9.2` and `6.9.3`, they all work as expected when running the `NERDTreeFind` command.

It seems related to https://github.com/preservim/nerdtree/issues/1154 but this issue only occurs when running `NERDTreeFind`, other commands seem to work well but I haven't tested all of them to be honest.

#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)

- [x] Operating System: NixOS 20.09 
- [x] Vim/Neovim version `:echo v:version`: Both `0.4.3` and the latest nigthly build `0.5.0-dev`. 
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: Both `6.9.4` and `6.9.5`.
- [ ] vimrc settings
    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [x] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [x] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue

1. Run `NERDTreeFind` in either verion `0.9.4` or `0.9.5` (at least on NixOS).

#### Current Result (Include screenshots where appropriate.)

![error](https://i.imgur.com/KcJekCg.png)

#### Expected Result

It opens the current directory for the file.

#### More information

This is my [NixOS configuration](https://github.com/gvolpe/nix-config/tree/master/nixos/home), in case it helps. The plugins I'm using are listed [here](https://github.com/gvolpe/nix-config/blob/master/nixos/home/programs/neovim/default.nix#L14), [here](https://github.com/gvolpe/nix-config/blob/master/nixos/home/programs/neovim/custom-plugins.nix) and [here](https://github.com/gvolpe/nix-config/blob/master/nixos/home/overlays/vim-plugins.nix).

I'd be keen to provide any more information as requested.

**Comment by PhilRunninger** [comment]
You don't have the latest version of `nerdtree-git-plugin`.

**Comment by gvolpe** [comment]
Thanks for the quick response! You're right, it works now. It should've occurred to me before :smile: 

Overriding the default Nixpkgs to use the latest version of `nerdtree-git-plugin` did trick in case some Nix user comes across the same issue: https://github.com/gvolpe/nix-config/commit/cf8810fc816caf4d27203bea0009c4e6b53d812c
