### ISSUE TITLE
Change CWD when Changing NERDTree Root

### ISSUE THREAD

**Issue by mucholove** [preservim/nerdtree#1160]
#### Change CWD when Changing NERDTree Root

Hi all! I would love to use NERDTree a bit more like a Finder window.

Basically—want to call these 2 functions in 1 command—one after the other:

NERDTreeMapChangeRoot
NERDTreeMapChdir

Would love to help but I don't understand the VIM script.

**Comment by PhilRunninger** [comment]
This is already built into NERDTree. Put this in your `.vimrc`:
```vim
let NERDTreeChDirMode = 2
```
This will change your cwd every time you change the root of NERDTree. See `:h NERDTreeChDirMode` to see what other values are supported.
