### ISSUE TITLE
sort reverse alphabetically?

### ISSUE THREAD

**Issue by pinggit** [preservim/nerdtree#1162]
I don't see a way to sort alphabetically but in reverse order.
for example in jekyll blog list I'd like to see the newest blog post first, even if the older blog just got the latest change.

2020-06-12-post2.md
2020-06-05-post1.md

**Comment by PhilRunninger** [comment]
There are several options related to grouping and sorting, but none of them allow you to specify reverse alphabetical:
```vim
g:NERDTreeNaturalSort 
g:NERDTreeSortOrder
g:NERDTreeCaseInsensitiveSort
g:NERDTreeSortHiddenFirst
```

The way NERDTree's sorting function is written makes this a difficult feature to implement. In fact, while researching the code, I came across a sorting-related function nearly duplicating the actions of another, and I'm not quite sure of its purpose. I'm not saying it's impossible to do this change, but it's not at the top of my priorities right now.

**Comment by PhilRunninger** [comment]
I'm not going to pursue this. It would involve too much refactoring to be worth the effort.

**Comment by cgbahk** [comment]
I can also imagine that it would be more 'ergonomic' for many cases.
