### ISSUE TITLE
Remove silent on event-broadcast for debuging

### ISSUE THREAD

**Issue by Xuyuanp** [preservim/nerdtree#1163]
https://github.com/preservim/nerdtree/blob/4a32dd0be35621dc8d4b73836f58434ff3e73124/lib/nerdtree/creator.vim#L31

https://github.com/preservim/nerdtree/blob/30ad6da98482d8aee36d90c49711a8476b5e240a/lib/nerdtree/nerdtree.vim#L30

I want to do something when `nerdtree` init first time or root changed, so I wrote these code

```vim
autocmd User NERDTreeInit call s:MyHandler()
autocmd User NERDTreeNewRoot call s:MyHandler()
```

But the `silent doautocmd` will also silent the triggered `autocmd`, so the messages in my handler (`echomsg`) are all skipped.  It's really inconvenient for debugging.

I think it's the subscriber's responsibility to decide when to use `silent`. like `autocmd User NERDTreeInit silent! call s:MyHandler()`

**Comment by PhilRunninger** [comment]
I'm OK with this. It looks like it was added about eight years ago for `vim-fugitive` integration. See these commits: https://github.com/preservim/nerdtree/commit/2cb0fc78fb4c7a1db5f51c042a447cc50f09983d and https://github.com/tpope/vim-fugitive/commit/89e771ea963baafd2918019bc8083cfd32f43aa6

@tpope, are you OK with the changes proposed by @Xuyuanp here?

**Comment by tpope** [comment]
The purpose of `silent` is to prevent a `No matching autocommands` message if there are no plugins listening for the event. I don't need it but you still might.

**Comment by tpope** [comment]
You can sidestep this need by declaring your own autocommands (`autocmd User NERDTreeInit exe`) or by wrapping the `doautocmd` in a `exists()` check.

**Comment by Xuyuanp** [comment]
@PhilRunninger Hi, I found that #1164 doesn't work correctly. `exists('#NERDTreeInit')` should be replaced by `exists('#User#NERDTreeInit')`, and so does `NERDTreeNewRoot`

Related https://github.com/Xuyuanp/nerdtree-git-plugin/issues/147
