### ISSUE TITLE
Ignore directory with R (refresh)

### ISSUE THREAD

**Issue by 9mm** [preservim/nerdtree#1169]
#### Description

Hey, I love NerdTree and have used it for years. Recently I am working on a lot of projects with ludicrous, idiotic, asinine, ridiculous amounts of npm packages.... like 100,000 files. This takes ~3-4 seconds for refreshing the tree, which I do very often.

It would be awesome to exclude certain folders, like `node_modules` from the root `R` refresh. If they need to be updated they would have to manually be refreshed with local `r` refresh.

**Comment by PhilRunninger** [comment]
If you never open the `node_modules` folder, the `R` refresh won't touch it, and should finish much quicker.

or

You can tell NERDTree to ignore the `node_modules` directory. Chances are you not interested in that directory while you're editing source anyway, right? Add this to your `vimrc`:
```vim
let NERDTreeIgnore = ['node_modules[[dir]]']
```
If you change your mind and want to look in that folder, press the `f` key to reveal the hidden folders. Then if NERDTree becomes to slow to refresh, create a new one with `:bw` (in the NERDTree window), followed by `:NERDTree`.

**Comment by 9mm** [comment]
Dude, thats awesome! I never noticed that opening it is what adds it to the stack to get refreshed. This is great, thanks!
