### ISSUE TITLE
Cascade nested directories

### ISSUE THREAD

**Issue by eyalch** [preservim/nerdtree#1171]
There are many situations in which a directory has only a single directory, so I think it would be better to cascade them.

Take the following structure for example:
![image](https://user-images.githubusercontent.com/5116133/93604097-99abb380-f9cd-11ea-9a2c-e4d4af4ce1f0.png)

Wouldn't it be better to show `nvim/.config/nvim/` instead of `nvim/` in the first line and just list the nested files under it?

NERDTree has this feature turned on by default (`g:NERDTreeCasadeOpenSingleChildDir`).

Thanks!

**Comment by PhilRunninger** [comment]
The feature you are asking for is already in NERDTree and turned on by default. Make sure these values are set to `1`, especially the first one.
```vim
:echo NERDTreeCascadeSingleChildDir
1
:echo NERDTreeCascadeOpenSingleChildDir
1
```
If that doesn't work, please open a bug issue, and include as much detail as possible.
