### ISSUE TITLE
Can I open nerdtree from directory which current file in?

### ISSUE THREAD

**Issue by xaljer** [preservim/nerdtree#1173]
#### Self-Diagnosis

- [ ] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [ ] I have reviewed the NERDTree documentation. `:h NERDTree`
- [ ] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [ ] I have searched the web for an answer to my question.

**Comment by PhilRunninger** [comment]
If you use the `:NERDTreeFind` command, it will open **NERDTree**, find the current file, and put the cursor on that line.

**Comment by xaljer** [comment]
It works, but what i want. When i work in a very deep directory tree, `NERDTreeFind` sometimes open tree view in the whole workspace, which cause so many indent (spaces) before the file name. But i just want to explore a part files in a big code base.
In addition, `NERDTreeFind` seems need run `NERDTreeToggle` first.
So, I think a command like `NERDTreeVCS` to open from path of current file would be better.

**Comment by PhilRunninger** [comment]
Try `:NERDTree %`. That will open a NERDTree buffer with the root being the path of the file in your active buffer.

`:NERDTreeFind` will use an existing NERDTree window, and expand whatever folders are necessary to find the file in your active buffer. If there is no NERDTree buffer already, it will create one whose root is the current working directory.

I see no evidence for your claim about running `:NERDTreeToggle` first; if you can consistently reproduce that, create a new issue for it.

**Comment by xaljer** [comment]
@PhilRunninger Thanks, `NREDTree %` is just what I want. And there is no bug about need running `NERDTreeToggle` first, just ignore it~
