### ISSUE TITLE
Status bar change when i open a new tab

### ISSUE THREAD

**Issue by arejula27** [preservim/nerdtree#1174]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System:  MacOS
- [x] Vim/Neovim version `:echo v:version`: 
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.9.9
- [x] vimrc settings
[vimrc.txt](https://github.com/preservim/nerdtree/files/5252766/vimrc.txt)

    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [x] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Open a tab

#### Current Result (Include screenshots where appropriate.)
my status bar change or dissapear
![Captura de pantalla 2020-09-20 a las 23 54 04](https://user-images.githubusercontent.com/46299278/93723175-b64a1600-fb9c-11ea-99ec-5262faeae9c6.png)
![Captura de pantalla 2020-09-20 a las 23 54 22](https://user-images.githubusercontent.com/46299278/93723176-b813d980-fb9c-11ea-9d85-db5110792101.png)

#### Expected Result
Keep my status bar

**Comment by PhilRunninger** [comment]
Check out `:h 'laststatus'`. In Vim, default is 1, which hides the status line when there is only one window. In Neovim, the default is 2, which always shows the status line. In your `.vimrc`, you can add the line
```vim
set laststatus=2
```
to always see your status line.

**Comment by arejula27** [comment]
Yes, it works
