### ISSUE TITLE
NERDTree and vim-airline integration problem

### ISSUE THREAD

**Issue by lesar** [preservim/nerdtree#1178]
#### environment

- vim: neovim 0.4.4-1\~ubuntu20.04.1~ppa1  
          :echo v:version --> 800
- NERDTree version: 0.12 installed by `call dein#add('preservim/nerdtree')`  
- vim-airline:  
call dein#add('vim-airline/vim-airline')
call dein#add('vim-airline/vim-airline-themes')
- OS:  Ubuntu 20.04 64bit on rpi4  
- Have you reproduced with a minimal vimrc: no
- What is your airline/NERDTree configuration: 
this is my .config/nvim/init.vim  
```vim
scriptencoding utf-8
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif
" Required:
set runtimepath+=/home/leonardo/.local/share/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/home/leonardo/.local/share/dein')
  call dein#begin('/home/leonardo/.local/share/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/home/leonardo/.local/share/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('Shougo/deoplete.nvim')

  " Add or remove your plugins here like this:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')

  source /home/leonardo/.config/nvim/loaded-plugins.vim

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------

"-------------------Load files-----------------
source ~/.config/nvim/base.vim
source ~/.config/nvim/plugins.vim
source ~/.config/nvim/ui.vim
source ~/.config/nvim/mappings.vim
source ~/.config/nvim/misc.vim

```  
### This is from my ~/.config/nvim/plugins.vim
```vim  

" === NERDTree === "
"
" Show hidden files/directories
let g:NERDTreeShowHidden = 1

" Remove bookmarks and help text from NERDTree
let g:NERDTreeMinimalUI = 1


" Custom icons for expandable/expanded directories
let g:NERDTreeDirArrowExpandable = '⬏'
let g:NERDTreeDirArrowCollapsible = '⬎'

" Hide certain files and directories from NERDTree
let g:NERDTreeIgnore = ['^\.DS_Store$', '^tags$', '\.git$[[dir]]', '\.idea$[[dir]]', '\.sass-cache$']

" Wrap in try/catch to avoid errors on initial install before plugin is available
try

" === Vim airline ==== "
" Enable extensions
let g:airline_extensions= ['branch', 'hunks', 'coc']

" Update section z to just have line number
let g:airline_section_z = airline#section#create(['linenr'])

" Do not draw separators for empty sections (only for the active window) >
let g:airline_skip_empty_sections = 1

" Smartly uniquify buffers names with similar filename, suppressing common parts of paths.
let g:airline#extensions#tabline#formatter = 'unique_tail'

" Custom setup that removes filetype/whitespace from default vim airline bar
let g:airline#extensions#default#layout = [['a', 'b', 'c'], ['x', 'z', 'warning', 'error']]

" Customize vim airline per filetype
" 'nerdtree'  - Hide nerdtree status line
" 'list'      - Only show file type plus current line number out of total
let g:airline_filetype_overrides = {
  \ 'nerdtree': [ get(g:, 'NERDTreeStatusline', ''), '' ],
  \ 'list': [ '%y', '%l/%L'],
  \ }

" Enable powerline fonts
let g:airline_powerline_fonts = 1

" Enable caching of syntax highlighting groups
let g:airline_highlighting_cache = 1

" Define custom airline symbols
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" Don't show git changes to current file in airline
let g:airline#extensions#hunks#enabled=0
" Vim airline theme
let g:airline_theme='onedark'

catch
  echo 'Airline not installed. It should work after running :PlugInstall'
endtry

```  

if you are using terminal:
- terminal: gnome terminal 3.36.2
- $TERM variable: screen-256color
- color configuration (:set t_Co?): Key code unset
if you are using Neovim:
- does it happen in Vim: not try: do not wont to mess vim configuration

#### actual behavior

$ nvim .  
display NERDtree and there is bad chars: E612 E613 E608 E609  ....  
see screen shot.  

#### expected behavior

see beatufull display.
normal utf8 char  

#### screen shot (if possible)
![Schermata del 2020-10-09 12-39-39](https://user-images.githubusercontent.com/6347403/95721009-477b4c80-0c72-11eb-8863-257899e90ea2.png)

best regard,
Leonardo

P.S. I have read and try [integrating-with-powerline-fonts](https://github.com/vim-airline/vim-airline#integrating-with-powerline-fonts)  
but the instruction do not work for me and seems a little outdated do Ubuntu 20.04 system

**Comment by lesar** [comment]
Solved. I found instruction a little hard to understand for my brain.  
I have search to find this:
[Ubuntu](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20Nerd%20Font%20Complete.ttf)
[UbuntuMono](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20Nerd%20Font%20Complete%20Mono.ttf)  
downloaded into ~/.local/share/fonts/  
the folder is not existing on ubuntu you have to create it.  
then do `fc-cache -vf ~/.local/share/fonts`  
this make the char display  
to me is a bit insane ... not the command itself but the path to find it

**Comment by mkschreder** [comment]
@lesar Terminus is a better font than ubuntu mono.
