### ISSUE TITLE
The divider is not aligned correctly.

### ISSUE THREAD

**Issue by hyochan** [preservim/nerdtree#1179]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: Chromeos Version 85.0.4183.133 (Official Build) (64-bit)
- [x] Vim/Neovim version `:echo v:version`: 800
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 
- [x] vimrc settings
    - https://gist.github.com/hyochan/9dbc2e754dd1c8bf561abb317a3a6344

#### Steps to Reproduce the Issue
1. Open up the nerd tree

#### Current Result (Include screenshots where appropriate.)
![Screenshot 2020-10-14 at 3 27 56 AM](https://user-images.githubusercontent.com/27461460/95900868-79ed8c80-0dcd-11eb-8d8b-2516de0ecd5e.png)

As shown in the screenshot, the divider is not straight so it is hard to make correct indentation while coding.

#### Expected Result

I want the vertically straight divider.

**Comment by PhilRunninger** [comment]
@hyochan Can you show all of the NERDTree window?

**Comment by hyochan** [comment]
@PhilRunninger Sure here it is.

![image](https://user-images.githubusercontent.com/27461460/96013712-85e65680-0e80-11eb-8489-e4d278657e8b.png)

**Comment by PhilRunninger** [comment]
This is a font issue, specifically related to the characters for indicating expandable or collapsible directories. Frankly, I'm surprised the terminal program doesn't line up the characters correctly. Does it have any settings to fix that alignment?

You can look at the characters available in your font to find something suitable. Or you can choose a different font that has the correct width for those triangles. As a last resort you can use ASCII characters like so:
```vim
let NERDTreeDirArrowExpandable=">"
let NERDTreeDirArrowCollapsible="v"
```
