### ISSUE TITLE
Error detected while processing function <lambda>

### ISSUE THREAD

**Issue by adisen99** [preservim/nerdtree#1180]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### On quitting vim after making changes to a file using `:wq` I get the following output -

```shell
Error detected while processing function <lambda>15[1]..407[5]..409[2]..<SNR>59_onGitStatusSuccessCB[10]..384[17]..NERDTreeRender[1]..nerdtree#renderView[1]..332[1]..353:
line   16:
E440: undo line missing
Error detected while processing function <lambda>15[1]..407[5]..409:
line    2:
E171: Missing :endif
Error detected while processing function <lambda>15[1]..407:
line    5:
E171: Missing :endif% 
```
#### This error doesn't exist on quitting after using `:w` first and then `:q`

I don't understand where the issue is. I have tried uninstalling and reinstalling **NerdTree** and **NerdTree-Git-Plugin**. Please let me know how to fix this issue. 

#### $MYVIMRC

```vim
" Nerdtree Settings

"let NERDTreeMinimalUI = 1
"let NERDTreeDirArrows = 1
map <leader>n :NERDTreeToggle<CR>
map <leader>f :NERDTreeFind<CR>
" Automatically start nerdtree if no file is opened
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" and automatically start nerdtree on openning up a directory
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | exe 'cd '.argv()[0] | endif
" Close vim if nerdtree is the only instance open
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
```

**Comment by PhilRunninger** [comment]
Looking up in Vim help, `:help E440` shows that this is an internal error that should be reported to the Vim developers.

Let's try to figure out where this error starts. Type `:verbose func {407}` in Vim. This will return the text of the first non-lambda function in your call stack. Where did I get `407`? It's in the error message you shared. `407` is an internal ID of some function, probably defined by one of your plugins. If you see a different number now, use it instead.

Also try `:verbose func {<lambda>15}` or `:verbose func {15}`, but I'm not sure those will work.

What do you get from those commands? Also other settings in your .vimrc may be causing this. Can you provide a minimal `.vimrc` that reproduces this error?
