### ISSUE TITLE
How do I remap aborted key when I modify path

### ISSUE THREAD

**Issue by scottming** [preservim/nerdtree#1181]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

Imagine this scene, I open NERDTree, and select a node, type `m` `m`, and the modified window was opened. But when I enter the new path, I want to use `alt+left` move the cursor back to the parent path, for example: `/home/user/repo/path.txt<cursor>` to `/home/user/repo/<cursor>path.txt`. And It not works, the modified window is closed and gave me a message: `NERDTree: Node Renaming Aborted. `

**Comment by PhilRunninger** [comment]
This falls under the category of command line editing within Vim. There's nothing specific to NERDTree. NERDTree uses Vim's `input()` function to ask for the new filename. Check out `:h cmdline-editing` to learn about remappings you can put in your .vimrc that work on the command line. I'm afraid your options are limited, however, especially the move by word capability you asked about.

**Comment by scottming** [comment]
Yes, I found this: 
```
 <S-Left> or <C-Left>                                    c_<C-Left>
                 cursor one WORD left
                                                         c_<S-Right>
 <S-Right> or <C-Right>                                  c_<C-Right>
                 cursor one WORD right
```

But when we type `:` and enter `/home/user/repo/path.txt<cursor>`, the meta key also not works.

**Comment by PhilRunninger** [comment]
I just remembered reading about this feature. I don't use it much myself, but I tested it out on your issue. It does work, even though it's a bit clunky. 

After pressing `m` - `m`, when Vim asks for the new filename, you can press `<C-F>` to open the `[Command Line]` editor buffer. In there, you can:
1. Use any Vim command to edit the line of text.
1. Press `Enter` to use the line under the cursor. It doesn't have to be the last line in the buffer.
1. Press `<C-C>` to return to the command line with the line of text under the cursor. You can still edit the string before the input is accepted.
1. Enter the `:q` command to close the window and abort the input.

**Comment by scottming** [comment]
Yes, This works on Windows, but not work on my iTerm2 vim. But this problem has nothing to do with Nerdtree, thanks for your idea.
