### ISSUE TITLE
NERDTree: Please wait, caching a large dir ...

### ISSUE THREAD

**Issue by pilot513** [preservim/nerdtree#1182]
#### Environment (for bug reports)
- [x] Operating System:  **CentOS Linux release 7.8.2003** 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64
- [x] Vim/Neovim version : **VIM 7.4.629 **
- [x] NERDTree version :  **6.9.10**
    - [ ] NERDTree variables
          ` let NERDTreeDirArrowExpandable='+'`
           ` let NERDTreeDirArrowCollapsible='~'`
           ` let g:netrw_winsize = 25`
           ` let NERDTreeIgnore = ['\.pyc$', '\.pyo$']`
           ` map <F3> :NERDTreeToggle<CR>`
            `nmap ,t :NERDTreeFind<CR>`
           

        - Other NERDTree-dependent Plugins
        - [X ] jistr/vim-nerdtree-tabs
        - [   ] ryanoasis/vim-devicons
        - [    ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ X ] Xuyuanp/nerdtree-git-plugin
        
![Nerdtree-err](https://user-images.githubusercontent.com/28645933/96910875-c3626980-14a8-11eb-8869-67c1a1c34091.png)

Can you help resolve this problem please

**Comment by PhilRunninger** [comment]
We need to find out that functions are being called here. For all the numbers in the first error message - 204, 205, 188, etc. - type the following command into Vim:
```vim
:verbose func {204}
```
This will tell us if it's NERDTree, some other plugin, or a combination of both that's misbehaving.

**Comment by pilot513** [comment]
`   function 204(dir) dict`
`        Last set from ~/.vim/plugged/nerdtree/lib/nerdtree/creator.vim`
`1      let creator = s:Creator.New()`
`2      call creator.toggleTabTree(a:dir)`
 `  endfunction`
`Press ENTER or type command to continue`

**Comment by pilot513** [comment]
See my .vimrc if need it please

**Comment by pilot513** [comment]
`
   function 205(dir) dict
        Last set from ~/.vim/plugged/nerdtree/lib/nerdtree/creator.vim
1      if g:NERDTree.ExistsForTab()
2          if !g:NERDTree.IsOpen()
3              call self._createTreeWin()
4              if !empty(a:dir) && a:dir !=# b:NERDTree.root.path.str()
5                  call self.createTabTree(a:dir)
6              elseif !&hidden
7                  call b:NERDTree.render()
8              endif
9              call b:NERDTree.ui.restoreScreenState()
10         else
11             call g:NERDTree.Close()
12         endif
13     else
14         call self.createTabTree(a:dir)
15     endif
   endfunction
Press ENTER or type command to continue
`

`
   function 188(name) dict
        Last set from ~/.vim/plugged/nerdtree/lib/nerdtree/creator.vim
1      let l:path = self._pathForString(a:name)
2
3      " Abort if an exception was thrown (i.e., if the bookmark or directory
4      " does not exist).
5      if empty(l:path)
6          return
7      endif
8
9      " Obey the user's preferences for changing the working directory.
10     if g:NERDTreeChDirMode != 0
11         call l:path.changeToDir()
12     endif
13
14     if g:NERDTree.ExistsForTab()
15         call g:NERDTree.Close()
16         call self._removeTreeBufForTab()
17     endif
18
19     call self._createTreeWin()
20     call self._createNERDTree(l:path, 'tab')
21     call b:NERDTree.render()
22     call b:NERDTree.root.putCursorHere(0, 0)
23
24     call self._broadcastInitEvent()
   endfunction
Press ENTER or type command to continue
`
`
   function 191(path, type) dict
        Last set from ~/.vim/plugged/nerdtree/lib/nerdtree/creator.vim
1      let b:NERDTree = g:NERDTree.New(a:path, a:type)
2
3      " TODO: This assignment is kept for compatibility reasons.  Many other
4      " plugins use b:NERDTreeRoot instead of b:NERDTree.root.  Remove this
5      " assignment in the future.
6      let b:NERDTreeRoot = b:NERDTree.root
7
8      call b:NERDTree.root.open()
   endfunction
Press ENTER or type command to continue
`

**Comment by PhilRunninger** [comment]
One more, that I didn't see until now. What is `: verbose func {273}`?

**Comment by pilot513** [comment]
`function 273(event) abort dict`
`        Last set from ~/.vim/plugged/nerdtree-git-plugin/autoload/gitstatus/listener.vim`
`1      call self.callback(a:event)`
`   endfunction`

**Comment by pilot513** [comment]
Yah, I found it!
I'm comment (disabled) plugin:
"Plug 'Xuyuanp/nerdtree-git-plugin'
and ... error is out now. See below ... 
![Nerdtree-solution_01](https://user-images.githubusercontent.com/28645933/97087517-72cb4780-1633-11eb-80f3-f56e903ebab8.jpg)
![Nerdtree-solution_02](https://user-images.githubusercontent.com/28645933/97087518-778ffb80-1633-11eb-8c98-6775c25fd4a8.jpg)


But now what to replace it?

**Comment by PhilRunninger** [comment]
Does this error happen all the time, or only on certain folders? Does it need to be a large directory as indicated by your screenshot? Does it need to be a Git repository? Please be specific about the conditions that will reproduce this issue. I do not see it happening on my setup.

**Comment by pilot513** [comment]
Now i can't reproduce it problem. Because I'm deinstall vim* packages installed from CentOS7 repos (7.4)
and build v.8.2  from source:
`./configure --with-features=huge --enable-multibyte --enable-rubyinterp --enable-perlinterp --enable-luainterp --with-x --enable-gui --enable-python3interp=yes --with-python3-config-dir=$(python3-config --configdir)`
Now, I enable plugin and I haven't error.
