### ISSUE TITLE
Focus and positioning 

### ISSUE THREAD

**Issue by bechampion** [preservim/nerdtree#1183]
Hi guys .
I have two questions:
Is it possible that when you do NERDTreeFind it focus on the file but also scrolls it to the middle of the buffer ? Sometimes it find the file at the very end of the buffer and it’s hard to see .
The other question is , doing open bookmark or NERDTreeFind is it possible to always focus on the file but always showing the full path , sometimes it seems like its autocding into the folder .
Thank you

**Comment by PhilRunninger** [comment]
1. Take a look at `:h NERDTreeAutoCenter` and `:h NERDTreeAutoCenterThreshold`. Also make sure `NERDTreeHighlightCursorline` isn't set to 0. The default value of 1 makes the current line stand out visually.
1. Could you explain your second question a little more? `:NERDTreeFind` and opening a bookmark will create a new NERDTree if the file is not found anywhere in the current NERDTree. Does that help answer your question?

**Comment by bechampion** [comment]
Hi Phil , It does help tons , thanks so much
