### ISSUE TITLE
function nerdtree#ui_glue#invokeKeyMap[1].

### ISSUE THREAD

**Issue by Hipoacusia** [preservim/nerdtree#1184]
Hello, I have two bugs, the first does not show an error but the second does.

I have the configuration so that NERDTree opens the manager once you open vim.

I have version 8 of vim.

the first problem is that when I press the letter e in the folder, it opens the open file in another window. then I press again and, in the open window, reopen the folder in the previous window in which I opened the first file.

it goes jumping from window to window. I don't know if that's normal.

The second error is what I show in the following image;

![imagen](https://user-images.githubusercontent.com/61639683/97093517-215e9080-1612-11eb-8e91-7632bfee6a5c.png)

That happens when I open the file with the letter s

![imagen](https://user-images.githubusercontent.com/61639683/97093439-9a111d00-1611-11eb-8979-aaf51fa428c6.png)

this is my configuration

**Comment by PhilRunninger** [comment]
@Hipoacusia , use `o` instead of `e`, and both of these issues will go away. I don't even know why the `e` command is there.

**Comment by PhilRunninger** [comment]
@Hipoacusia, is it OK to close this issue now?

**Comment by PhilRunninger** [comment]
No response. Closing.

**Comment by Axjohnhason** [comment]
I miss the sample problem  , how to fix that ? emmmmmm ^_^
