### ISSUE TITLE
How to auto open the tree without the empty buffer.

### ISSUE THREAD

**Issue by carlosala** [preservim/nerdtree#1185]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

Good night!
The question is simple: how to auto open nvim with the tree (when no file is specified) and without opening an empty buffer?
When I use the snippet of the readme file in my init.vim, the tree is opened with an empty buffer on his left. Is it possible to open in a "fullscreen mode". What I need to change in the snippet?
Thanks!

Code snippet:
```
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
```

**Comment by PhilRunninger** [comment]
Make sure `NERDTreeHijackNetrw` is set to 1, the default. Don't change anything in your snippet, and then start Neovim with: `nvim .`
