### ISSUE TITLE
function nerdtree#ui_glue#invokeKeyMap[1]

### ISSUE THREAD

**Issue by vegawong** [preservim/nerdtree#1186]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
    the same issue as [https://github.com/preservim/nerdtree/issues/1184#issue-728875809](https://github.com/preservim/nerdtree/issues/1184#issue-728875809)
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System:  macos 10.15.7
- [x] Vim/Neovim version `:echo v:version`: 802
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`:  6.9.10
- [x] vimrc settings
    - [x] NERDTree variables
    ```vim
    " NERDTree
    let g:NERDTreeDirArrowExpandable = ''
    let g:NERDTreeDirArrowCollapsible = ''
    let g:NERDTreeMinimalUI = 1
    " NERDTree窗口关闭标记列和关闭高亮列
    autocmd FileType NERDTree set signcolumn=no | set nocuc
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [x] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. open a file into a buffer, select something via visual mode
2. press key `x` to cut 
3. swich to the nerdtree window, then press key `m` to show the menu

#### Current Result (Include screenshots where appropriate.)
![image](https://user-images.githubusercontent.com/17271745/98336945-cc277380-2042-11eb-8ff1-0b71ce7e0db5.png)

#### Expected Result
![image](https://user-images.githubusercontent.com/17271745/98336986-dc3f5300-2042-11eb-9e87-b43701f3494a.png)

**Comment by PhilRunninger** [comment]
I cannot reproduce this error. It may have something to do with the Chinese characters. It looks like the error happens on the `redraw!` command on [this line](https://github.com/preservim/nerdtree/blob/master/lib/nerdtree/menu_controller.vim#L37). If you look at the help file `:h E315` you'll see that this should be reported to the [Vim project](https://github.com/vim/vim). Make sure it is reproducible, and be very specific about the conditions that cause the error.

**Comment by vegawong** [comment]
Thanks! I will  stay focused for this issue! It's an amazing issue. I found it out long time before, but never find out what‘s wrong about it. Maybe it's a bug for vim.
