### ISSUE TITLE
File operation menu pops up unexpectedly

### ISSUE THREAD

**Issue by akulakov** [preservim/nerdtree#1187]
#### Self-Diagnosis

- [ x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [ x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [ x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x ] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System: mac
- [ ] Vim/Neovim version `:echo v:version`:  802
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 3.1.1
- [ ] vimrc settings
    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. 
press 6j

for x>=6
for x<6, menu does not popup.
#### Current Result (Include screenshots where appropriate.)
nerdtree filesystem menu pops up

#### Expected Result
move down by 6 lines

**Comment by PhilRunninger** [comment]
I've tried multiple numbers, less than and greater than 6, and I can't reproduce this issue. Is there any other information you can provide?

**Comment by akulakov** [comment]
I had a custom function that was adding a mark to the jump list when <n>j or <n>k with n>=6. Thanks for looking into it!
