### ISSUE TITLE
How to change the on/off  button for my NERDtree?

### ISSUE THREAD

**Issue by iliveforfun** [preservim/nerdtree#1188]
at the beginning, i start my nerdtree's  with 'NERDTreeToggle', but it's too long for me to code. so I change it in my .vimrc from 'NERDTreeToggle' to ‘NERD’， but it doesnt matters.

i've tried remove nerdtree's directory and use vim-plug to install it again, but still cant work. after i return to 'NERDTreeToggle', it's ok again.

plz tell me if 'NERDTreeToggle' is the only way to start nerdtree?

my setting is as below:
```
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
```

**Comment by PhilRunninger** [comment]
You need to provide some more detail for me to make sense of the question.

* What are you doing to "change 'NERDTreeToggle' to 'NERD'?"
* There are multiple ways to start NERDTree, all documented in `:h NERDTreeGlobalCommands`.
* I would recommend that you change the `Plug` statement. Make it
```vim
Plug 'preservim/nerdtree'
```
You don't save very much startup time by delaying the loading of NERDTree, and this will ensure **all** of the NERDTree commands will defined and available to start NERDTree.

**Comment by iliveforfun** [comment]
> You need to provide some more detail for me to make sense of the question.
> 
> * What are you doing to "change 'NERDTreeToggle' to 'NERD'?"
> * There are multiple ways to start NERDTree, all documented in `:h NERDTreeGlobalCommands`.
> * I would recommend that you change the `Plug` statement. Make it
> 
> ```viml
> Plug 'preservim/nerdtree'
> ```
> 
> You don't save very much startup time by delaying the loading of NERDTree, and this will ensure **all** of the NERDTree commands will be defined and available to start NERDTree.

i using `nmap` to solve this problem xD.
- as for your first question, it means i wanna change my bindings so that i can use NERD to toggle my NERDTree. At the first, i config it like
```
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
```
so that I need to press `NERDTreeToggle` to open it, but when i change to
```
Plug 'scrooloose/nerdtree', { 'on':  'NERDOn' }
```
and it wont matter, and i dont know why....

whatever, i've solve it. thanks for ur kindness

**Comment by PhilRunninger** [comment]
You are misinterpreting the purpose of the dictionary `{'on':'NERDTreeToggle'}` in the `Plug` statement. When specifying that dictionary, `vim-plug` does not install NERDTree when Vim starts, but waits until you run the command `NERDTreeToggle`. `vim-plug` will then intercept it, and install NERDTree at that time. It does this to reduce the startup time of Vim; some plugins take a long time to install, but NERDTree isn't usually one of them.

Using `nmap` or `nnoremap` is the correct solution for defining a shortcut that calls a long command name.
