### ISSUE TITLE
How to set l and h keys to open/close directory or file?

### ISSUE THREAD

**Issue by coder3101** [preservim/nerdtree#1189]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

I come from coc-explorer and it had a default key binding which opened or closed directory or files with the help of `l` and `h` keys respectively. I would like to know how I can set that same behaviour in Nerdtree on my neovim. I read the docs and found that there is a way to set custom keymaps by `NERDTreeAddKeyMap` but it came with some error when launching nvim (Unknown function NERDTreeAddKeyMap). Maybe I did it wrong, could you please help me how to set up such keybindings in nerdtree.

**Comment by PhilRunninger** [comment]
Unfortunately, that is not possible with **NERDTree**. The `o` key does both opening and closing of directories. The closest you can come to **coc-explorer** is to use `o` and `x` in place of `l` and `h`, but the `x` key's behavior is not quite the same as **coc-explorer**'s `l` key.

To change the keys associated with a NERDTree action, in particular the suggestion above, you would do this:
```vim
let NERDTreeMapActivateNode = 'l'
let NERDTreeMapCloseDir = 'h'
```
The `NERDTreeAddKeyMap` function is used to extend **NERDTree** with functions that you write to add new functionality to the plugin. If you're feeling ambitious, you could implement the desired `h` and `l` behavior you're seeking by creating a new NERDTree plugin.

**Comment by coder3101** [comment]
I wish clicking `h` on a directory node closed it, but I think I can get used to toggling behaviour of  `l`.

Thanks for your help!
