### ISSUE TITLE
Can I open projects like in vscode?

### ISSUE THREAD

**Issue by vatosarmat** [preservim/nerdtree#1191]
- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question
Vscode command `code ~/Projects/foo` opens project i.e. sets working directory to `foo` and file explorer root to `foo`. Can I achieve similar effect with Nvim and NERDtree? 

I config `let g:NERDTreeChDirMode=3` and run nvim as `nvim ~/Projects/foo`. But this doesn't work as desired:

1. nvim initially opens with `~/Projects/foo` nerdtree in its only window
2. I go to file and its content replaces nerdtree
3. then I toggle nerdtree and it has its root in directory from which I've launched nvim instead of `~/Projects/foo`

**Comment by PhilRunninger** [comment]
Yes, you can do this. As documented in the README and the Wiki, you can put the following text in your `vimrc`:
```vim
" Start NERDTree when Vim starts with a directory argument.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
    \ execute 'NERDTree' argv()[0] | wincmd p | enew | execute 'cd '.argv()[0] | endif
```

Once you do that, `vim ~/Projects/foo` will open NERDTree to the `foo` folder, and set your current working directory to that folder as well.

If you open vim without a folder, you will see only the initial `[No Name]` buffer; no NERDTree.
