### ISSUE TITLE
I am trying to edit the NERDTreeCWD and i am not able to

### ISSUE THREAD

**Issue by hrqmonteiro** [preservim/nerdtree#1194]
#### Self-Diagnosis

- [X] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [X] I have reviewed the NERDTree documentation. `:h NERDTree`
- [X] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [X] I have searched the web for an answer to my question.

#### State Your Question

Hi, i am aware that in order for me to change the color of this section here, the text of the current directory:

![2020-12-19_16-59](https://user-images.githubusercontent.com/17055027/102698387-a681b280-421b-11eb-9edb-922102c8e0f8.png)

I have to highlight as the following: `hi NERDTreeCWD ctermfg=4`, for example.

So, i am trying to test my skills in editing Vim Plugins, and i wanted to change what is like on these function, so i found, in the file `/plugin/NERD_tree.vim` the following section:

```
function! NERDTreeCWD()

    if empty(getcwd())
        call nerdtree#echoWarning('current directory does not exist')
        return
    endif

    try
        let l:cwdPath = g:NERDTreePath.New(getcwd())
    catch /^NERDTree.InvalidArgumentsError/
        call nerdtree#echoWarning('current directory does not exist')
        return
    endtry

    call NERDTreeFocus()

    if b:NERDTree.root.path.equals(l:cwdPath)
        return
    endif

    let l:newRoot = g:NERDTreeFileNode.New(l:cwdPath, b:NERDTree)
    call b:NERDTree.changeRoot(l:newRoot)
    normal! ^
endfunction
```

So, for matters of testing, i changed it simply to:

´´´
function! NERDTreeCWD()
  return 'Test'
endfunction
´´´

So if i do, let's say, type `:echo NERDTreeCWD()` in the vim cmd line, it indeed returns `Test`

But my bar still looks like this: 

![2020-12-19_16-59](https://user-images.githubusercontent.com/17055027/102698446-0b3d0d00-421c-11eb-9658-62adda4ee95c.png)

It still show me the directory. So how could i properly change this? What am i missing? I looked in the other files and couldn't find something that clarifies me.

**Comment by PhilRunninger** [comment]
The function `NERDTreeCWD()` is called by the command `:NERDTreeCWD` and is mapped to the `CD` key combination inside of NERDtree. It has nothing to do with highlighting or changing the line of text. It's purpose is to change the root of the NERDTree to whatever the current working directory of Vim is. For example, if you did this sequence of commands:
```
~ $ vim
:pwd
/home/hrq
:NERDTree .config/nvim
```
You would see at the NERDTree shown in your pictures. Then `:call NERDTreeCWD()` would change the root of NERDTree to be `/home/hrq` and cause it to be refreshed.

You are right about the `highlight` statement, but `NERDTreeCWD` there refers to the syntax group, which is found in the `syntax/nerdtree.vim` file.

What are you trying to accomplish with this experiment? If you're trying to learn Vim script, NERDTree is not the place to start. It uses some advanced techniques that are not really native to a scripting language, specifically prototype-based objects. I suggest [Learn Vimscript the Hard Way](https://learnvimscriptthehardway.stevelosh.com/) as a good starting point.

**Comment by hrqmonteiro** [comment]
> The function `NERDTreeCWD()` is called by the command `:NERDTreeCWD` and is mapped to the `CD` key combination inside of NERDtree. It has nothing to do with highlighting or changing the line of text. It's purpose is to change the root of the NERDTree to whatever the current working directory of Vim is. For example, if you did this sequence of commands:
> 
> ```
> ~ $ vim
> :pwd
> /home/hrq
> :NERDTree .config/nvim
> ```
> 
> You would see the NERDTree shown in your pictures. Then `:call NERDTreeCWD()` would change the root of NERDTree to be `/home/hrq` and cause it to be refreshed.
> 
> You are right about the `highlight` statement, but `NERDTreeCWD` there refers to the syntax group, which is found in the `syntax/nerdtree.vim` file.
> 
> What are you trying to accomplish with this experiment? If you're trying to learn Vim script, NERDTree is not the place to start. It uses some advanced techniques that are not really native to a scripting language, specifically prototype-based objects. I suggest [Learn Vimscript the Hard Way](https://learnvimscriptthehardway.stevelosh.com/) as a good starting point.

Well i see, i got this wrong, then, my fault.

I am not exactly trying to learn vimscript per se, i was able to make some functions of my own already. I was just trying to edit this part, i mean edit what is shown above the folders.

How could i change it from showing the current directory to something else? Which file should i look at to edit this part?

**Comment by PhilRunninger** [comment]
The value for that line is set here: https://github.com/preservim/nerdtree/blob/master/lib/nerdtree/ui.vim#L424

But, be warned. Changing that line of text will break NERDTree, specifically this function - https://github.com/preservim/nerdtree/blob/master/lib/nerdtree/ui.vim#L257-L265 - and every function that relies on it.

**Comment by hrqmonteiro** [comment]
I see.

But what if i let this lines untouched. Like, they remain calling out these functions

```
    " draw the header line
    let header = self.nerdtree.root.path.str({'format': 'UI', 'truncateTo': winwidth(0)})
    call setline(line('.')+1, header)
    call cursor(line('.')+1, col('.'))
```

But the functions called are edited to show something else then the name of the current directory? Couldn't that be done, let's say?

**Comment by PhilRunninger** [comment]
Why do you want to replace this important piece of information? What would you put there instead?

When you try opening a file or folder, NERDTree starts where your cursor is, and travels upward to build a path. It knows to stop when it gets to the CWD line. If that line is incorrectly formatted, no path is generated, and you will never be able to open a file or expand a folder.

You can change that line of text, but there is a limitation. If you look closely at the `s:UI.getRootLineNum()` function, you'll see that it's looking for a line that starts with either of these two string: `/` or `</`. Putting anything else at the beginning of the line will break NERDTree.

**Comment by hrqmonteiro** [comment]
Well i see.

What i'm trying to do actually is kinda integrate it on my statusline plugin i'm writing, so it would look all uniformly.

How about instead i could put a text below the CWD line? That would work for me. Could i to that? Just a line of text.

**Comment by hrqmonteiro** [comment]
> Why do you want to replace this important piece of information? What would you put there instead?
> 
> When you try opening a file or folder, NERDTree starts where your cursor is, and travels upward to build a path. It knows to stop when it gets to the CWD line. If that line is incorrectly formatted, no path is generated, and you will never be able to open a file or expand a folder.
> 
> You can change that line of text, but there is a limitation. If you look closely at the `s:UI.getRootLineNum()` function, you'll see that it's looking for a line that starts with either of these two string: `/` or `</`. Putting anything else at the beginning of the line will break NERDTree.

Well i see.

What i'm trying to do actually is kinda integrate it on my statusline plugin i'm writing, so it would look all uniformly.

How about instead i could put a text below the CWD line? That would work for me. Could i to that? Just a line of text.

**Comment by PhilRunninger** [comment]
No. That would be treated as a file name.

**Comment by hrqmonteiro** [comment]
I see. Well thanks for trying to help me anyway, i appreciate!
