### ISSUE TITLE
Special

### ISSUE THREAD

**Issue by nehuenlabs** [preservim/nerdtree#1195]
I applied the following configuration, but on Windows 10 vim shows incorrect characters:

let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

Screens shows "â–¸" ...

Am I missing additonal configurations?

Thanks

**Comment by PhilRunninger** [comment]
This is a font issue. Windows has always had notoriously limited fonts, which is the main reason NERDTree has different defaults for the directory arrows based on the OS. Things are better now, with better console programs and available fonts. Try specifying a different font, and see if there is one that displays the arrows correctly. Of the ones I tried, **Lucida Console** and **Courier New** didn't display the arrows properly, but **Consolas** works. There are other fonts available now that work too.

If you're using Gvim, and not the text-based version, you'll need to specify the font with the `'guifont'` setting in your vimrc, like this, for example:

```vim
set guifont=Cascadia\ Code\ PL:h12
```

**Comment by PhilRunninger** [comment]
Fonts for the console application should be changed in the Defaults menu so they don't revert the next time you start a shell.

![image](https://user-images.githubusercontent.com/5598066/102721746-c9b76b00-42ca-11eb-8535-f5ced18a1266.png)
