### ISSUE TITLE
Automatically refresh nerdtree if new file or folder added.

### ISSUE THREAD

**Issue by WIttyJudge** [preservim/nerdtree#1197]
Hi, I have a questing about settings of nerdtree plugin.
Is it available to automatically refresh plugin if new file of folder added?
I know I can press ``R`` to refresh nerdtree, but automating it would be great.

Thank you in advance!

**Comment by PhilRunninger** [comment]
No, that doesn't exist within NERDTree. I have seen people set up auto commands to refresh NERDTree when its window becomes active, but that refresh comes with a significant performance penalty on large trees.
```vim
augroup refreshNERDTree
    autocmd!
    autocmd BufEnter NERD_tree_* NERDTreeRefreshRoot
augroup END
```

I know of no way in Vim script to watch the filesystem for changes and trigger a refresh, nor would I want to spend any time on it. Vim script is or should be on its way out, and [coc-explorer](https://github.com/weirongxu/coc-explorer) is already a quite capable file explorer that, I think, does the kind of live updating you're looking for.

**Comment by WIttyJudge** [comment]
@PhilRunninger, thank you for you answer.
