### ISSUE TITLE
Error while using NERDTreeFind

### ISSUE THREAD

**Issue by ApoloDesolado** [preservim/nerdtree#1202]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: Linux kali 5.8.0-kali1-amd64 #1 SMP Debian 5.8.7-1kali1 (2020-09-14) x86_64 GNU/Linux
- [ ] Vim/Neovim version `:echo v:version`: vim 8.02
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.9
- [ ] vimrc settings:

```
colorscheme gruvbox
set bg=dark
filetype indent plugin on

" Configure the indent lines:
let g:indentLine_color_term = 99
let g:indentLine_char = '┊'
let g:indentLine_enabled = 1

" https://github.com/Yggdroot/indentLine#leading-spaces

" Manage plugins with pathogen 
execute pathogen#infect()
let g:python_highlight_all = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'jsformatter'
" let g:airline_theme='powerlineish'
let g:airline_powerline_fonts = 1 " Triangle in the powerline
    " To install packages, you need to:
    " cd ~/.vim/bundle && /
    " git clone https://github.com/tpope/vim-sensible.git


" configure expanding of tabs for various file types
au BufRead,BufNewFile *.py set expandtab
au BufRead,BufNewFile *.c set noexpandtab
au BufRead,BufNewFile *.h set noexpandtab
au BufRead,BufNewFile Makefile* set noexpandtab

" --------------------------------------------------------------------------
" configure editor with tabs and nice stuff...
" ----------------------------------------------------------------------
set expandtab           " enter spaces when tab is pressed
set textwidth=120       " break lines when line length increases
set tabstop=4           " use 4 spaces to represent tab
set softtabstop=4
set shiftwidth=4        " number of spaces to use for auto indent
set autoindent          " copy indent from current line when starting a new line
set smartindent
set smarttab
set expandtab
set number
set foldmethod=marker
" make backspaces more powerfull
set backspace=indent,eol,start

set ruler                           " show line and column number
syntax on               " syntax highlighting
set showcmd             " show (partial) command in status line

map <C-t><up> :tabr<cr>

map <C-t><down> :tabl<cr>

map <C-t><left> :tabp<cr>

map <C-t><right> :tabn<cr>
```

- [ ] NERDTree variables
```vim
```
- Other NERDTree-dependent Plugins
    - [ ] jistr/vim-nerdtree-tabs
    - [ ] ryanoasis/vim-devicons
    - [ ] tiagofumo/vim-nerdtree-syntax-highlight
    - [ ] Xuyuanp/nerdtree-git-plugin
    - [ ] Others (specify): 
- [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1.  NERDTree
2. NERDTree Find <filename>

#### Current Result (Include screenshots where appropriate.)
![Screenshot from 2021-01-06 17-18-30](https://user-images.githubusercontent.com/73731349/103832819-eaaaea80-5044-11eb-9960-114c7f107d11.png)

#### Expected Result
.......

**Comment by PhilRunninger** [comment]
I can't reproduce this issue. Can you provide more details? Do you have open files? Is there a new buffer (never saved to disk) involved? Which window is active when the error occurs? The more details you can provide, the better I can help you.

**Comment by ApoloDesolado** [comment]
Sorry, I didn't see your comment, and NerdTree have been working pretty well lately. Unfortunately I don't remember what I did to fix the issue :(
