### ISSUE TITLE
Custom plugin working on Ubuntu but not on MacOS

### ISSUE THREAD

**Issue by hwijeen** [preservim/nerdtree#1208]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

I have put the following script to `~/vim/plugged/nerdtree/nerdtree_plugin` in order to copy path from nerdtree.
```
call NERDTreeAddKeyMap({
        \ 'key': 'yy',
        \ 'callback': 'NERDTreeYankCurrentNode',
        \ 'quickhelpText': 'put full path of current node into the default register' })

function! NERDTreeYankCurrentNode()
    let n = g:NERDTreeFileNode.GetSelected()
    if n != {}
        call setreg('"', n.path.str())
    endif
endfunction
```

It works perfectly as expected on Ubuntu, but it does not work on my Macbook.
I have put the same script in the sample location, but `yy` does not yank anything to my clipboard on my Macbook.
I use Nerdtree a lot, any this is a pain in the ass for me.. could you help me with this?

**Comment by PhilRunninger** [comment]
Yeah, the clipboard register is a pain. I don't know what works on Ubuntu, but  you could try the `*` or `+` register. That's what NERDTree uses in its implementation of this. You can access that from the NERDTree menu: `m`, `p`.
