### ISSUE TITLE
Close NERDTree on all open tabs?

### ISSUE THREAD

**Issue by browser-bug** [preservim/nerdtree#1222]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question
Hi, I'm trying to find a way to auto close every NERDTree istances on the current vim session before closing it. I've looked around and I didn't found anything relevant to the topic. Something like `NERDTreeTabsClose` which came from https://github.com/jistr/vim-nerdtree-tabs. Unfortunately it appears to be a dead NERDTree plugin so I'm looking for a fresh way to achieve that. I don't actually know if this is achievable with NERDTree commands only so I'm asking here if someone have a little hack for it. Thanks in advance.

**Comment by PhilRunninger** [comment]
This command will do it for you. Work it into the suggested autocmd in the README.
```vim
:tabdo NERDTreeClose
```
