### ISSUE TITLE
mouse click to open file disappears nerdtree

### ISSUE THREAD

**Issue by laoshaw** [preservim/nerdtree#1224]
#### Environment (for bug reports)
- [ ] Operating System:  Ubuntu 20.04
- [ ] Vim/Neovim version `:echo v:version`:  vim 2:8.1.2269-1ubuntu5
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.10.6
- [ ] vimrc settings
    - [ ] NERDTree variables
    ```vim
    let NERDTreeMinimalUI = 1
    let NERDTreeDirArrows = 1
    let g:NERDTreeWinSize = 30
    let g:NERDTreeDirArrowExpandable = '▸'
    let g:NERDTreeDirArrowCollapsible = '▾'
    "let g:NERDTreeDirArrowExpandable = ''
    "let g:NERDTreeDirArrowCollapsible = ''
    let g:NERDTreeGlyphReadOnly = 'RO'
    let g:NERDTreeNodeDelimiter = "\u0009"
    let g:NERDTreeChDirMode=2
    let g:NERDTreeMouseMode=3 " single click to open all
    let g:NERDTreeIgnore = ['\.pyc$','\~$','\.db$', '\.sqlite$', '__pycache__']
    nnoremap <Leader>f :NERDTreeToggle<Enter>
    ```

    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [X] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify):  nerdcommenter, nerdtree-execute,
    - [ ] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. use mouse to click a filename on nerdtree, the file opens, but nerdtree itself disappears
2. I do have ap/vim-buftabline to do tabs in multiple file opens, it used to work well until yesterday after I did a PlugUpdate for all my plugins
#### Expected Result

The nerdtree shall stay when mouse clicks any file on it

**Comment by astier** [comment]
This happens to me too if `NERDTreeMouseMode` is set to 3. If its set to 2 NERDTree doesn't get closed. Reproducable with the following minimal vimrc:

```vim
set runtimepath^=~/.local/share/nvim/plugins/nerdtree
let g:NERDTreeMouseMode = 3
set mouse=a
```
