### ISSUE TITLE
NERDTree Mirror and error window

### ISSUE THREAD

**Issue by dominiquefournier** [preservim/nerdtree#1226]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

I try to use the quickfix-window (with syntastic). As I use tabs, I define the configuration : 
```
" Display NERDtree on each created tab
autocmd BufWinEnter * silent NERDTreeMirror
```
Each time the quickfix window is created, there is a list of errors displayed (I remove the "silent" to see the error) : 
```
NERDTree: No trees to mirror
Erreur détectée en traitant function 194[2]..195[4]..205 :
ligne    6 :
E788: L'édition d'un autre tampon n'est plus permise
Erreur détectée en traitant function 194[2]..195 :
ligne    4 :
E170: :endfor manquant
Erreur détectée en traitant function SyntasticErrors[1]..333 :
ligne    6 :
E171: :endif manquant
```
How Is possible to not mirror the Tree in the Quickfix Window but in all the other ones ?
Thanks

**Comment by PhilRunninger** [comment]
You could try the other suggestion in the README. Instead of trying to mirror on every window change, it will do it only when you ask for a new NERDTree.
```vim
" Mirror the NERDTree before showing it. This makes it the same on all tabs.
nnoremap <C-n> :silent NERDTreeMirror<CR>:NERDTreeFocus<CR>
```

**Comment by dominiquefournier** [comment]
Thanks for the proposition. I solve the problem with : 
`nnoremap <C-t> :tabnew<CR>:silent NERDTreeMirror<CR>:wincmd p<CR>`

Well done !
