### ISSUE TITLE
NERDTree menu draw problem

### ISSUE THREAD

**Issue by timfeirg** [preservim/nerdtree#1227]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System: Mac OS 11.2.1 (20D74)
- [ ] Vim/Neovim version `:echo v:version`: NVIM v0.5.0-dev+nightly-189-gc64cce906
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`: commit a1fa4a33bf16b6661e502080fc97788bb98afd35 (HEAD -> master, tag: 6.10.7, origin/master, origin/HEAD)
- [x] I've verified the issue occurs with only NERDTree installed.
- [ ] vimrc settings

    ```vim
    call plug#begin('~/.nvim/plugged')
    Plug 'scrooloose/nerdtree'
    call plug#end()
    ```

#### Steps to Reproduce the Issue
1. open up any text file with nerdtree loaded
2. `:NERDTreeToggle` to launch nerdtree
3. `m` to launch the nerdtree menu
4. the menu pane would occur, but will be complete blank

#### Current Result (Include screenshots where appropriate.)

![image](https://user-images.githubusercontent.com/4319104/108679615-c5f0d080-7527-11eb-9aec-e30c762d4679.png)

#### Expected Result

sometimes the menu will flicker if I press some random keys like j or k. I managed to get a screenshot of my menu displaying:

![image](https://user-images.githubusercontent.com/4319104/108680123-71018a00-7528-11eb-8765-f8c324567b26.png)

**Comment by PhilRunninger** [comment]
If its title means what I think it does, your nightly release of Neovim is quite old. The newest one is `NVIM v0.5.0-dev+1102-g595f6e4d6`. Try installing that one, and see if NERDTree behaves correctly.

**Comment by timfeirg** [comment]
upgraded neovim and it's fixed:

```
vi --version
NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210223-55563-la85nm/build/config -I/tmp/neovim-20210223-55563-la85nm/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210223-55563-la85nm/build/src/nvim/auto -I/tmp/neovim-20210223-55563-la85nm/build/include
```
