### ISSUE TITLE
Is it possible to disassociate the CursorLine highlight group from Nerdtree?

### ISSUE THREAD

**Issue by hrqmonteiro** [preservim/nerdtree#1228]
What i mean is, the color of the background of the selected folder/file in NERDTree is the same as set by the highlight ` hi CursorLine`

![2021-02-24_01-00](https://user-images.githubusercontent.com/17055027/108945680-cc706c80-763b-11eb-87e1-95af4b94ddcd.png)

It is possible for me to disassociate this? To set the bg color for the selected item in Nedtree to be different from the CursorLine color?

**Comment by PhilRunninger** [comment]
In Vim, I don't think it can be done. Any change to the `CursorLine` highlight group changes it in all windows. I could be mistaken, but that's what I discovered when I tried it. I welcome being proved wrong on this, if anyone knows better.

In Neovim, however, it is possible using the `winhighlight` setting and an autocmd. I based the solution on what I found in `:help hl-StatusLineTerm` and `:help 'winhighlight'`.  Put this in your `init.vim` and you should be all set.

```vim
autocmd ColorScheme * highlight NERDTreeCursorLine ctermbg=208   " Change as needed.
autocmd User NERDTreeInit
       \ if &filetype=='nerdtree' |
       \     setlocal winhighlight=CursorLine:NERDTreeCursorLine |
       \ else |
       \     setlocal winhighlight= |
       \ endif
```

**Explanation**: If you have defined a `User NERDTreeInit` autocmd, then NERDTree will call it after creating its window. This is an undocumented feature, intended for NERDTree plugin authors, but it works very well in this situation.

**Comment by hrqmonteiro** [comment]
Exactly what i needed! Thanks!

**Comment by PhilRunninger** [comment]
The autocmd can be made simpler. The `if` statement was leftover from the Neovim help page, which used different events. Given that we're using the `NERDTreeInit` event, we'll always be in the NERDTree window when it runs. You can simplify the code like so:

```vim
autocmd ColorScheme * highlight CursorLineNERDTree ctermbg=208
autocmd User NERDTreeInit setlocal winhighlight=CursorLine:CursorLineNERDTree
```

**Comment by hrqmonteiro** [comment]
> The autocmd can be made simpler. The `if` statement was leftover from the Neovim help page, which used different events. Given that we're using the `NERDTreeInit` event, we'll always be in the NERDTree window when it runs. You can simplify the code like so:
> 
> ```viml
> autocmd ColorScheme * highlight CursorLineNERDTree ctermbg=208
> autocmd User NERDTreeInit setlocal winhighlight=CursorLine:CursorLineNERDTree
> ```

I know is not related to this plugin, but you sure know your vimscript: any way i can set this to [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua) too?

I tried:

```
autocmd ColorScheme * highlight CursorLineNvimTree guibg=#88C0D0 guifg=#2E3440 gui=none
autocmd User NvimTree setlocal winhighlight=CursorLine:CursorLineNvimTree
```

But no success. If i open it and type manually: ``setlocal winhighlight=CursorLine:CursorLineNvimTree` it does work, but not on the autocmd.

**Comment by PhilRunninger** [comment]
`NERDTreeInit` (and `NERDTreeNewRoot`) are the names of a potentially-defined `autocmd`. If you have one or both in your `.vimrc`, **NERDTree** will call them at certain times in its processing, using the commands:
```vim
doautocmd User NERDTreeInit
" and
doautocmd User NERDTreeNewRoot
```
Plugins like [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) use these autocmds to respond to events happening in **NERDTree** to keep their information up to date as the tree changes. You are using it, as I recommended, to customize the cursor line in the **NERDTree** window.

**nvim-tree** doesn't have this functionality. In other words, it isn't firing events that can be handled externally, like **NERDTree** is doing.

You can try responding to other events, ones that are built into **Neovim**, and accomplish the same thing. This command can replace your second `autocmd`:
```vim
autocmd BufNew NERD_tree_* setlocal winhighlight=CursorLine:CursorLineNERDTree
```
Replace the buffer name pattern `NERD_tree_*` with one that matches the buffer containing **nvim-tree**, and you should get what you're after. Use the command `:ls!` to list all the buffer names.

**Comment by hrqmonteiro** [comment]
> `NERDTreeInit` (and `NERDTreeNewRoot`) are the names of a potentially-defined `autocmd`. If you have one or both in your `.vimrc`, **NERDTree** will call them at certain times in its processing, using the commands:
> 
> ```viml
> doautocmd User NERDTreeInit
> " and
> doautocmd User NERDTreeNewRoot
> ```
> 
> Plugins like [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) use these autocmds to respond to events happening in **NERDTree** to keep their information up to date as the tree changes. You are using it, as I recommended, to customize the cursor line in the **NERDTree** window.
> 
> **nvim-tree** doesn't have this functionality. In other words, it isn't firing events that can be handled externally, like **NERDTree** is doing.
> 
> You can try responding to other events, ones that are built into **Neovim**, and accomplish the same thing. This command can replace your second `autocmd`:
> 
> ```viml
> autocmd BufNew NERD_tree_* setlocal winhighlight=CursorLine:CursorLineNERDTree
> ```
> 
> Replace the buffer name pattern `NERD_tree_*` with one that matches the buffer containing **nvim-tree**, and you should get what you're after. Use the command `:ls!` to list all the buffer names.

Wow, i really didn't know any of that. Thanks for the clarification.

But unfortunately it doesn't work, it still only works if i manually type the `setlocal winhighlight=CursorLine:CursorLineNERDTree` on the NvimTree buffer. But it was a nice effort.
