### ISSUE TITLE
Variable name conflict

### ISSUE THREAD

**Issue by TornaxO7** [preservim/nerdtree#1229]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [ ] Operating System: Arch Linux
- [ ] Vim/Neovim version `:echo v:version`: 800
- [ ] NERDTree version, found on 1st line in NERDTree quickhelp `?`:
```
" NERDTree (6.10.7) quickhelp~
```
- [ ] vimrc settings
    - [ ] NERDTree variables
```vim
let g:NERDTreeNaturalSort=0
let g:NERDTreeSortHiddenFirst=0
let g:NERDTreeChDirMode=1
```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [x ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Put this (minimal vimrc) into your `vimrc`:
```vim
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'ryanoasis/vim-devicons'
call plug#end()
```
2. Open any `.tex` file
3. Open NERDTree with `:NERDTreeToggle`

#### Current Result (Include screenshots where appropriate.)
I'm getting this error (with vim-devicons):
![image](https://user-images.githubusercontent.com/50843046/109493068-3b125780-7a8c-11eb-981d-fb002f17aa96.png)

Here's a little live-demonstration:
![GIF](https://user-images.githubusercontent.com/50843046/109494410-28008700-7a8e-11eb-8432-973d452028af.gif)

#### Expected Result
No error should appear.

**Comment by TornaxO7** [comment]
I'm not sure if I should create the issue here or in vim-devicons.

**Comment by PhilRunninger** [comment]
I don't think the problem is with `vim-devicons`. I don't see any reference to `Callback` in its code. If you're curious, you can find where the function is with this command:
```vim
:verbose func Callback
```

There are a couple of local variables in NERDTree named `Callback` which are referred to in your error messages. I'll put out a fix shortly.

**Comment by TornaxO7** [comment]
Thank you! It's working now :)
