### ISSUE TITLE
File symbols failing to displaying on MacOS

### ISSUE THREAD

**Issue by CATboardBETA** [preservim/nerdtree#1231]
On MacOS Neovim, the  file-type symbols do not display. I am using UTF-8 with a fully UTF-8-supported font. 

Screenshot:
<img width="178" alt="Screen Shot 2021-03-03 at 7 00 41 PM" src="https://user-images.githubusercontent.com/66703887/109889147-cf2e1b80-7c52-11eb-987f-5693e6826fac.png">

On Ubuntu, these display as missing characters as well.

EDIT: One of the characters is U+E60C, which is a Unicode Private-use codepoint. Do I need extra settings in my

**Comment by PhilRunninger** [comment]
NERDTree doesn't put anything there, but provides a space for other plugins to insert such flags. U+E60C is a javascript glyph. Do you have any other plugins you're using? `vim-devicons`, perhaps?

**Comment by CATboardBETA** [comment]
@PhilRunninger I was using `vim-devicons`. When I created this, I had forgotten that those were not inserted by NERDTree.
