### ISSUE TITLE
NerdTREE causing the cursor to disappear when used with Solarized Colors and GVim

### ISSUE THREAD

**Issue by LordRishav** [preservim/nerdtree#1232]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: GNU/Linux (KDE neon
- [x] Vim/Neovim version `:echo v:version`: 801
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.9.10
- [ ] vimrc settings
    - [ ] NERDTree variables
    ```vim
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [ ] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Install Solarized Colorscheme
2. Open GVim maximized
3. Start NerdTREE with :nerdtreetoggle
4. Exit NerdTree and try to move cursor on the editing window

#### Current Result (Include screenshots where appropriate.)
The cursor disappears but remains functional
#### Expected Result
The cursor should work and appear normally as it does when any other colorscheme (e.g. Gruvbox) is used
#### Edit
Same phenomenon started with GruvBox too

**Comment by PhilRunninger** [comment]
I doubt this is being caused by NERDTree. Enter this command before and after the cursor disappears to see what is causing it to change. Let me know what you find.

```vim
:verbose highlight Cursor
```

**Comment by LordRishav** [comment]
@PhilRunninger I tried it, and here is the command before the cursor disappears:
![Before](https://user-images.githubusercontent.com/75823494/110662911-f5703000-81eb-11eb-8158-f1d7ccaee3e8.png)

After this, I tried to open NERDTree with `:NERDTreeToggle` and my cursor disappeared after I closed it. I tried to run the command again, but I couldn't even see the command while I was typing. Here is the output after I managed to do it:
![after](https://user-images.githubusercontent.com/75823494/110663280-497b1480-81ec-11eb-9e66-59bc7af8848d.png)

**Comment by PhilRunninger** [comment]
Can you provide a minimal `.vimrc` file that produces the issue? Make sure to identify where you obtained your plugins.

**Comment by LordRishav** [comment]
@PhilRunninger The only option related to NERDTree in my `.vimrc` file is:
```nmap <C-l> :NERDTreeToggle<CR>```
Some GVim options are there too like 
```set guioptions-=r
set guioptions-=T
set guioptions-=R
```
Please let me know if you want to know any other options, or whether I should provide my full `.vimrc` file as it is only 22 lines

**Comment by PhilRunninger** [comment]
Go ahead and share your `.vimrc`, although, I'm not sure it will be all that helpful. I don't have access to a Linux box to test on, so I'd be just guessing.

I really think this is a bug in Vim. NERDTree doesn't do anything to change the cursor's appearance. I found this post - https://stackoverflow.com/questions/1025762/cursor-disappears-in-vim-when-switching-windows-between-vertical-and-horizontal - from a few years back. Some of the suggestions in it may still be relevant.

There also is an issue in the the Vim project with several contributors diagnosing the problem and offering suggestions: https://github.com/vim/vim/issues/480

**Comment by LordRishav** [comment]
Yes, this really seem like a Vim bug. I added `set guioptions-=L` (which removes the left scrollbar) in my `.vimrc` according to the StackOverflow thread which you shared. This might be as NERDTree also opens a window to display its content and I don't use many windows in my workflow, and that's why I didn't notice it happening with any other window.

I'll close this issue here then, as it doesn't belong to NERDTree. Thank you for reply.
