### ISSUE TITLE
How can I add another keybinding for the same command?

### ISSUE THREAD

**Issue by duongdominhchau** [preservim/nerdtree#1235]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

I want to map `<Left>` key to `jumpToParent` without removing the existing keybinding for that command. However, all I found online is either reusing the callback (which is marked private in current version) or changing the keybinding for the command by setting `NERDTreeMapJumpParent` to `<Left>`. What I want to achieve is pressing either `p` or `<Left>` jumps to the parent directory

**Comment by PhilRunninger** [comment]
Put this in your `.vimrc`:

```vim
autocmd FileType nerdtree nmap <Left> p
```

**Comment by duongdominhchau** [comment]
Thank you for your help. I added `<buffer>` right after `nmap` to limit the keybinding to `nerdtree` buffer only and it works as I expected.
