### ISSUE TITLE
How to bind "toggle folder open/close" to <TAB>

### ISSUE THREAD

**Issue by ianpan870102** [preservim/nerdtree#1238]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question

As titled, I believe I'm missing something, but I can't seem to find the function to toggle a folder open/close (reveal/hide its underlying files). I'd like to bind it to `<TAB>`. The default binding for that is `<ENTER>`.

I've tried `:h NERDTree` and browsed the web for an answer, but in vain..

I'm rather new to vim/neovim, coming from an Emacs background. Any help would be much appreciated!

**Comment by PhilRunninger** [comment]
`:h NERDTree-<CR>` is the section you needed to read. Try this:
```vim
let NERDTreeMapCustomOpen = '<TAB>'
```

**Comment by ianpan870102** [comment]
Thanks for the reply @PhilRunninger ! Unfortunately, `let NERDTreeMapCustomOpen = '<TAB>'` has no effect. I wish I were better at vim configuration syntax -- are there any other ways I can try?

**Comment by PhilRunninger** [comment]
Show me what you're doing in your `vimrc` file.

**Comment by ianpan870102** [comment]
@PhilRunninger 

Sure, here you go: https://github.com/ianpan870102/my-dot-files/blob/master/.config/nvim/init.vim

**Comment by PhilRunninger** [comment]
This works.
```vim
" Package configurations
let g:NERDTreeMapCustomOpen = '<Tab>'
let g:NERDTreeShowHidden=1
nnoremap <silent><C-S-e> :NERDTreeToggleVCS<CR>
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif
```

The only thing I can think of, based on your last comment, is that you forgot the `let` keyword. If it still doesn't work, run this command while your cursor is in the NERDTree window:
```vim
:verbose map <Tab>
```
It should report back the following text:
```
n  <Tab>       *@:call nerdtree#ui_glue#invokeKeyMap("<Tab>")<CR>
        Last set from ~/.config/nvim/pack/tmp/opt/nerdtree/lib/nerdtree/key_map.vim line 58
```
If not, it will either say `No mapping found` or some other plugin will have created the mapping. Let me know what that command outputs.

**Comment by ianpan870102** [comment]
Thanks @PhilRunninger ! It works now. Turns out I didn't prepend the `g:` before `NERDTreeMapCustomOpen`.

**Comment by ianpan870102** [comment]
@PhilRunninger I noticed that when I bind g:NERDTreeMapCustomOpen to TAB, I can't use ENTER to perform g:NERDTreeMapCustomOpen anymore.

Is there a way to "add" TAB as an **additional** binding of g:NERDTreeMapCustomOpen and not overwrite ENTER? In other words, I'd like to use both TAB and ENTER interchangeably for g:NERDTreeMapCustomOpen.

There must be a way for vimscript to achieve that, I'm just not that good with it yet...

p.s. Probably not helping, but in Emacs, that'd be something like

```emacs-lisp
(define-key NERDTree-active-map (kbd "<tab>") #'g:NERDTreeMapCustomOpen)
```

which adds "TAB" as an additional mapping for g:NERDTreeMapCustomOpen and also keeps the default ENTER as is.

**Comment by PhilRunninger** [comment]
@ianpan870102 `Enter` no longer works because you've told **NERDTree** that you want `Tab` to do that function instead. To do what you're asking, use this statement instead.
```vim
autocmd FileType nerdtree nmap <Tab> <CR>
```

`autocmd` defines a command to be run when a buffer of type **nerdtree** is created. The command, `nmap`, makes the `Tab` do the same thing as the `Enter` key. See ':help :nmap` for more information. In this situation, don't use `nnoremap`, which will revert to the original unmapped `Enter` behavior instead of the remapping done in **NERDTree**.

**Comment by ianpan870102** [comment]
> autocmd defines a command to be run when a buffer of type nerdtree is created. The command, nmap, makes the Tab do the same thing as the Enter key. See ':help :nmap for more information. In this situation, don't use nnoremap, which will revert to the original unmapped Enter` behavior instead of the remapping done in NERDTree.

Thank you so so much for the detailed explanation. It makes total sense. I really appreciate it!
