### ISSUE TITLE
Files can't be open in NERDtree

### ISSUE THREAD

**Issue by gusye1234** [preservim/nerdtree#1239]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: MacOS Catalina 10.15.7
- [x] Vim/Neovim version `:echo v:version`: 802
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 5.0.0
- [x] vimrc settings
    - [x] NERDTree variables
    ```vim
    let NERDTreeDirArrows=1
    let NERDTreeMinimalUI=1
    let g:NERDTreeDirArrowExpandable = '»'
    let g:NERDTreeDirArrowCollapsible = '«'
    autocmd BufEnter * if 0 == len(filter(range(1, winnr('$')), 'empty(getbufvar(winbufnr(v:val), "&bt"))')) | qa! | endif
    ```
    - Other NERDTree-dependent Plugins
        - [ ] jistr/vim-nerdtree-tabs
        - [x] ryanoasis/vim-devicons
        - [ ] tiagofumo/vim-nerdtree-syntax-highlight
        - [ ] Xuyuanp/nerdtree-git-plugin
        - [ ] Others (specify): 
    - [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
I have empty my `~/.vim/bundle` , and used `vim +PluginInstall +qall` to install all my plugins, and still trapped in this issue. I have uploaded my `~/.vimrc` in Github: https://github.com/gusye1234/vim_config/blob/master/vimrc.2021.
The `vim` I used is installed by `brew`, and the output of `vim --version` is:
```shell
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 13 2020 23:38:53)
macOS version
Included patches: 1-1200
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.32.0/lib/perl5/5.32.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -lpython3.8 -framework CoreFoundation  -lruby.2.7
```
So the steps to reproduce are:
1. Install vim in macOS by `brew` with python3 supported.
2. Copy my `.vimrc` into `~/.vimrc`.
3. Run `vim +PluginInstall +qall`.
4. Open a file, and use `:NERDTreeToggle` to open the NERDtree.
5. Try a file with key `<ENTER>`, `t`, `T`, `s`, `i`, and nothing happens.

But I'm not sure this problem certainly can be reproduced since I don't have another available macOS device.

#### Current Result (Include screenshots where appropriate.)
The folders in NERDtree can be expanded, opened in a new tab. BUT the files can't be opened, whether using `<ENTER>`, `t`, `T`, `s`, `i`. 
#### Expected Result
The files in NERDtree can be opened, using `<ENTER>`, `t`, `T`, `s`, `i`.

**Comment by PhilRunninger** [comment]
You are using the wrong repository for NERDTree. Your line
```vim
Plugin 'The-NERD-Tree'
```
is referencing a [repository](https://github.com/vim-scripts/The-NERD-tree) that is 6 years out of date and no longer being maintained. Use this instead:
```vim
Plugin 'preservim/nerdtree'
````

**Comment by gusye1234** [comment]
Yes, that works for me...
Thanks for your kind reply.
