### ISSUE TITLE
Update imports when moving or renaming a file

### ISSUE THREAD

**Issue by gabrielbeauchemin** [preservim/nerdtree#1240]
When moving or renaming a file, I would like to update all the imports of the project referencing this file. 

Ex. If I move file directoryA/fileA to directoryB/fileA, and that fileB is importing fileA: import { ... } from "directoryA/fileA", I would like the import to be renamed: import {...} from "directoryB/fileA".

Is there a way to accomplish that? Maybe that NERDTree is language agnostic, so this feature won't be aligned with the project. In this case, do you suggest a way or a plugin to accomplish that? It is very important, because if a file needs to be moved/renamed and that means that 15 imports need to be changed manually, it is a huge waste of time.

Thank you very much!

**Comment by PhilRunninger** [comment]
That is the job of an IDE, which Vim is not. NERDTree is simply a file explorer, and Vim is simply a text editor. Other plugins have attempted to bridge the gap, so you may have better luck with them. CoC comes to mind, but I'm not sure if it includes that functionality. Another one I just found is https://github.com/brooth/far.vim.

**Comment by gabrielbeauchemin** [comment]
Ok I understand, thank you.

**Comment by gabrielbeauchemin** [comment]
For anyone trying to do that, I found that with Coc plugin and when installing watchman with it, it does work with most language server.

E.g. with typescript: https://github.com/neoclide/coc-tsserver#features
