### ISSUE TITLE
E492: Not an editor command: MaximizerToggle!

### ISSUE THREAD

**Issue by yukikongju** [preservim/nerdtree#1245]
**Error Message**

Hi, I currently have the following output when trying to open ``:NERDTreeToggle`` :
``E492: Not an editor command: MaximizerToggle!``.

**System Information**

I currently have the following mappings in my .vimrc on Ubuntu 20.04.2 LTS with vim 8.2:
![image](https://user-images.githubusercontent.com/34996954/118385176-cbb3fa80-b5da-11eb-8e03-cfc57b5d22ea.png)

**Steps to reproduce the issue**

1. Add mappings for NERDTree 
2.  Try to open ``:NERDTreeToggle`` with remap ``<leader>m``

**Steps to solve the issue**

First Try:

I have also looked at this similar issue at https://github.com/square/maximum-awesome/issues/160 , and I have tried to update my pluggins with ``:PlugInstall``
since I use https://github.com/junegunn/vim-plug as a plugin manager, but I still get the same error.

Second Try:

I figured that ``:MaximizerToggle`` could be linked to ViM new windows interface, so I tried to download https://github.com/szw/vim-maximizer to solve the issue, but now I can't open ``:NERDTreeToggle``

**Comment by PhilRunninger** [comment]
Is the error happening before you added the **vim-maximizer** plugin, or after?

If your `<leader>m` mapping is showing the error message, you need to find out exactly what it's trying to do. There's a possibility that something else is overriding the mapping in your `.vimrc`. Run this command in vim, and tell me what it says.
```vim
:verbose map <leader>m
```

**Comment by PhilRunninger** [comment]
@yukikongju I'm closing this issue because I haven't heard back from you. Feel free to reopen with the requested information.
