### ISSUE TITLE
Suggested autocmd in README breaks q:

### ISSUE THREAD

**Issue by Yamakaja** [preservim/nerdtree#1246]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question
The suggested autocmd in the README for NT instance mirroring over tabs is breaking `q:` for me:

```vim
" Open the existing NERDTree on each new tab.
autocmd BufWinEnter * silent NERDTreeMirror
```
Result:
![Image describing issue](https://i.imgur.com/3GQWw42.png)

(This should probably have been labeled as a bug, but i can't change the labels myself now)

**Comment by PhilRunninger** [comment]
Have you tried the other suggestion? I actually prefer this one, as it doesn't rely on auto commands. Auto commands can have a nasty habit of interfering with each other, and working in unexpected ways in edge cases such as this.

```vim
" Mirror the NERDTree before showing it. This makes it the same on all tabs.
nnoremap <C-n> :NERDTreeMirror<CR>:NERDTreeFocus<CR>
```

**Comment by Yamakaja** [comment]
Well yes, currently i'm using the following, which also allows me to toggle NERDTree and resizes my windows for me:
```vim
nnoremap <C-n> :NERDTreeToggle<CR>:if exists('b:NERDTree') <bar> silent NERDTreeMirror <bar> endif<CR><C-w>=
```

Still, the suggestion should probably be changed if it breaks stuff ^^
