### ISSUE TITLE
How can I make NERDTree-<CR> to act differently on some condition?

### ISSUE THREAD

**Issue by jin8495** [preservim/nerdtree#1247]
#### Self-Diagnosis

- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### State Your Question
I usually open vim on root directory without argument. So I open files with NERDTree (I am really appreciating your work by the way).
I set my vimrc like below,
```
let NERDTreeCustomOpenArgs = {'file' : {'where' : 'p', 'reuse' : 'all', 'keepopen' : 1, 'stay' : 1}}
```
I usually work on tabs, so I tried mapping NERDTree-\<CR\> to 't'. But, in empty window, it doesn't work as I expect. Literally it opens new tab.
So I want to map NERDTree-\<CR\> to 'p' when a window is empty and 't' if it is not empty.

Is there a way to do that??

**Comment by PhilRunninger** [comment]
There's no way to do that using NERDTree's built-in settings. You could override the <CR> key with your own function. Search the NERDTree documentation to learn how the API works.
