### ISSUE TITLE
Nerdtree not autoclose on new tab

### ISSUE THREAD

**Issue by Hungpro3112** [preservim/nerdtree#1248]
I open a new tab in vim use :tabnew and it has a new NERDTree because i use this feature in my _vimrc but when i close the tab it just deletes a file, the NERDTree was still there.

This is line i use in vim to close nerd tree when it is a last window but it just works in 1 tab 
" Exit Vim if NERDTree is the only window left.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() |
    \ quit | endif

I think Nerdtree-developers need to add new feature about my issue to improve UX. Thanks for reading.

**Comment by PhilRunninger** [comment]
If you want Vim to close the tab when NERDTree is only window left in it, then change the `autocmd` statement to this:
```vim
" Exit Vim if NERDTree is the only window left.
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
```

**Comment by PhilRunninger** [comment]
I'll update the ReadMe with this answer.
