### ISSUE TITLE
NERDTree with blank page not close

### ISSUE THREAD

**Issue by Hungpro3112** [preservim/nerdtree#1250]
When use vim, sometime i open vim with nerdtree and blank page to test some function or when you open vim with NERDTree from the beginning, and i can not close them in 1 time with :q! or :wq or :x. This quite annoying for me. Can anyone help me?

**Comment by PhilRunninger** [comment]
`:qa`, which stands for **quit all**, is the command you need to use. It will close all windows and all tabs.
