### ISSUE TITLE
File/Directory creation and deletion

### ISSUE THREAD

**Issue by anurag3301** [preservim/nerdtree#1251]
Can you please add this feature so that we can create/delete files and folders directly from the nerd tree as we can in vscode.

And can you make NERDTree update as we do any changes to the working dir?

**Comment by PhilRunninger** [comment]
This functionality already exists. See `:h NERDTreeMenu`. It won't refresh automatically when there are outside changes to the file system, but you can refresh the tree easily with the `r` and `R` keys.

**Comment by PhilRunninger** [comment]
@anurag3301 My explanation was a little brief. You can access the menu by pressing `m`. This will display the menu associated with the node under the cursor. From there you have access to other functions like creating, deleting, copying, and moving files and directories.

Automatic refresh would involve a separate process to monitor the directory, and I have no plans to add that.

**Comment by anurag3301** [comment]
Got thanks, I didn't know NERDTree has that many options, ill create new bindings.
