### ISSUE TITLE
Error detected while processing ...NERD_tree.vim

### ISSUE THREAD

**Issue by jonnyrobbie** [preservim/nerdtree#1254]
#### Self-Diagnosis
Before creating an issue, take some time to search these resources for an answer. It's possible that someone else has already seen and solved your issue.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### Environment
- Operating System: macos big sur 11.5.1
- Vim/Neovim version `:version`: 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 06 2021 19:34:38)
macOS version - x86_64
Included patches: 1-3300
Compiled by Homebrew
```
- NERDTree version, found on first line of quickhelp `?`: 
- Are you using any of these NERDTree-dependent plugins?  
    - [x] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [x] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [x] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.

#### Steps to Reproduce the Issue
1. Open vim

#### Current Behavior (Include screenshots where appropriate.)

An error shows up:
`Error detected while processing /Users/user/.vim/plugged/nerdtree/plugin/NERD_tree.vim[229]..function nerdtree#postSourceActions[5]..script /Users/user/.vim/plugged/nerdtree-project-plugin/nerdtree_plugin/project.vim:
line   45: E1208: -complete used without allowing argumentsPress ENTER or type command to continue`

#### Expected Result

Clean start

#### Notes

I did a system (company managed) os update. It may be related.
Also NERDTree "seems" to work if I ignore the error message (as far as I can tell).

**Comment by PhilRunninger** [comment]
This looks like a bug in `nerdtree-project-plugin`. There is 5-day-old pull request there to fix it, but I don't know when @scrooloose will merge it in. See https://github.com/scrooloose/nerdtree-project-plugin/pull/2. I see that you compiled Vim on August 6. I wonder if a new patch in Vim is causing this bug to surface.

**Comment by jonnyrobbie** [comment]
I'm sorry I didn't reply sooner. This is probably it. I guess I basically didn't use the plugin, so no harm for me in just deleting it. Thanks for the heads up.
