### ISSUE TITLE
NERDTreeFocusToggle command

### ISSUE THREAD

**Issue by SarveshMD** [preservim/nerdtree#1257]
#### Description
We could have a command `NERDTreeFocusToggle`. 
It's purpose could be to check for two things, if nerdtree is already focused when the command is called, and if nerdtree is already open when the command is called. 
Then it could focus nerdtree if nerdtree is not already focused or not already open. 
It could close nerdtree if nerdtree is open and focused. 
The NERDTreeToggle command opens nerdtree and focuses or closes nerdtree if it's already open, it doesn't make any difference if nerdtree is already focused. 

This command will be useful for users switching from Visual Studio Code because VS Code's `Ctrl+b` does the same thing I have requested for this new command. The command name could be changed.

**Comment by PhilRunninger** [comment]
@SarveshMD This should do the trick for you. Put this line in your `.vimrc` file:
```vim
nnoremap <silent><expr> <C-B> (winnr()==g:NERDTree.GetWinNum() ? ":NERDTreeClose\<CR>" : ":NERDTreeFocus\<CR>")
```

**Comment by ZeChArtiahSaher** [comment]
```
function! ToggleNERDTree()
  if (winnr() == g:NERDTree.GetWinNum())
    execute "wincmd p"
  else
    :NERDTreeFocus
  endif
endfunction

nnoremap <M-b> :call ToggleNERDTree()<CR>
```
