### ISSUE TITLE
Example snippet to skip loading NERDTree for small mobile screens

### ISSUE THREAD

**Issue by mcandre** [preservim/nerdtree#1270]
#### Description

I enjoy using Vim NERDTree on desktop and tablet screens. However, when using Vim on small screen devices such as phones, then I would like to optionally hide NERDTree.

Can we please expand the README to show a snippet that avoids loading NERDTree when the screen width is very small?

**Comment by PhilRunninger** [comment]
Since this is not a very common situation, I'll answer your question here, and not with a change to the README. You can simply add the width condition to your autocmd's `if` statement. For example:

```vim
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists('s:std_in') && &columns > 200 | NERDTree | endif
```
