### ISSUE TITLE
Error detected while processing function. Not allowed to edit another buffer now

### ISSUE THREAD

**Issue by caokietbk** [preservim/nerdtree#1271]
I'm a newbie in vim and I currently set up my vim config for golang development environment.
I read your document and it said: 
" Open the existing NERDTree on each new tab.
autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif

but when I use golang :GoMetaLinter I see the error like below:

![image](https://user-images.githubusercontent.com/45527841/135626546-b4f4fe85-fa71-4b1e-bd60-134c1de57268.png)

And my question is: how to open the existing NERDTree on each new tab without that error.

Here is my full vim config. But I think this error because of the NERDTree command above:
https://github.com/caokietbk/golang-vim-config.git

I'm looking forward to hearing from you soon.
Thanks.

**Comment by PhilRunninger** [comment]
First, let's see what functions are throwing the exception. Enter these commands and report back what they print out. Keep in mind the numbers may be different now than when you created the issue.
```vim
:verbose func {194}
:verbose func {195}
:verbose func {205}
```

It may be the case that this auto command won't work with your setup; that is, it could be conflicting with `vim-go`. If that's the case, you could use the other suggestion in the NERDTree README. I actually like this better because it doesn't use auto commands.
```vim
" Mirror the NERDTree before showing it. This makes it the same on all tabs.
nnoremap <C-n> :NERDTreeMirror<CR>:NERDTreeFocus<CR>
```

**Comment by caokietbk** [comment]
Thank for your response.

Yes. I read document and I knew your solutions above but I want something automation.

Here is commands's output:
:verbose func {194}
![image](https://user-images.githubusercontent.com/45527841/136020789-91cd4e46-acda-445a-8e43-7800b42660a9.png)
:verbose func {195} image 1.
![image](https://user-images.githubusercontent.com/45527841/136021220-540d4335-bd30-4aa7-b39c-2e60a5293e3d.png)
:verbose func {195} image 2.
![image](https://user-images.githubusercontent.com/45527841/136021287-d92703b6-98b1-4781-b9c4-8eb83d6d269a.png)
:verbose func {205}
![image](https://user-images.githubusercontent.com/45527841/136021349-fc08a540-98f7-4c97-a132-6095c7c72fc1.png)

Hope it's enough for you to find the issues.

**Comment by vhmh2005** [comment]
I got the same issue

**Comment by nickspoons** [comment]
This error can be triggered simply by opening a new session and running `:copen`. There is a proposed fix/workaround in [1275](https://github.com/preservim/nerdtree/issues/1275#issuecomment-944935231):

```vim
" Open the existing NERDTree on each new tab.
autocmd BufWinEnter * if &buftype != 'quickfix' && getcmdwintype() == '' | silent NERDTreeMirror | endif
```

The suggested autocmd in the README is a bad recommendation and should be removed or updated.
