### ISSUE TITLE
Sorting by name sorts folders before files

### ISSUE THREAD

**Issue by KwatME** [preservim/nerdtree#1276]
![Screen Shot 2021-10-19 at 12 02 55](https://user-images.githubusercontent.com/7741548/137965895-887fc929-b1e0-4bab-8b2f-3c456e343fb3.png)

How can I make `1.fatigue.md` appear before `2.weight.md`?

**Comment by KwatME** [comment]
![Uploading Screen Shot 2021-10-19 at 12.41.48.png…]()

**Comment by marioferpa** [comment]
Did you solve this or just gave up?

**Comment by KwatMDPhD** [comment]
Sovled it.

**Comment by maxims94** [comment]
I also ran into this problem. Here's how I solved it:
```
let NERDTreeSortOrder=[]
```

For details, consult the documentation on `NERDTreeSortOrder`. It's quite thorough.

Oh and don't trust ChatGPT. It gave me a bogus answer.
