### ISSUE TITLE
Closing vim with Nerdtree

### ISSUE THREAD

**Issue by wojciechGaudnik** [preservim/nerdtree#1277]
Hi
I'm using ":bd" to close tabs/windows, it is important to me because when I'm closing the current single window and some other files left in the buffer then automatically switch mi to another, and doesn't close vim. I am struggling for few days with how to do it when the last window is the last open file and independent of that if Nerdtree is opened I would like to exit from vim. I will be grateful for yours help.

**Comment by igbanam** [comment]
If you want to exit from Vim regardless, `:qa` should get you out.

In any case, this is also handled in the README in [How can I close Vim of a tab automatically when NERDTree is the last window](https://github.com/preservim/nerdtree#how-can-i-close-vim-or-a-tab-automatically-when-nerdtree-is-the-last-window)
