### ISSUE TITLE
Folder won't open if path contains apostrophe (')

### ISSUE THREAD

**Issue by willchao612** [preservim/nerdtree#1278]
System info:

- Neovim 0.6.0
- Kubuntu 20.04.3 LTS
- Latest nerdtree

I don't know if anybody else has experienced the same issue since there are no other complaints, but when I open a folder say "Foo's Bar" it won't open. At first I thought it was because of that space between words but when I remove it the error still occurred. I then remove the apostrophe and it worked.

Maybe this is the expected behavior since punctuation or special characters are usually not used in paths but I figure it is worth mentioning it. (Or it could be a bug)

**Comment by iago-pssjd** [comment]
And does the folder open if it contains a space? Have you tried? with "Foos Bar" name? I am getting a similar issue and my hypothesis is the space presence, becaue I do not have any (other) special character in the name.

**Comment by KarateJB** [comment]
Tried opening a directory that conatains blank and it didn't list what within it.

![](https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgJcppU8Dq_ljqQDnzScqBnOuKqekssh-5m6kRjdocQA90lBHxN_oHxdXyjJtk_EEkd6U05yJkZs0TUBaRhNhvluIYEUP683GD1Hk8A8gTIdvxQ6azIAfYwPZyTEDGNX9dl5WZxcEuceOQK42hZ7pXxiyEEZFaqH9LF4dgMuqcuz-zxLd-gkpdEkK_w/s559/vim-nerdtree-issue.jpg)

**Comment by rzvxa** [comment]
I cannot reproduce this issue, Since this issue has been stale for a long time I'm going to close it, Feel free to reopen it with a minimal .vimrc / init.vim file that can produce it.
