### ISSUE TITLE
Binding C-b and C-o 

### ISSUE THREAD

**Issue by bryant-the-coder** [preservim/nerdtree#1279]
I wanna bind this 2 keys to bookmark and open the bookmark.But how?

**Comment by igbanam** [comment]
You can bind the key to `:Bookmark <name>` and another to `:OpenBookmark <name>`

How did I get here?
- `:NERDTreeToggle`
-  `?`
- `/bookmark`
- `B`

This shows you the list of bookmarking commands NERDTree gives you.
