### ISSUE TITLE
Closing Vim with cursor under NERDTree

### ISSUE THREAD

**Issue by sicr0** [preservim/nerdtree#1282]
Before creating an issue, take some time to search these resources. It's possible that someone else has already asked your question and gotten an answer.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resource: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### State Your Question
Is there a way to close Vim when I type `:q` with the cursor under NERDTree instead of just closing NERDTree? Sometimes I have the cursor there, I want to close Vim and I end up typing `:q :q` to exit. Maybe some autocmd in `.vimrc`

**Comment by le-michael** [comment]
Try `:qa`
