### ISSUE TITLE
Add Prolog `.pro` support

### ISSUE THREAD

**Issue by sicr0** [preservim/nerdtree#1284]
#### Description
![Screenshot_20211105_212008](https://user-images.githubusercontent.com/49662650/141343947-fb75cd2a-2b6d-4e9d-b279-5a5a1072d4ad.png)

The .pl file extension is used by both Perl and Prolog, but since Perl is more widespread I wouldn't mind if it were one loaded. But Prolog also has .pro file extension, and Nerd Fonts has the nf-dev-prolog icon () that could be used since it doesn't have misinterpretation.

Thanks for your time.

**Comment by rzvxa** [comment]
Hello, you should ask for this on the icon provider that you are using(If I had to guess I would've said that you are using `ryanoasis/vim-devicons`)
NerdTree itself doesn't have any icons and third-party plugins can extend it to add icons and or things like git status of files/directories.
You can create a pull request for it on the icon provider's GitHub repo.
for example on `vim-devicons` it can be added in this file.
https://github.com/ryanoasis/vim-devicons/blob/71f239af28b7214eebb60d4ea5bd040291fb7e33/plugin/webdevicons.vim#L254
If you happen to want to contribute to that project don't forget about adding the appropriate test case to the https://github.com/ryanoasis/vim-devicons/blob/master/test/filetype.vim file.

You can easily copy a test case from another single file type language(for example go)
```vim
function! s:suite.OneArgument_GetGoIcon()
  call s:assert.equals(WebDevIconsGetFileTypeSymbol('test.go'), '')
endfunction
```
