### ISSUE TITLE
NERDTree does not update its tree when changing working directory

### ISSUE THREAD

**Issue by ericktucto** [preservim/nerdtree#1286]
Use fzf to change working directory

I share my code (lua) that I use to change working directory:

```lua
function Projects()
  coroutine.wrap(function()
   -- table projects, example { '/home/erick/Proyectos/glux', '/home/erick/.dotfiles' }
    local projects = require('project_nvim').get_recent_projects()
    local result = fzf.fzf(projects, "--ansi", { border = false })
    if result then
      -- change working directory
      require('project_nvim.project').set_pwd(result[1], "stixcode")
    else
      print("Ups error")
    end
  end)()
end
```

My home directory was /home/erick/Proyectos/glux but when changing to /home/erick/.dotfiles, NERDTree does not update
![imagen](https://user-images.githubusercontent.com/22831024/143730666-1a7fe1e1-83c5-4cbb-8c5c-f584588a4388.png)

I temporarily fix it using the NERDTreeCWD function, but this unnecessarily opens NERDTree
```lua
function Projects()
  coroutine.wrap(function()
   -- table projects, example { '/home/erick/Projects/nerdtree', '/home/erick/Projects/fzf.vim' }
    local projects = require('project_nvim').get_recent_projects()
    local result = fzf.fzf(projects, "--ansi", { border = false })
    if result then
      -- change working directory
      require('project_nvim.project').set_pwd(result[1], "stixcode")
      --> Update NERDTree <--
      vim.fn["NERDTreeCWD"]()
    else
      print("Ups error")
    end
  end)()
end
```

this is because it is called the function NERDTree Focus is called in NERDTreeCWD
[preservim/nerdtree:/plugin/NERD_tree.vim#L213](https://github.com/preservim/nerdtree/blob/81f3eaba295b3fceb2d032db57e5eae99ae480f8/plugin/NERD_tree.vim#L213)

__Is there a way to update NERDTree after changing working directory?__

**Comment by rzvxa** [comment]
Here is the code for doing this using Vimscript:
```vim
    let l:cwdPath = g:NERDTreePath.New(getcwd())
    let l:newRoot = g:NERDTreeFileNode.New(l:cwdPath, b:NERDTree)
    call b:NERDTree.changeRoot(l:newRoot)
```
Since this issue has been stale for a while I'm going to close it but feel free to reopen it if you have any further questions.
