### ISSUE TITLE
[Windows] NERDTree throws an error when trying to delete a folder

### ISSUE THREAD

**Issue by Drllap** [preservim/nerdtree#1289]
#### Environment
- Operating System: Windows 10
- Vim/Neovim version: NVIM v0.6.1
- NERDTree version, found on first line of quickhelp `?`: 6.10.16
- Are you using any of these NERDTree-dependent plugins?  
    - [ ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.
```
call plug#begin(stdpath('data') . '/test-plugged')
Plug 'preservim/nerdtree'
call plug#end()
```

#### Steps to Reproduce the Issue
1. Create an empty folder
2. Use (m) to open NERDTree Menu
3. Select the new empty folder
4. Use (d) to delete the folder

#### Current Behavior (Include screenshots where appropriate.)
An error appears `NERDTree: Could not remove node`
and the folder isn't removed

#### Expected Result
The folder should be removed

**Comment by rzvxa** [comment]
I cannot reproduce it but right now I have Windows 11 installed(which I don't think to be a big issue).
Since this issue has gone stale, I'm going to close it, Feel free to reopen it in the future if you find that it still doesn't work as expected.

**Comment by lmcr666** [comment]
Am also getting this issue, got no clue as to why or how to fix it, just want to delete this empty folder 😞
