### ISSUE TITLE
nerdtree error in neovim i am not quit sure how to fix this problem because i am new to the linux os

### ISSUE THREAD

**Issue by sameer333** [preservim/nerdtree#1292]
Error detected while processing /home/sameer/.config/nvim/pack/vendor/start/nerdtree/syntax/nerdtree.vim:
line   24:
E121: Undefined variable: g:NERDTreeNodeDelimiter
Press ENTER or type command to continue
Error detected while processing /home/sameer/.config/nvim/pack/vendor/start/nerdtree/syntax/nerdtree.vim:
line   24:
E116: Invalid arguments for function char2nr
Press ENTER or type command to continue
Error detected while processing /home/sameer/.config/nvim/pack/vendor/start/nerdtree/syntax/nerdtree.vim:
line   39:
E121: Undefined variable: g:NERDTreeNodeDelimiter
Press ENTER or type command to continue
Error detected while processing /home/sameer/.config/nvim/pack/vendor/start/nerdtree/syntax/nerdtree.vim:
line   48:
E121: Undefined variable: g:NERDTreeNodeDelimiter
Press ENTER or type command to continue
Error detected while processing /home/sameer/.config/nvim/pack/vendor/start/nerdtree/syntax/nerdtree.vim:
line   50:
E121: Undefined variable: g:NERDTreeNodeDelimiter

**Comment by rzvxa** [comment]
Since this issue has been stale for a long time, I'm going to close it.
Feel free to reopen if you still have this issue.
