### ISSUE TITLE
Weird text after directory name in nerdtree.

### ISSUE THREAD

**Issue by talwat** [preservim/nerdtree#1293]
#### Self-Diagnosis
Before creating an issue, take some time to search these resources for an answer. It's possible that someone else has already seen and solved your issue.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### Environment
- Operating System: Pop!_os
- Vim/Neovim version `:version`: Vim 8.2
- NERDTree version, found on first line of quickhelp `?`: 6.10.16
- Are you using any of these NERDTree-dependent plugins?  
    - [x] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [x] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [x] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
autocmd VimEnter * NERDTree | wincmd p
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

filetype plugin on

call plug#begin('~/.vim/plugged')

Plug 'https://github.com/ycm-core/YouCompleteMe.git'
Plug 'mbbill/undotree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/tagbar'
Plug 'jreybert/vimagit'
Plug 'tpope/vim-fugitive'
Plug 'pangloss/vim-javascript'
Plug 'elzr/vim-json'
Plug 'terryma/vim-multiple-cursors'
Plug 'scrooloose/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'preservim/nerdcommenter'

call plug#end()
```

#### Steps to Reproduce the Issue
1. Use zsh & kitty full screened (Do Ctrl + Shift + F11)
2. Make sure you have nerdtree open on startup
3. Open a file

#### Current Behavior (Include screenshots where appropriate.)
![image](https://user-images.githubusercontent.com/83217276/151039697-2fffee71-dba4-4e98-8e76-967ccf096cbf.png)
It shows strange text after the file directory, however, it doesn't show up when I use bash. Instead, it only shows up when I use zsh.

#### Expected Result
The expected result should be what it is when I click on the other window and it goes back to normal.
![image](https://user-images.githubusercontent.com/83217276/151041386-8e3c0b81-9e46-410c-865f-db64ad389582.png)

**Comment by rzvxa** [comment]
Since this issue has gone stale I'm going to close it.
As for the problem itself, It needs further information for debugging and needs the original author's cooperation to find the actual issue. Feel free to reopen it if you are experiencing this issue.
