### ISSUE TITLE
An option I added to .vimrc crashes with grep

### ISSUE THREAD

**Issue by jin8495** [preservim/nerdtree#1294]
Before creating an issue, take some time to search these resources. It's possible that someone else has already asked your question and gotten an answer.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resource: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

---------------
#### State Your Question

I added the code below into my .vimrc from the README.md of the repo.
```
" Open the existing NERDTree on each new tab.
autocmd BufWinEnter * if getcmdwintype() == '' | silent NERDTreeMirror | endif
```

And when I grep some word, I get the message like this.
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/49510451/151880463-e1ac5698-24e9-499f-beef-ae8265aea0d0.png">

I greped using some plugins
- https://github.com/MarSoft/nerdtree-grep-plugin
- https://github.com/dkprice/vim-easygrep

Is there a way to resolve the problem while I still use the grep and the option I added?

**Comment by asadakbar** [comment]
I also added the same code to my vimrc and hit this issue
````
E492: Not an editor command:  silent NERDTreeMirror | endif
````
I'm not sure if its related but posting in case anyone else comes across it.

**Comment by rzvxa** [comment]
this issue has been solved using the new snippet from the readme file:
```vim
" Open the existing NERDTree on each new tab.
autocmd BufWinEnter * if &buftype != 'quickfix' && getcmdwintype() == '' | silent NERDTreeMirror | endif
```
