### ISSUE TITLE
Error: "E1208: -complete used without -nargs" reported on client start

### ISSUE THREAD

**Issue by dsr432** [preservim/nerdtree#1295]
#### Environment
- Operating System: Windows 11
- Neovim version `:version`: 0.6.1 and Neovide version `:version`: 0.5.0
- NERDTree version, found on first line of quickhelp `?`: version 6.10.16
- Are you using any of these NERDTree-dependent plugins?  
    look to config
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
call plug#begin()

Plug 'arcticicestudio/nord-vim'
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'scrooloose/nerdtree-project-plugin'
Plug 'PhilRunninger/nerdtree-buffer-ops'
Plug 'PhilRunninger/nerdtree-visual-selection'

call plug#end()
```

#### Steps to Reproduce the Issue
1. use neovide or neovim on windows (isntalled with scoop)
2. create nvim/init.vim with above config
3. run ':PlugInstall'
4. look for error :>

#### Current Behavior (Include screenshots where appropriate.)
error reported on startup of neovim and neovide:
![image](https://user-images.githubusercontent.com/66963044/153274425-fd6f74ca-be9b-4f60-904e-76f42da37d0d.png)
running NERDTree does still work, not entirely sure what this effects but it's an error!

#### Expected Result
No reported error :>

**Comment by Karkoon** [comment]
Hi, so I encountered the same problem and I believe it's an issue with the `scrooloose/nerdtree-project-plugin` plugin.

It has a fix which wasn't merged. https://github.com/scrooloose/nerdtree-project-plugin/pull/2
