### ISSUE TITLE
Edit new file will lose file name after modify .vimrc to compatible netrw

### ISSUE THREAD

**Issue by keepsaunter** [preservim/nerdtree#1297]
#### Self-Diagnosis
Before creating an issue, take some time to search these resources for an answer. It's possible that someone else has already seen and solved your issue.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### Environment
- Operating System: 
- Vim/Neovim version `:version`: 
- NERDTree version, found on first line of quickhelp `?`: 
- Are you using any of these NERDTree-dependent plugins?  
    - [ ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
function! s:OpenFileOrExplorer(...)
    if a:0 == 0 || a:1 == ''
        NERDTree
    elseif filereadable(a:1)
        execute 'edit '.a:1
        return 0
    elseif a:1 =~? '^\(scp\|ftp\)://' " Add other protocols as needed.
        execute 'Vexplore '.a:1
    elseif isdirectory(a:1)
        execute 'NERDTree '.a:1
    endif
    return 1
endfunction

" Auto commands to handle OS commandline arguments
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc()==1 && !exists('s:std_in') | if <SID>OpenFileOrExplorer(argv()[0]) | wincmd p | enew | wincmd p | endif | endif

" Command to call the OpenFileOrExplorer function.
command! -n=? -complete=file -bar Edit :call <SID>OpenFileOrExplorer('<args>')

" Command-mode abbreviation to replace the :edit Vim command.
cnoreabbrev e Edit

```

#### Steps to Reproduce the Issue
1. install Nerdtree by pathogen
2. modify .vim/vimrc according to README.md of this project
![image](https://user-images.githubusercontent.com/29244475/154950866-09c01d4b-e6c9-4a87-a68c-0851e1b52948.png)

3. open a new file by vim in command line
```vim newFileName.sh```

#### Current Behavior (Include screenshots where appropriate.)
![image](https://user-images.githubusercontent.com/29244475/154949788-bef89dc1-d2d1-484c-91c1-40760620d920.png)

got a error when save this new file
![image](https://user-images.githubusercontent.com/29244475/154949889-faf8ff2a-504a-4ad0-a668-092955bdedd4.png)

#### Expected Result
When i edit a new file, it should be this:
![image](https://user-images.githubusercontent.com/29244475/154950314-3bf3f3ac-76fd-4882-9427-18276b8f7746.png)

**Comment by rzvxa** [comment]
I cannot reproduce this issue, And it's been a while since the creation of this issue.
Feel free to reopen it if you are still experiencing the same issue.
