### ISSUE TITLE
NERDTreeNodeDelimiter causes jagged indent with nerdtree-git-plugin

### ISSUE THREAD

**Issue by sshock** [preservim/nerdtree#1298]
#### Environment
- Operating System: macOS
- Vim version: 8.2
- NERDTree version: 6.10.16
- Are you using any of these NERDTree-dependent plugins?
    - [x] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)

#### Steps to Reproduce the Issue
1. View any directory with git modified files

#### Current Behavior (Include screenshots where appropriate.)

Jagged indents due to NERDTreeNodeDelimiter (the space in front of the filename).

<img width="373" alt="jagged" src="https://user-images.githubusercontent.com/1693761/156982794-757faeb1-c90f-43b1-8afe-5aa00b7c43e9.png">

#### Expected Result

No jagged indents.

<img width="383" alt="no jagged" src="https://user-images.githubusercontent.com/1693761/156982839-b1b98e3b-6d1b-4c0a-88ee-690bd57301f9.png">

#### Notes
* Until recently I was using a version of NERDTree from 3.5 years ago, and it didn't have this problem.
* I tried to workaround this issue myself by setting `let g:NERDTreeNodeDelimiter = ""` in my ~/.vimrc, and it fixed the issue but at the same time introduced a bigger issue where it wouldn't allow me to expand any directory.

**Comment by sshock** [comment]
I wasn't expecting this but I installed vim from homebrew (still version 8.2) and this problem went away.

I think it's because the OS-included vim does not have the `conceal` feature but the homebrew one does.

**Comment by vieo97** [comment]
When I use "ga" command to display the current cursor character and its ASCII value

In the first image, you can see that there are "spaces".
![Image](https://github.com/user-attachments/assets/e88408a9-5b29-4582-81a2-8293bce414d8)

In the second image, when I press the arrow key →, my cursor points to a, and the vertical and horizontal highlight points to a, but ga shows "^G"
![Image](https://github.com/user-attachments/assets/3e95c8f3-89cf-4f96-92b4-1028c2ae1f33)

In the third picture, when I press the arrow keys again →, my cursor points to a, but it highlights to c, and ga shows "a"
![Image](https://github.com/user-attachments/assets/6d4fa8d5-ae88-401a-b4ce-881f8a03281b)

In the fourth picture, by pressing the arrow keys again →, my cursor points to b, but it is highlighted horizontally and vertically to d, and ga shows "b"
![Image](https://github.com/user-attachments/assets/d096e705-e3b0-48f0-952e-13c5e67d5590)

Also, let NERDTreeNodeDelimiter= "\u00a0" does not solve this problem, in front of each file, there is a character (^G) that is not displayed, causing the cursor and the horizontal and vertical highlighted position to be misaligned.

This leads to a problem, when I use the mouse to select a file name as in the fifth image, the selected file name area is smaller than the area the mouse travels through.
![Image](https://github.com/user-attachments/assets/0a43b584-1924-462d-84c0-b3a46435a228)
