### ISSUE TITLE
Scroll down issue with putty

### ISSUE THREAD

**Issue by vladgh** [preservim/nerdtree#130]
I'm not sure this is a bug but when I use vim inside putty on windows, scrolling down with the scroll wheel opens a new split with the file under  the cursor. Scrolling up works without a problem. I should also mention that everything works when using Ubuntu's terminal, or gvim, or iterm2 on Mac. So it could be just a putty issue. This is weird because scrolling both up and down works ok inside vim and active file window. I only have this issue when scrollIng down inside the active nerdtree window. 
Can someone offer me some advice regarding this?

**Comment by wanovak** [comment]
FYI for those who still have this problem, "acidtonic" 's fix still works, however it must now be applied to the following file: autoload/nerdtree/ui_glue.vim

**Comment by AdamSLevy** [comment]
This is also a problem for ThinkPad keyboards that use the little nib with the middle mouse button to scroll.

**Comment by AdamSLevy** [comment]
It would be nice if this was a configurable option.
