### ISSUE TITLE
Close the tab if NERDTree is the only window remaining in it also close vim if using with lightline-bufferline

### ISSUE THREAD

**Issue by hungpham3112** [preservim/nerdtree#1300]
#### Environment
- Operating System: Windows
- Vim/Neovim version `:version`: 8.2.4557
- NERDTree version, found on first line of quickhelp `?`: 
- Are you using any of these NERDTree-dependent plugins?  
    - [ ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [X] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                             Plugin: NERDTree                               "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Short cuts
nnoremap <F8> :silent NERDTreeFind <bar> NERDTreeCWD<CR>
nnoremap <C-t> :silent NERDTreeToggle<CR>

" Close the tab if NERDTree is the only window remaining in it.
"autocmd BufEnter * silent if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

" If another buffer tries to replace NERDTree, put it in the other window, and bring back NERDTree.
autocmd BufEnter * silent if bufname('#') =~ 'NERD_tree_\d\+' && bufname('%') !~ 'NERD_tree_\d\+' && winnr('$') > 1 |
    \ let buf=bufnr() | buffer# | execute "normal! \<C-W>w" | execute 'buffer'.buf | endif

let NERDTreeIgnore = ['\.DAT$[[file]]', '\.LOG1$[[file]]', '\.LOG1$[[file]]','\c^ntuser\..*']
let NERDTreeDirArrowExpandable=" "
let NERDTreeDirArrowCollapsible=" "
let g:NERDTreeWinSize = 40
let g:NERDTreeWinPos = "right"
let NERDTreeShowHidden = 1

nnoremap <silent> <leader>d :up<CR>:bd<CR> "This line for deleting a buffer

```

#### Steps to Reproduce the Issue
1. use lightline-bufferline plugin
2. use above vimrc

#### Current Behavior (Include screenshots where appropriate.)
It closes vim if  `<leader>d` when you have 2 buffers and NerdTree on. With NerdTree turn off it can delete normal. Bug causes by this line:

" Close the tab if NERDTree is the only window remaining in it.
"autocmd BufEnter * silent if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

Remove it and everything is ok.

![bandicam 2022-03-17 18-12-22-313](https://user-images.githubusercontent.com/75968004/158798698-9285a327-f200-4b10-8496-3e5e2f0a865d.gif)

#### Expected Result
Still  Close the tab if NERDTree is the only window remaining in it but also can delete current buffer like normal.

**Comment by thisisrandy** [comment]
I'm not familiar with lightline-bufferline, but I believe the problem can be reduced to the following: If there is a single open window in addition to NERDTree and multiple buffers are open, closing the *active* buffer (e.g. with `bd`) causes `winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree()` to evaluate to `true`, which erroneously triggers the `autocmd` in question and quits vim.

I'm not familiar enough with vimscript to devise a better condition, but perhaps someone with more expertise could refine it appropriately.

**Comment by nhejazi** [comment]
I'm running into this issue now too, so just indicating interest in case anyone is able to resolve this problem. the comment above about it being triggered makes sense, but disabling lightline-bufferline doesn't actually fix this for me

**Comment by rzvxa** [comment]
The code mentioned in the issue checks for the number of open windows, if there is only a `NERDTree` buffer open it will quit the vim.
Since `bd` would close the window with the buffer unless it is the last remaining window, It would result in the buffer getting closed with its window and only one window remaining, which is the one displaying the NERDTree and it would cause that code to fire.

I'm going to mark it as `wont-fix` because it is an issue with the example configuration and it is working as expected since doing it the correct way isn't really possible without an over complicated workaround.
