### ISSUE TITLE
NERDTreeFind without moving cursor to NERDTree split

### ISSUE THREAD

**Issue by StrongerXi** [preservim/nerdtree#1301]
#### Description
I found `NERDTreeFind` to be a very useful feature when I started using `fzf`. However, it's slightly annoying that it moves the cursor from the newly opened split to NERDTree split. Is there a way to prevent the cursor from moving?

**Comment by mark2185** [comment]
`nnoremap <F4> :NERDTreeFind<CR><c-w>w` ?
