### ISSUE TITLE
In command window mode when switching back to command line mode with "ctrl + c", the text invisible, any sort of 

### ISSUE THREAD

**Issue by ediw8311xht** [preservim/nerdtree#1309]
#### Environment
- Manjaro Linux 21.2.5
- Display Manager: i3
- Terminal: st
- Vim/Neovim version: v0.6.1
- NERDTree version: 6.10.14

#### Steps to Reproduce the Issue
1. Go into "Command Window Mode" ":q + ctrl+f" or "q:". Type text, or go back to a previous command then press "ctrl + c" to go back to Command Line Mode.

#### Current Behavior (Include screenshots where appropriate.)
1. Text is invisible when switching from "Command Window Mode" into "Command Line Mode", until you press a key on your keyboard or change window focus.

#### Expected Result
1. Text should be visible automatically when switching between "Command Window Mode" and "Command Line Mode".

**Comment by rzvxa** [comment]
I'm going to close this one as I cannot reproduce it and is perhaps a configuration error.
If you think it's not a configuration problem and can reproduce it with vanilla settings on i3, st, and NERDTree please consider creating a new issue, This one is stale and won't get much attention.
