### ISSUE TITLE
Remove `*` and `/` from the end of file name

### ISSUE THREAD

**Issue by XenoBino** [preservim/nerdtree#1313]
I have (from my [dotfiles](XenoBino/dotfiles)):

```
</home/dotfiles
▸ bash/
▸ vim/
  bash_aliases.sh*
  bash_login.sh*
  bash_logout.sh*
  bashrc.sh*
  gitconfig.ini
  install.sh*
  README.md
  vimrc.vim
```

I want to remove the `*` and `/` from the end of the file/directory name

**Comment by PavlenkoV** [comment]
I am not able to find and set option **NERDTreeShowExecutableFlag**

**Comment by rzvxa** [comment]
There is no such option as `NERDTreeShowExecutableFlag` and it is not planned to be anytime soon.
