### ISSUE TITLE
Can't install Nerdtree, it shows: Plugclean required

### ISSUE THREAD

**Issue by Gummy0reo** [preservim/nerdtree#1315]
I tried to install the plugin, but it doesn;t seem to be working, it says plugclean required, can someone please help me with this please~

thank you!!
![Screenshot_2022-07-16_04-24-19](https://user-images.githubusercontent.com/103487514/179287378-9549e1cb-ff31-470c-939c-eb58f4b54755.png)
![Screenshot_2022-07-16_04-24-35](https://user-images.githubusercontent.com/103487514/179287381-0d1bcac8-0299-444a-a104-0ce59e6e5a56.png)

**Comment by godalming123** [comment]
have you tried running `:PlugClean` it uninstalls plugins if they are not in your config file you just have to type y and hit enter to remove them after running the command

**Comment by Gummy0reo** [comment]
> have you tried running `:PlugClean` it uninstalls plugins if they are not in your config file you just have to type y and hit enter to remove them after running the :PlugClean command you should then be able to run :PlugInstall

OMG this works perfectly, thank you so much!!!
