### ISSUE TITLE
Disable cursor on window

### ISSUE THREAD

**Issue by godalming123** [preservim/nerdtree#1316]
#### State Your Question

Is there a way to disable the cursor in my nerdtree window. Since what column is focused does not matter there is no need to have the cursor visible when you can see the focused line because of the line highlight on 24bit color.

**Comment by weebcyberpunk** [comment]
If you're on Neovim, you can try setting an autocmd to change the guicursor when entering nerdtree buffer and another one to reset guicursor to default when leaving it.

Something like:
```
augroup NERDTreeCursor
    autocmd BufEnter NERD_tree* set guicursor='your cursor opts for nerdtree'
    autocmd BufLeave NERD_tree* set guicursor='n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20'
augroup END
```

**Comment by godalming123** [comment]
That helps but I could not find a way to hide the cursor in https://github.com/neovim/neovim/issues/3688

**Comment by weebcyberpunk** [comment]
As far as I know, guicursor opts are the only way to change cursor appearance, so if is impossible to hide it completely on guicursor, it's impossible on Neovim…

**Comment by godalming123** [comment]
You can change cursor color but there is no opacity option
```
highlight Cursor guifg=white guibg=black
``

**Comment by godalming123** [comment]
It works with:
```
highlight! Cursor guibg=#ffffff guifg=#000000
set guicursor=n-v:block-Cursor

augroup NERDTreeCursor
				autocmd BufLeave NERD_tree* hi Cursor blend=0
				autocmd BufEnter NERD_tree* hi Cursor blend=100
```
The only problem if that ounce you enter nerd tree if you type a command your cursor is gone

**Comment by godalming123** [comment]
I'm trying to add this to other panels in neovim is there an easy command to see the name of a focused window so I can do this

**Comment by weebcyberpunk** [comment]
You need the name of the buffer and not the window. I don't know any command, but there's a VimScript function bufname()

The placeholder '%' is synonym to the current buffer, so you can do something like:

`execute 'echo' bufname('%')`

or with a variable:

`let bufname=bufname('%')`
`let bufname`

**Comment by weebcyberpunk** [comment]
Remember that some buffers can change their name on specific situations, so you maybe need to use a placeholder * just like the NERDTree_*

**Comment by godalming123** [comment]
Thanks

**Comment by weebcyberpunk** [comment]
You're welcome!
