### ISSUE TITLE
Display of nerdtree broken. When deleting lines, artifact appears in the nerdtree windows.

### ISSUE THREAD

**Issue by Rz-Rz** [preservim/nerdtree#1319]
#### Environment
- Operating System: Ubuntu 20.04
- Vim/Neovim version 0.7.2
- NERDTree version, found on first line of quickhelp `?`: 6.10.16
- Are you using any of these NERDTree-dependent plugins? No nerdtree dependent plugin.
- Provide a minimal **.vimrc** file that will reproduce the issue.
```
call plug#begin()
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.0' }
Plug 'preservim/nerdtree'
call plug#end()
" Telescope config
" Find files using Telescope command-line sugar.
nnoremap <silent>;f <cmd>Telescope find_files<cr>
nnoremap <silent>;g <cmd>Telescope live_grep<cr>
nnoremap <silent>;b <cmd>Telescope buffers<cr>
nnoremap <silent>;h <cmd>Telescope help_tags<cr>
" Nerdtree
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-n> :NERDTree<CR>
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
```

#### Steps to Reproduce the Issue
Open a nerdtree windows within a js file. Delete a few lines, they will glitch and appear stuck to the nerdtree side.

#### Current Behavior (Include screenshots where appropriate.)
![image](https://user-images.githubusercontent.com/52322219/184140843-3c7293ae-2c22-42a5-9ce5-1b1e7170efbf.png)

#### Expected Result
There should be not artifact within the nerdtree windows.

**Comment by rzvxa** [comment]
If I'm not mistaken this artifact is happening in older versions of Windows terminal, I used to experience similar issues. They have a new render engine called "Atlas", consider turning this option on even if your problem gets solved with the update, And maybe you can switch to the Windows terminal preview version as it proved to be stable enough and has some cutting-edge features.
Here is my attempt to recreate it with your config using WSL(which I think is your environment, or perhaps it's an SSH connection?)
![NVIDIA_Share_KB8E5QmtOR](https://github.com/preservim/nerdtree/assets/3788964/fee09c75-3bb9-4de7-9d3f-c3d555fb1acd)
