### ISSUE TITLE
How I can use control-j control-k to switch between windows?

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [preservim/nerdtree#1325]
How I can use control-j control-k to switch between windows? I am using nvim 0.7.2,ubuntu 22.04

**Comment by weebcyberpunk** [comment]
You mean switching between any window or only between a buffer window and the tree window?

**Comment by igbanam** [comment]
This is how I do mine. The tree window is a buffer, anyways.

https://github.com/igbanam/dotfiles/blob/release/vimrc#L167-L170

**Comment by weebcyberpunk** [comment]
I use that too, I only asked because maybe @Bogdan-Torkhov is asking for a keybind to change the focus exclusively between the tree and other buffers, treating the tree as a special window

**Comment by Bogdan-Torkhov** [comment]
> This is how I do mine. The tree window is a buffer, anyways.
> 
> https://github.com/igbanam/dotfiles/blob/release/vimrc#L167-L170

Thanks,that works
