### ISSUE TITLE
Refreshing 'R' the file list fails when a new file name matches an existing one with different case.

### ISSUE THREAD

**Issue by pacazo** [preservim/nerdtree#1329]
#### Environment
- Operating System: OpenSuse Tumbleweed
- Vim/Neovim version `:version`:  Vim 9.0 Patch 1-453
- NERDTree version, found on first line of quickhelp `?`: 6.10.16
- Are you using any of these NERDTree-dependent plugins?  
    - [ ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
"Empty vimrc file
```
Maybe related to Issue #1241
#### Steps to Reproduce the Issue
1. Create files 'test2.txt' and 'TEST.txt'
2. Start VIM and NerdTREE
3. Rename 'test2.txt' to 'test.txt' from outside vim
4. Press 'R' in Nerdtree to refresh the list of files.

#### Current Behavior (Include screenshots where appropriate.)

Two files with the same name 'TEST.txt' appear. Clicking any of the two opens 'TEST.txt'.
The file test.txt does not appear and cannot be opened from NerdTree

#### Expected Result
Both files 'TEST.txt' and 'test.txt' show up in the list of files.

**Comment by igbanam** [comment]
This may be an OS-specific problem. I am on Mac OS Ventura, Vim 9, and this seems to work perfectly.

`TEST.txt` and `Test.txt` are considered the same file.


https://user-images.githubusercontent.com/390059/201539188-5c1cf73c-d5c5-4678-b32e-1254ccb250ea.mov

**Comment by pacazo** [comment]
> This may be an OS-specific problem. I am on Mac OS Ventura, Vim 9, and this seems to work perfectly.
> 
> `TEST.txt` and `Test.txt` are considered the same file.
> Screen.Recording.2022-11-13.at.18.56.39.mov

NERDTree seems to be unable to recognize filename case, which is a different problem. Please try renaming the file outside of vim. I am updating the issue to reflect this point. Thank you.

**Comment by igbanam** [comment]
I still think this problem may be outside NERDTree; if at all.

<img width="720" alt="Screenshot 2022-11-14 at 09 43 59" src="https://user-images.githubusercontent.com/390059/201627585-afd55706-4951-4c63-93af-7654ff2759fc.png">

**Comment by pacazo** [comment]
> I still think this problem may be outside NERDTree; if at all.
What you have done in this reply is try to match against the git filename matcher. Git is designed to be portable, such that the git filename matcher will preserve case but match filenames whose only difference is case. Therefore, git will show test.txt and TEST.txt as the same file. Because of limitation in Microsoft filesystems.

**Comment by pacazo** [comment]
> I still think this problem may be outside NERDTree; if at all.
What you have done in this reply is try to match against the git filename matcher. Git is designed to be portable, such that the git filename matcher will preserve case but match filenames whose only difference is case. Therefore, git will show test.txt and TEST.txt as the same file. Because of limitation in Microsoft filesystems.
However the issue I opened has nothing to do with git.

**Comment by pacazo** [comment]
> I still think this problem may be outside NERDTree; if at all.


What you have done in this reply is try to match against the git filename matcher. Git is designed to be portable, such that the git filename matcher will preserve case but match filenames whose only difference is case. Therefore, git will show test.txt and TEST.txt as the same file. Because of limitation in Microsoft filesystems.
However the issue I opened has nothing to do with git.

**Comment by igbanam** [comment]
It has nothing to do with Git 🙂 

<img width="720" alt="tmux_new_-s_everything-everywhere" src="https://user-images.githubusercontent.com/390059/201653444-9ebdfd49-a294-4798-89e2-e691a2a101f2.png">

**Comment by igbanam** [comment]
Now we know it's a filesystem issue. Maybe NERDTree could look into handling Microsoft filesystems better? I don't know a good solution to this. But generally files should be unique on their non-case-sensitive names. Hopefully someone with a Windows machine can look into this. I may not be of much help since I don't have the right environment to reproduce this.

**Comment by pacazo** [comment]
Check that 'mv' is not an alias of 'git mv' in your machine. Unix systems(OSX, Linux, BSD, etc but not Windows) have case sensitive filenames.
