### ISSUE TITLE
Update to Neovim 0.8.0 causes E5248: Invalid character in group name

### ISSUE THREAD

**Issue by mcguiremw** [preservim/nerdtree#1331]
### Nerdtree settings in init.vim
" NERDTree
let NERDTreeShowHidden=1
" autocmd VimEnter * NERDTree | wincmd p
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let NERDTreeShowHidden=1
map <Leader>p :NERDTreeToggle<CR>
nmap <Leader>r :NERDTreeFocus<cr>R<c-w><c-p>
" No file
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" " Directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
" If another buffer tries to replace NERDTree, put it in the other window, and bring back NERDTree.
autocmd BufEnter * if bufname('#') =~ 'NERD_tree_\d\+' && bufname('%') !~ 'NERD_tree_\d\+' && winnr('$') > 1 |
    \ let buf=bufnr() | buffer# | execute "normal! \<C-W>w" | execute 'buffer'.buf | endif
let g:webdevicons_enabled_nerdtree = 1
let g:webdevicons_conceal_nerdtree_brackets = 1

### Neovim version
➜ nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.0/share/nvim"

### Health Check
Run :checkhealth for more info

mkdp: health#mkdp#check
========================================================================
  - INFO: Platform: macos
  - INFO: Nvim Version: NVIM v0.8.0
  - INFO: Pre build: /Users/me/.config/nvim/plugged/markdown-preview.nvim/app/bin/markdown-preview-macos
  - INFO: Pre build version: 0.0.10
  - OK: Using pre build

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color

### Screen Grab
[![Watch the video](https://github.com/mcguiremw/issues_media/blob/main/nerdtree_thumb.png)](https://github.com/mcguiremw/issues_media/blob/main/nerdtree_error.gif)

**Comment by Brageanth** [comment]
Same here

**Comment by caiwenhn2008** [comment]
+1

**Comment by Railly** [comment]
+1

**Comment by arh78750** [comment]
I was having the same issue but I am not sure this is an issue with nerdtree itsself, I also had `tiagofumo/vim-nerdtree-syntax-highlight` enabled and disabling that plugin seemed to make the error go away

**Comment by Griiid** [comment]
> I was having the same issue but I am not sure this is an issue with nerdtree itsself, I also had `tiagofumo/vim-nerdtree-syntax-highlight` enabled and disabling that plugin seemed to make the error go away

Cool, same here, the error go away after disabling `tiagofumo/vim-nerdtree-syntax-highlight`
