### ISSUE TITLE
Sugestion: add help for change between tabs, windows, 

### ISSUE THREAD

**Issue by jazei-AR** [preservim/nerdtree#1334]
I don't know how change between windows,  I mean I don't know how to go back to nerdtree tree window.... maybe if you put in help this I will learn how.
thank you

**Comment by imLew** [comment]
The nerdtree window is just a regular window so you can navigate to it the way you would to any other window. I think the default mapping to move to an adjacent buffer is `<C-w>x` where `x` is one of `h,j,k,l`.
Alternatively you can just hit your nerdtree toggle twice.

As this seems to be a matter related to vim and not to nerdtree I don't think it warrants a in nerdtree.
