### ISSUE TITLE
how to reload bookmark?

### ISSUE THREAD

**Issue by pinggit** [preservim/nerdtree#1335]
I found no way to reload the bookmark except restart vim.
this is easy to reproduce.

* bookmark a file
* remove the file (bookmark not updated)
* add the file back(bookmark not updated)

the bookmark info is not "lost" since it's in ~/.NERDTreeBookmarks
but currently it looks `R` does not reload the bookmark.
this is really annoying when switching branches in git environment where certain files only exist in certain branch.
can this be fixed/enhanced?

**Comment by sihunqu123** [comment]
How about trying `:RevealBookmark` in the NERDTree panel to reload.

**Comment by rzvxa** [comment]
You should use `:ReadBookmarks` in the NERDTree window
