### ISSUE TITLE
Opening tabs

### ISSUE THREAD

**Issue by jtmr05** [preservim/nerdtree#1338]
#### Description

When opening a new tab with `T`, the cursor moves to the top of screen. That's a bit annoying and counter productive. It would be better if it stayed on the same line.

**Comment by imLew** [comment]
What exactly do you mean by the same line?
If you want the cursor to be on the same line that it was on when you last viewed the file you can use the [vim-stay plugin](https://github.com/zhimsel/vim-stay).

**Comment by jtmr05** [comment]
On the NERDTree panel. If you navigate to a certain a file and then open it in a tab, the cursor jumps to the top of the panel.

**Comment by imLew** [comment]
What version of vim and nerdtree are you using?
I'm on neovim 0.8.1 and nerdtree 6.10.16 and when I use nerdtree to open a file in a tab with `T` or `t` the cursor stays on the file (resp. is on the file if navigate back to the tab in which I used nerdtree).

**Comment by jtmr05** [comment]
`$ vim --version`
`VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec 11 2022 13:50:40)`
`Included patches: 1-1046`
`Compiled by Arch Linux`

I'm running the most recent version of the plugin as well.

**Comment by imLew** [comment]
When I use that version I get a different problem (it actually fills the command line with `:call nerdtree#ui_glue#invokeKeyMap("T")<cr>` instead of executing that), but once the new tab is opened the cursor stays in its position.

**Comment by rzvxa** [comment]
@jtmr05 
Hello, Sorry for the late reply.
You can use this snippet in your .vimrc / init.vim file
```vim
" Open the existing NERDTree on each new tab.
autocmd BufWinEnter * if &buftype != 'quickfix' && getcmdwintype() == '' | silent NERDTreeMirror | endif
```
NERDTree by default assigns a new tree to each tab, With the use of this snippet you actually mirror the current NERDTree instead of creating a new one on each tab.

**Comment by jtmr05** [comment]
been a while since I used NERDtree but thanks for the input

**Comment by rzvxa** [comment]
I'm happy to help, NerdTree was a little bit unmaintained in the last 2 years and I'm just trying to plow into the backlog of issues to solve/close as many as possible and only keep the bugs/feature requests open until we get PRs out for them.
