### ISSUE TITLE
`o` keybind does not work as documented

### ISSUE THREAD

**Issue by roy-work** [preservim/nerdtree#1340]
#### Self-Diagnosis
Before creating an issue, take some time to search these resources for an answer. It's possible that someone else has already seen and solved your issue.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### Environment
- Operating System: macOS
- Vim/Neovim version `:version`: `VIM`, `9.0`
- NERDTree version, found on first line of quickhelp `?`: (I'm not understanding the question fully.) Running `master`, `fc85a6f07c2cd694be93496ffad75be126240068`
- Are you using any of these NERDTree-dependent plugins?  
    - [ ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):

  (An affirmative "No", to all / I have none of these installed.)
- Provide a minimal **.vimrc** file that will reproduce the issue.
  ```vim
  set runtimepath+=~/.vim/bundle/nerdtree
  ```
  (Where that directory is a `git clone` of this repository.)

#### Steps to Reproduce the Issue
1. I press `:e .` to edit a directory; NERDTree opens.
2. I highlight a file that is open in another tab.
3. I press `o`; the tab is switched to the open file, instead of opening it on the current tab.

#### Expected Result
The current NERDTRee is replaced with the file, as if `:e <selected file>` had been run. I.e., [as the docs state](https://github.com/preservim/nerdtree/blob/fc85a6f07c2cd694be93496ffad75be126240068/doc/NERDTree.txt#L902-L915),

> 'o' will open the selected file in the same window as the tree, replacing it.

(I went looking for this after I grew tired of the behavior of `<Enter>` — switching to an already open window is, to me, disruptive: I am opening the file here, as it is related to the mental context represented by this tab. That another tab has it open is coincidental.)

**Comment by rzvxa** [comment]
I'm going to close this issue since I'm pretty sure this option solves your problem.
Feel free to reopen it if you have any further questions.
