### ISSUE TITLE
E492: Not an editor command: NERDTree in vim9.0 

### ISSUE THREAD

**Issue by x-xiny** [preservim/nerdtree#1342]
你好 我在vim9.0版本上安装一直不成功，一直报这个错误 E492: Not an editor command: NERDTree请问怎么解决呀，我已经把代码clone 到了 ~/.vim/pack/vendor/start/nerdtree目录下了

**Comment by rzvxa** [comment]
It probably has to do with your config.
I'm going to close this issue, feel free to reopen it if you have any further questions.
