### ISSUE TITLE
NERDTreeCopyPath printing path instead of copying path on ubuntu

### ISSUE THREAD

**Issue by hwijeen** [preservim/nerdtree#1350]
Before creating an issue, take some time to search these resources. It's possible that someone else has already asked your question and gotten an answer.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resource: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### State Your Question
I use the following to use `yy` to copy the path of a file from NERDTree. It works fine on my MacBook but it won't copy but print the path on ubuntu. Why is it the case? Is it possible to copy into the clipboard on ubuntu?
```
  autocmd VimEnter * call NERDTreeAddKeyMap({
      ┆   \ 'key': 'yy',
      ┆   \ 'callback': 'NERDTreeCopyPath',
      ┆   \ 'quickhelpText': 'put full path of current node into the default register' })
```

**Comment by rzvxa** [comment]
@hwijeen You have a version of Vim installed without the clipboard feature. If you are on Ubuntu you can install either `gvim` or `vim-gtk3` if you want to have a full feature build of vim.
write `:version` in the vim or use `vim --version` in the terminal to find out about features that are enabled in your vim build.
You can also obviously rebuild Vim for yourself with +clipboard but I personally advise you to keep a full-featured Vim upstream in your package manager so you get seamless updates without the need for rebuilds by yourself
