### ISSUE TITLE
define a custom command in NERDTree

### ISSUE THREAD

**Issue by trevoravant** [preservim/nerdtree#1356]
#### Description

Is it possible to define a custom command in NERDTree? For example, when I have a Python file highlighted, I would like to use NERDTree to apply a Vim command to manipulate to that file. I'm guessing this would most likely be done via the NERDTree menu, so I would define a command "x" in the menu, and then just type "mx" to apply my command to a file.

*Note*: What I want to do is similar to [this issue](https://github.com/preservim/nerdtree/issues/1211), but my goal is a little different.

**Comment by rzvxa** [comment]
Maybe something like this can help you in your journey.

```
function! ShortcutCallback ()
  let l:currentDirNode = g:NERDTreeDirNode.GetSelected()
  let l:currentNode = g:NERDTreeFileNode.GetSelected()
  echomsg l:currentDirNode.path.str()
  echomsg l:currentNode.path.str()
endfunction

autocmd VimEnter * call NERDTreeAddMenuItem({'text': '(t)test menu item', 'shortcut': 't', 'callback': 'ShortcutCallback'})
```

**Comment by trevoravant** [comment]
@rzvxa This is awesome, thank you.

**Comment by rzvxa** [comment]
@trevoravant I'm glad that snippet of code were useful to you, I don't have access to close this issue, If you found your issue resolved, close this. Otherwise go ahead and ask your subsequent questions.
