### ISSUE TITLE
remote authentication required but no callback set

### ISSUE THREAD

**Issue by EricEWeir** [preservim/nerdtree#1368]
Noncoder vim user here. Attempting to install nerdtree just now I got this error message: “remote authentication required but no callback set.” 

I’ve searched the web for help. What came up was folks looking for help in very specific coding contexts which are way over my head.

Hoping for help in my specific context.

Thanks

**Comment by rzvxa** [comment]
Hey mate, what is your OS? and how do you manage your plugins?
I suspect it's from git, have you authenticated git on your machine? I suggest you download the GitHub `gh` command line tool and write this in your terminal `gh auth login`.
It's the easiest way to setup your profile in git.
I'm going to close this issue, feel free if you have any further questions.

**Comment by EricEWeir** [comment]
﻿On Oct 24, 2023, at 2:09 PM, Ali Rezvani ***@***.***> wrote:﻿Hey mate, what is your OS? and how do you manage your plugins?
I suspect it's from git, have you authenticated git on your machine? I suggest you download the GitHub gh command line tool and write this in your terminal gh auth login.
It's the easiest way to setup your profile in git.
I'm going to close this issue, feel free if you have any further questions.Thanks much. My OS is macOS. With Macvim I manage plugins with vim-plug. But I encountered this problem using the amazing ivim porting of vim for iOS/iPadOS. Amazing in particular for the ways it gets around Apple’s sandboxing of iOS/iPadOS apps.As I may have mentioned in my post of of the issue I am a non-coding vim user using it for writing. I have never used vim from terminal. I have a GitHub account of course, but my only use to date has been to post issues with plugin.I understand there are ways GitHub could be useful even to a non-coding writer. I will explore it.----------------------------------------Eric WeirDecatur, GA ***@***.***"It has all been combustion.”- W.G.  Sebald

**Comment by rzvxa** [comment]
I understand, as far as I can tell this error is from git and vim-plug uses git to download your plugins from GitHub so that's why I suggested trying to authenticate your git command. It can also be that you have misspelled something in your vim-plug config.
I would like to ask that you send me the minimal vim config file that can reproduce this error.
To be honest it can be a configuration error or anything else but it's not from NERDTree.
