### ISSUE TITLE
Issue #1368 remote authentication required….

### ISSUE THREAD

**Issue by EricEWeir** [preservim/nerdtree#1385]
> I understand, as far as I can tell this error is from git and vim-plug uses git to download your plugins from GitHub so that's why I suggested trying to authenticate your git command. It can also be that you have misspelled something in your vim-plug config.
> I would like to ask that you send me the minimal vim config file that can reproduce this error.
> To be honest it can be a configuration error or anything else but it's not from NERDTree.

First, I appreciate your responding and then following up to my response.

Second,I just tried installing `NERDtree` using `ivim`’s `iplug` plugin manager. Installation went through without a hitch.

At the time I encountered the message I also encountered it trying to install `fern`. I continued to get it in several attempts over a couple weeks. Then all of a sudden it went through. 

Subsequently I encountered the message trying to install a plugin to `fern`. A couple weeks down the road I noticed that where the plugin used a `.` I had used a `-`. When I changed the spelling of the plugin’s name installation went through without a hitch.

I suspect that the problem all along, with `fern` and `NERDtree`, was simple misspelling on my part. 

For future reference, given the use of git i have described, should learn what it means to “authenticate” a git command?

**Comment by rzvxa** [comment]
Hey Eric,
The authentication part shouldn't be a problem if it is from the misspelling. Git with that error basically says it can't access the URL so it thinks it doesn't have enough access to view it.
In case you find yourself in a situation that needs git authentication to access a private plugin or something like that it usually asks for your username and password on the first try but if it doesn't you can always authenticate via your Operating System Login mechanism, For example, if you are on Windows you use `Windows Credential Manager` and `Apple KeyChain` on macOS, there is also an SSH authentication which may be a little bit confusing right now so I won't go into its details.
GitHub has 2 tools for easing this process for users [GitHub cli](https://cli.github.com/) and [GitHub Desktop](https://desktop.github.com/) but to be honest you don't need any of them as long as you keep using a plugin manager for that.

**Comment by rzvxa** [comment]
I'll send you a few reference links for doing the authentication part, But in short, you shouldn't need it. Your plugin manager should be able to download every plugin since they are all public, You only need authentication to access private git projects

https://git-scm.com/docs/gitcredentials
https://stackoverflow.com/questions/56573522/how-can-i-login-to-git
