### ISSUE TITLE
E1208: -complete used without allowing arguments

### ISSUE THREAD

**Issue by az-z** [preservim/nerdtree#1398]
#### Environment
- Operating System: Fedora release 37 (Thirty Seven) 
- Vim/Neovim version `:version`: 
`
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 22 2023 00:00:00)
Included patches: 1-2120
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby/dyn          +wildignore
+cursorbind        +lua/dyn           +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             -sound             +xattr
-dnd               -mouseshape        +spell             -xfontset
-ebcdic            +mouse_dec         +startuptime       -xim
+emacs_tags        +mouse_gpm         +statusline        -xpm
+eval              -mouse_jsbterm     -sun_workshop      -xsmp
+ex_extra          +mouse_netterm     +syntax            -xterm_clipboard
+extra_search      +mouse_sgr         +tag_binary        -xterm_save
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -DSYS_VIMRC_FILE=/etc/vimrc -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes -L/usr/local/lib -o vim -lm -lselinux -lncurses -lsodium -lacl -lattr -lgpm
`
- NERDTree version, found on first line of quickhelp `?`:  7.1.0
- Are you using any of these NERDTree-dependent plugins?  
    - [x] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [x] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [x] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [x] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
" Install Nerd font e.g.:
"https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/IBMPlexMono.zip
" into ~/.local/share/fonts
" Instal Plug: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

set nocompatible
set number
set relativenumber
set termguicolors
call plug#begin()
Plug 'vim/colorschemes'
Plug 'preservim/NERDTree' |
	\ Plug 'Xuyuanp/nerdtree-git-plugin' |
	\ Plug 'tiagofumo/vim-nerdtree-syntax-highlight' |
	" \ Plug 'scrooloose/nerdtree-project-plugin' | 
	" \ Plug 'PhilRunninger/nerdtree-buffer-ops' | not compatible with git
	" and devicons
	\ Plug 'PhilRunninger/nerdtree-visual-selection' 
Plug 'ryanoasis/vim-devicons'
Plug 'vim-airline/vim-airline'
call plug#end()

autocmd VimEnter * NERDTree | wincmd p
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

source ~/.vim/NERDTree.vim
```

#### Steps to Reproduce the Issue
1. Remove the comment from line 	\ Plug 'scrooloose/nerdtree-project-plugin' | 

#### Current Behavior (Include screenshots where appropriate.)
vim ~/.vimrc 
Error detected while processing /home/az/.vim/plugged/NERDTree/plugin/NERD_tree.vim[234]..function nerdtree#postSourceActions[5]..script /home/az/.vim/plugged/nerdtree-project-plugin/nerdtree_plugin/project.vim:
line   45: E1208: -complete used without allowing argumentsPress ENTER or type command to continue
#### Expected Result
it should not throw the error.

Filing as directed by @rzvxa in #1051 

Thank you.
AZ

**Comment by rzvxa** [comment]
Hey @az-z, Thanks for filing this issue!

I've allocated some time toward tracing this bug, `nerdtree-project-plugin` is almost 10 years old at this point so there might be some incompatibility issue that we have introduced over the years and went unnoticed because of the low user base of the said plugin.

But fortunately, there is already a PR for this problem on the `nerdtree-project-plugin` which hasn't merged yet(it is from 2021), Can you use this version instead and report the result?
[View PR](https://github.com/scrooloose/nerdtree-project-plugin/pull/2)
[View Fork](https://github.com/DehanLUO/nerdtree-project-plugin)

**Comment by rzvxa** [comment]
I'll close this issue since the problem originates from one of Nerdtree's plugins and doesn't have to do with Nerdtree itself. But I strongly believe that the fork mentioned above would fix the problem.
Feel free to reopen this issue or create a new one if there are any other problems even with this plugin excluded from your config.
