### ISSUE TITLE
highlight the current filename in the tree window after following a tag

### ISSUE THREAD

**Issue by lijh8** [preservim/nerdtree#1407]
#### Self-Diagnosis
Before creating an issue, take some time to search these resources for an answer. It's possible that someone else has already seen and solved your issue.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### Environment
- Operating System: macOS 12.7.3 (21H1015)
- Vim/Neovim version `:version`: VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct 27 2023 01:00:56)
- NERDTree version, found on first line of quickhelp `?`: NERDTree (7.1.1) 
- Are you using any of these NERDTree-dependent plugins?  
    - [ ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [x] Others (specify): https://github.com/ludovicchabant/vim-gutentags , https://github.com/preservim/tagbar , 
- Provide a minimal **.vimrc** file that will reproduce the issue.
```vim
$ cat .vimrc 
set autoindent
set expandtab
set hlsearch
set incsearch
set noerrorbells
set novisualbell
set nowrapscan
set number
set shiftwidth=4
set t_vb=
set tabstop=4
set updatetime=200
filetype on
syntax off

" NERDTree
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif
autocmd VimEnter * NERDTree
let g:NERDTreeNodeDelimiter = "\u00a0"
nnoremap <C-n> :NERDTreeToggle<CR>

" tagbar
let g:tagbar_sort = 0
nmap <F8> :TagbarToggle<CR>

" gutentags: ctags: Ctrl-], Ctrl-t
" mkdir ~/project_root_dir/.git
let g:gutentags_add_default_project_roots = 1

$ 
```

#### Steps to Reproduce the Issue

Hi, if I follow a tag and open the file containing that tag (could be in different directory),
the nerdtree does not sync and highlight the new filename entry in its window.
It is supported and can I configure that? thanks!

#### Current Behavior (Include screenshots where appropriate.)

![Screen Shot 2024-02-06 at 14 32 58](https://github.com/preservim/nerdtree/assets/9011764/d09490ff-8bf4-4219-80c0-39d197bdfe27)

![Screen Shot 2024-02-06 at 14 33 05](https://github.com/preservim/nerdtree/assets/9011764/59518045-3786-427a-8db6-e5fbebdbea3e)

**Comment by rzvxa** [comment]
Hi,

Unfortunately, it is not possible in NERDTree, The tree is intended to keep its state when you leave it and is not bound to the active buffer/window. However, it is possible to find and select the current file in the tree using the `:NERDTreeFind` command.
