### ISSUE TITLE
NERDTree.TreeNotOpen thrown when opening Neovim into NERDTree

### ISSUE THREAD

**Issue by sjshuck** [preservim/nerdtree#1408]
First reported as a comment to #1347 and moved here per @rzvxa.

> I don't know when it started happening (it was a few weeks ago I feel), or whether it's the same issue, but I am getting a similar error. When I launch directly into NERDTree with `nvim .` and then open a file with `s`, it produces this error:
>
> ```
> Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..76[18]..75[3]..<SNR>29_openVSplit[1]..105[1]..121[3]..177[6]..178[9]..172[3]..176[16]..218[1]..228[2]..function nerdtre
> e#ui_glue#invokeKeyMap[1]..76[18]..75[3]..<SNR>29_openVSplit[1]..105[1]..121[3]..177[6]..178[9]..172[3]..176[16]..218[1]..228:
> line    2:
> E605: Exception not caught: NERDTree.TreeNotOpen
> ```
> Note that this only errors with `s`, not with `i`, and only when launching directly into `nvim .`, not when explicitly firing up NERDTree after Neovim via `nvim -c ':NERDTree'`.
> 
> * Linux
> * Konsole 23.08.4
> * NVIM v0.9.5
> * [This init.lua](https://github.com/sjshuck/dotfiles/blob/bfbd19b2fcb541e97fff665958cd4c10f2c04d68/init.lua)
> * NERDTree commit https://github.com/preservim/nerdtree/commit/60b5e602e95384e6f6d5ba47975b4903c12e2c59
>
> I have also observed this on a Mac

**Comment by rzvxa** [comment]
I found the issue and created a merge request for it, Give it a spin and let me know if that resolves your issue completely or it still persists.

**Comment by rzvxa** [comment]
That's great! I've merged the PR and now you can update to the latest commit on the master branch.
Thanks again for reporting the issue, And I'm sorry for this inconvenience.

**Comment by sjshuck** [comment]
> sorry for this inconvenience

Are you kidding?  This is the most convenience I've ever experienced in the open source world.
