### ISSUE TITLE
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..96[18]..95[3]..<SNR>185_openHSplit[1]..125[1]..141[3]..197[6]..198[17]..33:

### ISSUE THREAD

**Issue by JESii** [preservim/nerdtree#1413]
#### Self-Diagnosis
Before creating an issue, take some time to search these resources for an answer. It's possible that someone else has already seen and solved your issue.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.
- I reviewed https://github.com/preservim/nerdtree/issues/1347 and https://github.com/preservim/nerdtree/issues/1408
As you said, they are simillar up to the `invokeKeyMap` but then different in the details.

#### Environment
- Operating System: MacOS Sonoma v14.4
- Vim/Neovim version `:version`: vim: 9.1.0250; nvim: v0.9.5
- NERDTree version, found on first line of quickhelp `?`: 7.1.2
- Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
- Are you using any of these NERDTree-dependent plugins?  
    - [xx ] [Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)
    - [ ] [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)
    - [ ] [tiagofumo/vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight)
    - [ ] [scrooloose/nerdtree-project-plugin](https://github.com/scrooloose/nerdtree-project-plugin)
    - [ ] [PhilRunninger/nerdtree-buffer-ops](https://github.com/PhilRunninger/nerdtree-buffer-ops)
    - [ ] [PhilRunninger/nerdtree-visual-selection](https://github.com/PhilRunninger/nerdtree-visual-selection)
    - [ ] [jistr/vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs)
    - [ ] Others (specify):
- Provide a minimal **.vimrc** file that will reproduce the issue.
Sorry... I deleted a bunch of stuff, and trimmed down all the plugins to the absolute minimum. Error still occurs here as described below. If you want really MINIMAL, I'll work on that
[vimrc_MINIMAL.txt](https://github.com/preservim/nerdtree/files/14878073/vimrc_MINIMAL.txt)

#### Steps to Reproduce the Issue
1. Open a new vim with nerdtree
2. move down to a text file in the list
3. press 'i' to start editing the file

#### Current Behavior (Include screenshots where appropriate.)
Throws the error
```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..96[18]..95[3]..<SNR>185_openHSplit[1]..125[1]..141[3]..197[6]..198[17]..33:
line    3:
E576: Error while reading ShaDa file: last entry specified that it occupies 48 bytes, but file ended earlier
```
and then continues. 
The error is not repeated if I close and re-open the same file, but if I try to open any other file with 'i' I get the error.
Opening a file with 's' also throws the error.
Here's a video

https://github.com/preservim/nerdtree/assets/486/46d5be6f-c46c-46fb-ae14-df58ed88a28f

Should quietly open the file.

**Comment by rzvxa** [comment]
Take a look at [this](https://github.com/neovim/neovim/issues/12101), It might resolve your issue.

**Comment by rzvxa** [comment]
I'm going to close this since I'm pretty sure it would resolve your issue, Feel free to reopen it at any time if it proved not to be the case.
