### ISSUE TITLE
provider: clipboard: missing required variable g:loaded_clipboard_provider

### ISSUE THREAD

**Issue by x41lakazam** [preservim/nerdtree#1418]
Reopening #1161.

I get the same error on Fedora 39

```
Error detected while processing ~/.config/nvim/plugged/nerdtree/plugin/NERD_tree.vim[235]..function nerdtree#postSourceActions[5]..script /.
~/.config/nvim/plugged/nerdtree/nerdtree_plugin/fs_menu.vim:
line   45:
provider: clipboard: missing required variable g:loaded_clipboard_provider
```

checkhealth provider reports:
```
- OK: Clipboard tool found: tmux
```

**Comment by rzvxa** [comment]
I don't think it has anything to do with NERDTree.
https://github.com/neovim/neovim/issues/11033
It is probably a neovim bug. At the very least I can't see any connection to the NERDTree.

I'll keep this issue open for a while in case there is some evidence that would prove it is indeed related to NERDTRee.
