### ISSUE TITLE
<c-j> <c-k> remaps not working

### ISSUE THREAD

**Issue by MatthewUng** [preservim/nerdtree#1424]
#### Self-Diagnosis
Before creating an issue, take some time to search these resources for an answer. It's possible that someone else has already seen and solved your issue.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resources: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### Environment
- Provide a minimal **.vimrc** file that will reproduce the issue.

I have the following in my vimrc that I frequently use for navigation.
```vim
nnoremap <c-j> <c-d>
nnoremap <c-k> <c-u>
vnoremap <c-j> <c-d>
vnoremap <c-k> <c-u>
```

#### Steps to Reproduce the Issue
1. Open nerdtree window
1. \<c-j> and \<c-k> do not work as intended based on my vimrc maps.

#### Current Behavior (Include screenshots where appropriate.)
\<c-j> and \<c-k> move up and down one line

#### Expected Result
\<c-j> and \<c-k> move up and down half a page

**Comment by rzvxa** [comment]
Both `<c-j>` and `<c-k>` already have their own behavior - moving up and down in a directory - You should remap them to something else first.
use `:help NERDTree-C-J` to open the help section for this specific mapping, And use `:help NERDTreeMappings` to open the list of all NERDTree mappings.

**Comment by MatthewUng** [comment]
This is perfect.
Thank you!
