### ISSUE TITLE
How to close input window?

### ISSUE THREAD

**Issue by CaiJinKen** [preservim/nerdtree#1425]
Before creating an issue, take some time to search these resources. It's possible that someone else has already asked your question and gotten an answer.
- [old NERDTree issues](https://github.com/preservim/nerdtree/issues?q=is%3Aissue)
- NERDTree documentation - `:h NERDTree`
- [NERDTree Wiki](https://github.com/preservim/nerdtree/wiki)
- Other resource: <https://stackoverflow.com>, <https://vi.stackexchange.com>, etc.

#### State Your Question
After i created some files with `ma` keymap, and the input window grows up and i have no way to close it. There is any way to fix this? If i set terminal to minimum and restore, the input window disappears, but i think nerdtree itself can refresh window automatic.

**Comment by rzvxa** [comment]
What is the exact version of your Vim? It should close with the press of the `Esc` key. It previously was a bug in the Vim9 maybe you are using an old version?
https://github.com/preservim/nerdtree/pull/1322

**Comment by CaiJinKen** [comment]
Thanks for replay.

**Comment by CaiJinKen** [comment]
Thanks for replay.

**Comment by CaiJinKen** [comment]
Thanks for replay. I use the latest version nerdtree and neo-vim info as follow:
➜  ~ nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
 brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

**Comment by CaiJinKen** [comment]
> What is the exact version of your Vim? It should close with the press of the `Esc` key. It previously was a bug in the Vim9 maybe you are using an old version? #1322

Thanks for replay. I use the latest version of nerdtree and neo-vim info as follow:
➜ ~ nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

**Comment by rzvxa** [comment]
I've tried to reproduce this issue to no avail. Is it possible for you to update your nvim to the latest stable version? A faulty version of nvim might be causing this problem(similar to the Vim9 issue).

**Comment by CaiJinKen** [comment]
> I've tried to reproduce this issue to no avail. Is it possible for you to update your nvim to the latest stable version? A faulty version of nvim might be causing this problem(similar to the Vim9 issue).

Thanks a lot. Everything works well after upgrade neovim & plugins.

**Comment by CaiJinKen** [comment]
> I've tried to reproduce this issue to no avail. Is it possible for you to update your nvim to the latest stable version? A faulty version of nvim might be causing this problem(similar to the Vim9 issue).

Thank you very much @rzvxa . Everything works well after upgrade neovim & plugins. This staps maybe useful to others:
bash:
```bash
# update all programs and dependencies
brew upgrade
```
in vim:
```vimrc
:checkhealth # maybe you should fix errors in result
:PluginUpdate
```
