### ISSUE TITLE
Re-open NerdTree in new tabs

### ISSUE THREAD

**Issue by nicknick63** [preservim/nerdtree#18]
I would NerdTree to be re-opened when we open a file in a new tab.
I'm using a little hack found here : http://stackoverflow.com/questions/1979520/auto-open-nerdtree-in-every-tab but I think it's a feature which a lot of people want so why don't make it possible enabling an option ?

P.S. : Sorry for my English but i'm French…

**Comment by ianwalter** [comment]
`vim-nerdtree-tabs` is no longer maintained but this setting seems to work:
```vim
autocmd BufWinEnter * NERDTreeMirror
```
From: https://stackoverflow.com/a/2762067/894420
