### ISSUE TITLE
Relase control of "?" to vim's reverse search

### ISSUE THREAD

**Issue by jgandt** [preservim/nerdtree#214]
I constantly use search in nerd tree to find a directory or file that I know exists in the current tree.

Unfortunately, many times the thing I am looking for is above me in the tree. so instead of /<search> - <CR> N I really just want to ?<search> - <CR>

however the nerd tree help intercepts the ?

It is extrodinarily annoying. Potentially enough so to drop the pluggin.

**Comment by skatenerd** [comment]
This just made my day.  Thanks for resolving this issue in a public, googleable fashion.
