### ISSUE TITLE
Nerdtree causes internal Vim error: E315 ml_get: invalid lnum

### ISSUE THREAD

**Issue by jdavis** [preservim/nerdtree#279]
Here's a screenshot of the error that I'm getting:

![Nerdtree error](http://i.imgur.com/1pPFQEK.png)

It only happens when I'm in Visual line select and use J/K to increase/decrease the size of the selection. This will pop up and make Vim spaz out.

After the spazzing, NERDTree will then lose all of its coloring.

**Comment by firedev** [comment]
I do have it now, when I try to drag the Nerdtree window.
![image](https://cloud.githubusercontent.com/assets/115612/7854631/694f45bc-0545-11e5-8657-bd64a151c9fa.png)

**Comment by firedev** [comment]
Fixed it by adding `set ttymouse=xterm2`
