### ISSUE TITLE
Highlight current buffer

### ISSUE THREAD

**Issue by alkesh** [preservim/nerdtree#3]
Not an issue - more of a feature request.
Is it possible to have a command that highlights the currently open file in NERDTree?
A bit like the 'RevealBookmark' command, but it just uses the active buffer instead of a bookmark.

**Comment by vitaly-zdanevich** [comment]
By the link I see

> !!! THE CURRENT VERSION OF NERDTree ALREADY HAS THIS FEATURE !!! 

How to enable this?
