### ISSUE TITLE
Opening and closing NERDTree causes gVim to become unsnapped in Windows 7/8

### ISSUE THREAD

**Issue by nfriend** [preservim/nerdtree#350]
I have a fairly large main monitor, and often work on two files simultaneously by snapping one to the left side of the screen and one to the right.  When I toggle NERDTree's visibility, the width of the gVim window changes, causing my entire gVim window to become unsnapped and change positions.  This doesn't happen when gVim is maximized (snapped to the top of the screen).

From what I can tell, the extra width is coming from the vertical scrollbar that NERDTree adds when it opens.

The various fixes I've found online don't seem to prevent this issue (the most popular being the `set winfixwidth` option).

**Comment by lethargi** [comment]
[This](https://superuser.com/questions/792385/plugins-cause-gvim-window-to-move-become-unsnapped-in-windows) answer in superuser stackexchange fixes this problem for me

**Comment by PhilRunninger** [comment]
Yes, that is the solution, but it may be incomplete, and as of **vim 8**, the answers in #513 and #659 may be too. Make sure you remove `R`, `r`, `L`, and `l` from `'guioptions'`. The complete answer is:
```
set guioptions-=R
set guioptions-=r
set guioptions-=L
set guioptions-=r
```
See `:help 'guioptions'` for more information.
