### ISSUE TITLE
NERDTree  conflicts with vim command bd

### ISSUE THREAD

**Issue by chaos-dd** [preservim/nerdtree#400]
Recently I seem to find a bug of NERDTree.
Here is steps to regenerate the bug.
Open Vim, toggle NERDTree , open more than two file through NERDTree, and than try to close one of  the opened file using command bd, the vim exits ! Not only close an opened file.

**Comment by bleached** [comment]
May I ask why this got closed? I have the same issue. When I have NERDTree opened, and issue :bd in another window, bd will close all buffers instead of just one, and vim will exit because I have chosen so (to quit vim if NERDTree is only window left).
If I issue bd with NERDTree closed, only the currently viewed buffer gets deleted, which is what I expect.

**Comment by darrynten** [comment]
:+1:

**Comment by Treri** [comment]
same problem, can anyone to fix?

**Comment by Treri** [comment]
@bleached @darrynten I have the same problem, and i find a solution on StackOverflow

http://stackoverflow.com/questions/1864394/vim-and-nerd-tree-closing-a-buffer-properly

**Comment by ecthiender** [comment]
@chaos-dd why did you close the issue? Did you find any fix? If yes, then please share. I'm also having the same problem.

**Comment by Treri** [comment]
@ecthiender you can have a try the answer I found on StackOverflow. I used long times and it works as expected.

**Comment by yifanchen** [comment]
I have the same problem.

**Comment by jdhao** [comment]
After long experiment and search ,finally find this post. For later comers, you can use this mapping in your vim/Nvim config:

```
nnoremap \d :bp<cr>:bd #<cr>
```

Simple, but it works well.

**Comment by s3cret** [comment]
> After long experiment and search ,finally find this post. For later comers, you can use this mapping in your vim/Nvim config:
> 
> ```
> nnoremap \d :bp<cr>:bd #<cr>
> ```
> Simple, but it works well.

Sorry, I did not see your comment.
I made a comment below yours and exactly the same as yours.
My bad.

**Comment by arbkm22** [comment]
> After long experiment and search ,finally find this post. For later comers, you can use this mapping in your vim/Nvim config:
> 
> ```
> nnoremap \d :bp<cr>:bd #<cr>
> ```
> 
> Simple, but it works well.

why doesn't this works for me?

**Comment by nhejazi** [comment]
I'm also having trouble getting the above solution to work
