### ISSUE TITLE
NERDTreeHijackNetrw ignored when using Default Key: e

### ISSUE THREAD

**Issue by LeighBicknell** [preservim/nerdtree#402]
Docs state:

```
Default key: e
Map option: NERDTreeMapOpenExpl
Applies to: files and directories.

|:edit|s the selected directory, or the selected file's directory. This could
result in a NERD tree or a netrw being opened, depending on
|'NERDTreeHijackNetrw'|.
```

But even with NERDTreeHijackNetrw set to 0, pressing 'e' on a directory still opens the directory in a 'secondary' NERDTree.

**Comment by felquis** [comment]
It is used here:

https://github.com/MarcoWorms/vimfiles/blob/06fc8a4438a361630c8a1d78f7e77ee06dc33991/init.vim#L138-L140

**Comment by lifecrisis** [comment]
This bug has been confirmed.  Also, I'm noting that the documentation here is wrong.  The `e` mapping does not currently operate properly on file nodes.
