### ISSUE TITLE
NERD-tree does not trigger WinEnter

### ISSUE THREAD

**Issue by molok** [preservim/nerdtree#59]
For some reason when I open a file from NERD-tree, the WinEnter autocommands are not triggered. This can be checked with

au WinEnter \* echo "entering"

and then opening a file from NERD-tree.
I think this is a bug, I know it breaks some of my stuff.

**Comment by jordwalke** [comment]
This is making it very difficult for me to properly implement [VimSplitBalancer](https://github.com/jordwalke/VimSplitBalancer/blob/master/plugin/VimSplitBalancer.vim).

The autocommands don't execute when opening the NERDTree, so I cannot possibly resize it in the `WinEnter` command.
