### ISSUE TITLE
Hide executables on linux

### ISSUE THREAD

**Issue by drewm1980** [preservim/nerdtree#62]
This is a feature request:

Add some facility for hiding executables from the tree.  On windows one can use a file filter on .exe, but on Linux, programs generally have no extension.  Executable shell scripts should remain visible.

Thanks!

**Comment by schickling** [comment]
This seems to be no longer supported. What's the current way to do this @scrooloose ?

**Comment by PhilRunninger** [comment]
@schickling , see `:h NERDTreeAddPathFilter`. This function lets you specify your own callback function for complex filtering needs.
