### ISSUE TITLE
Interaction with autocomplete

### ISSUE THREAD

**Issue by mishaszu** [preservim/nerdtree#989]
### Environment
* Operating System: `Ubuntu 18.04.2 LTS`, `MacOS 10.12`, `Termux (Android 9)`
* Vim version: `VIM - Vi IMproved 8.1`
* NERDTree version : `3c06335`
### Process
* Install `ALE` syntax check https://github.com/w0rp/ale with vim plug
* Install `YouCompleteMe` https://github.com/Valloric/YouCompleteMe
* Use colorcheme installed via `vim-plug`
* comment all plugins in `vim-plug`'s `begin` section expect `Nerdtree` & `ALE` or `YouCompleteMe` and choosen colorscheme
* Open a file with NERDTree
* Complete any code. It doesn't always leave marks after the same amount of steps. Usually, the buffer becomes dirty after 1-30 completions.

* NERDTree settings applied in vimrc:
    ```vim
    let g:NERDTreeWinPos = 'right'
    let g:NERDTreeWinSize=$NERDTREE_WIDTH
    let g:NERDTreeDirArrowExpandable = '▸'
    let g:NERDTreeDirArrowCollapsible = '▾'
    autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
    let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }
    ```
* [whole vim file](https://github.com/mishaszu/vim-rc/blob/master/vimrc)

### Current Result
![ale_bug_4](https://user-images.githubusercontent.com/11981362/56864798-1a2bd780-69c7-11e9-814c-71ccb115af2c.png)
* For `ALE` after 1-30 completions buffer becomes dirty in random places in whole width and height
* For `YouCompleteMe` dropdown leaves some results above existing code
* Autocompletion doesn't leave marks while `Nerdtree` is closed
* Closing `Nerdtree` doesn't clear marks
* Pressing `r` key in active `Nerdtree` used to clear buffer's marks
* Omni-completion doesn't leave marks.
* Default vim's colorscheme doesn't leave marks but installed by `vim-plug` does (e.g. https://github.com/sickill/vim-monokai, https://github.com/markvincze/panda-vim)

### Expected Result
Always clear buffer or way to clear it manually.

**Comment by mishaszu** [comment]
Just check for colors placed in `~/.vimrc/colors`. The same behavior. It should be replicable not only for `vim-plug`'s colorschemes.

**Comment by mishaszu** [comment]
I think it is the same for omnicompletion, but more likely to appear when 2 vsplits are open with NERDTree

**Comment by PhilRunninger** [comment]
I highly doubt this is an issue with NERDTree. If you issue the command `:redraw!` or press `<Ctrl-L>` does that fix things when the file becomes dirty? Try searching for related issues in the other plugins' repositories. This may have been reported there.

**Comment by PhilRunninger** [comment]
@mishaszu Any updates?

**Comment by gmg137** [comment]
I have the same problem and I look forward to solving it as soon as possible.

**Comment by PhilRunninger** [comment]
@mishaszu , @gmg137 , if you want me to take a look at this any further, please put a minimal `.vimrc` file in this issue so I can reproduce the issue.

**Comment by gmg137** [comment]
It can be confirmed that the problem is caused by installing ycm.

Here's my vimrc configuration:
```
"YCM 设置
"在任何时候都显示注释菜单，那怕在注释中
let g:ycm_complete_in_comments = 1
"从注释的字符串中收集标识符
let g:ycm_collect_identifiers_from_comments_and_strings = 1
"从 tags 文件中收集标识符
"let g:ycm_collect_identifiers_from_tags_files = 1
"自动关闭 preview 窗口
let g:ycm_autoclose_preview_window_after_completion = 1
"从vim语法文件中提取关键字
let g:ycm_seed_identifiers_with_syntax = 1
"设置实例触发键
let g:ycm_key_invoke_completion = '<C-Space>'
"禁用 ycm 补全的文件类型
let g:ycm_filetype_blacklist = {
      \ 'tagbar'  : 1,
      \ 'qf'      : 1,
      \ 'notes'   : 1,
      \ 'unite'   : 1,
      \ 'vimwiki' : 1,
      \ 'pandoc'  : 1,
      \ 'infolog' : 1,
      \ 'html' : 1,
      \ 'mail'    : 1
      \}

"nerdtree 配置
"自动启用
"autocmd vimenter * NERDTree
```

**Comment by mishaszu** [comment]
I don't use `YCM` anymore and still have the same issue. [I also asked question here](https://vi.stackexchange.com/questions/25676/auto-completion-pop-up-no-clean-up-how-to-debug).
I tried to play with turning on/off all my plugins. So far I found it more frequent for some languages with a specific color schemes.

**Comment by PhilRunninger** [comment]
@mishaszu, you said in your [stackexchange question](https://vi.stackexchange.com/questions/25676/auto-completion-pop-up-no-clean-up-how-to-debug) that this happens even when NERDTree is removed. Given that, I agree that this doesn't look like a NERDTree issue.

Does the issue happen with multiple windows; in other words, could the auto complete feature have a hard time with the split window? Does it matter what is in the other window, or does it need to be NERDTree to cause the issue? Try creating a blank split window first - `:vnew` - and then see if the error occurs.

You mentioned colorschemes. I don't know how it makes a difference, especially with one as simple as panda-vim, but you could try a different one to see if that fixes it. There are lots out there; https://vimcolors.com/ has an extensive list.

It could be a bug in YCM, CoC and ALE, especially if they have similar code.

But more likely it's a bug in Vim. I suggest you continue asking questions on your stackexchange question, and see if **filbranden** thinks it's worth creating an issue in the Vim project.
